### ISSUE TITLE
Images not properly working if they contain a space in the name

### ISSUE THREAD

**Issue by Jakz** [gnosygnu/xowa#125] opened 2017-01-31 21:58 UTC
Hello, I've been able to download a dump of a wiki hosted on Wikia through wikiteam Python scripts. Dumping the database and importing it into XOWA worked nicely and I've been able to customize the css to match the one of the original wiki.

The only issue I'm having is how to map images (which I have, as single files) to the imported wiki. ~~In the documentation I only see that you usually download pre-made packages which are directly copied into the root wiki but that's not the case so I'm wondering how to do it (or which part of the engine manages this part so that I can further investigate how to solve my problem).~~

I've been able to make XOWA see the images (or at least so it seems, by following [this](https://sourceforge.net/p/xowa/discussion/general/thread/91f5df9f/#ed2d) discussion) but images are only partially working. Some of them work, while others don't. If I inspect the HTML of the final page I can see for example

```
<a href="/wiki/File:Citizen_Barbarian_Rebel.png" class="image" xowa_title="Citizen_Barbarian_Rebel.png"><img id="xoimg_5" alt="" src="" width="-1" height="-1"></a>
```

so while a certain `id` is set (which I guess is a computed mapping) this doesn't seem to work for all the images of the wiki (although they are present in the folder containing them all.

Thanks

**Comment by Jakz** [comment] 2017-01-31 23:23
I actually found the issue. It was related to the fact that a previous sqlite3 database was present in the orig folder, then I tried restarting from scratch with a different wiki path without deleting the database so there were some references to files which wasn't existing anymore. Now everything seems to work fine, I'm currently testing multiple pages to check it.

**Comment by gnosygnu** [comment] 2017-01-31 23:25
Hi! Thanks for the interest in XOWA!

> Hello, I've been able to download a dump of a wiki hosted on Wikia through wikiteam Python scripts. Dumping the database and importing it into XOWA worked nicely and I've been able to customize the css to match the one of the original wiki.

Cool. Glad to hear that you were able to customize the css. Just in case you ever need it, XOWA also supports custom javascript and lua. See #88 

> I've been able to make XOWA see the images (or at least so it seems, by following this discussion) but images are only partially working. Some of them work, while others don't. 

Your link to the discussion is correct. Just so you know, there's also an active discussion in #124 . The only known issue is that XOWA is not showing images in a File namespace page. For example, something like <code>my_wiki/wiki/File:My_image.png</code>would not show any images.

By any chance, are you not the missing images on these File namespace pages? If you're seeing it on other pages, then I'm not sure what it could be. Here are two guesses:

* Imagemagick and Inkscape are not set up on the machine. I don't expect that to be the issue as your example shows a png which would use Imagemagick, and presumably Imagemagick is set up. (a lot of images would be missing if it wasn't)
* You're viewing the images on one machine in one path (X:\xowa) and they don't show up on another machine under a different path (Y:\xowa). If you're on the same machine, this wouldn't apply

If it's neither of these issues, then can you provide the following:
* The exact path of the file, and whether or not it exists? For your example, using your "Citizen_Barbarian_Rebel.png" you can check ....
    * The original folder: <code>C:\xowa\wiki\your_wiki\file\orig\2\25\</code>
    * The thumb folder: <code>C:\xowa\wiki\your_wiki\file\thumb\2\25\</code>
* The actual Wikia and page used. I'm assuming this is the "Master of Magic" Wikia? (which, off-topic, was a great game. :))

> If I inspect the HTML of the final page I can see for example ... so while a certain id is set (which I guess is a computed mapping) this doesn't seem to work for all the images of the wiki (although they are present in the folder containing them all.

Yeah, the id is automatically generated by XOWA. The src, width, and height are filled in afterwards, but unfortunately, in custom wikis, they don't show up in the HTML. I'll try to fix that for a future build

Hope this helps.

Thanks!

**Comment by gnosygnu** [comment] 2017-01-31 23:29
Oops. Commented just a few minutes after you closed it. 

> I actually found the issue. It was related to the fact that a previous sqlite3 database was present in the orig folder, then I tried restarting from scratch with a different wiki path without deleting the database so there were some references to files which wasn't existing anymore. 

I think the different wiki path is the "one machine in one path" issue from above. I'm assuming you deleted the <code>^orig_regy.sqlite3</code> file because it had wrong paths in the <code>orig_fil</code> table?

If so, I have this fixed in the next build. Let me know if you want to try a preview build and I'll upload one to my Google Drive account. Just let me know which Operating System and Bitness you use (for example, Windows 64-bit)

Thanks.

**Comment by Jakz** [comment] 2017-01-31 23:37
Maybe I spoke too soon :)

I deleted the sqlite3 file and the issue fixed itself but it's occurring again. For example:

- I delete the cache, launch xowa and all the images are correctly processed and shown.
- Then I close the application, I relaunch it and no images already cached are shown BUT new images which weren't yet cached (and mapped into the database) are correctly processed.
- From this time on, every time the program is launched the previously cached images are not shown until I totally wipe the `^orig_regy.sqlite3` and start again.

**Comment by gnosygnu** [comment] 2017-02-01 00:12
Ah, that stinks. :(

Unfortunately, I can't reproduce this on my side. I'm trying with the Nethack wiki and "https://nethackwiki.com/wiki/Monster". I think I'm doing what you're doing:
* Going to nethackwiki.com/wiki/Monster
* Wait about 1 min for all the images to generate on the page
* Close XOWA
* Reopen XOWA
* Go back to nethackwiki.com/wiki/Monster . Images are still there

By any chance, are your images all SVG? #124 reported disappearing images, but only for SVG. Unfortunately, I can't reproduce this either. I've tried this on the Nethack wiki for https://nethackwiki.com/wiki/Keyboard

If you want, I can make a debug version for you to try out, but it won't be ready until sometime tomorrow. If so, let me know which Operating System you're on, and I'll upload a copy.

Thanks!

**Comment by Jakz** [comment] 2017-02-01 00:24
I'm on OS X 10.11 64 bit, I'm trying to understand what's happening by testing some modifications in configuration but the issue seems to persist. All images are PNG or GIF, not any SVG.

I can see that the thumb folder is created by replacing underscore with spaces, is this the intended behavior? For example let's assume image `Hero_Aerie.png`, then after closing the application I have

     orig/Hero_Aerie.png
     thumbs/Hero Aerie.png/60.png

and an entry inside the database which is

    | 293 | Hero_Aerie.png | 1 | 64 | 64 | /Path/to/orig |

Thanks for your support! It's really appreciated!

**Comment by gnosygnu** [comment] 2017-02-01 00:41
> I can see that the thumb folder is created by replacing underscore with spaces, is this the intended behavior? 

That's strange. It should always be underscores: both in orig and thumb. For example, on my machine, I have <code>C:\xowa\wiki\nethackwiki.com\file\thumbs\0\00\Wizard_of_Yendor.png\16.png</code>

Let me look at it some more. When you get a chance, can you try the following:
* Renaming the folder from <code> thumbs/Hero Aerie.png/60.png</code> to <code> thumbs/Hero_Aerie.png/60.png</code>
* Opening the page in XOWA and seeing if that one file shows

> Another interesting thing (maybe unrelated, maybe not) is that I always see 0.000 B in cache info inside Special:XowaCfg 

Yeah, this has to do with custom wikis which doesn't use the regular cache (the one at C:\xowa\file). I'm making a few changes to it, but don't think I'll get the cache fully integrated. So for now, just ignore it. ;)

Thanks!

**Comment by Jakz** [comment] 2017-02-01 01:02
No actually the issue is different. The file is referred with the underscore in the wiki, saved without space in the orig folder and generated (as you stated) without underscore if it didn't have it. But renaming the thumbs folder with underscore fixes the problem. So to recap:

- image is saved as `"orig/SpellIcon PsionicBlast.png"``
- image is referred in wiki pages as `[[File:SpellIcon_PsionicBlast.png]]`
- image is generated as `"thumbs/SpellIcon PsionicBlast/38.png"`
- it correctly shows the first time it's cached
- it doesn't show anymore successive times
- renaming `"thumbs/SpellIcon PsionicBlast/38.png"` to `"thumbs/SpellIcon_PsionicBlast/38.png"` seems to fix the problem

**Comment by gnosygnu** [comment] 2017-02-01 02:47
Cool. Thanks for the breakdown. I was able to try it on my side, and can verify that you're right. If the original has a space ("orig/SpellIcon PsionicBlast.png") then this will cause XOWA problems.

Let me figure out a few things on my side. I should have a test build sometime tomorrow.

Thanks!

**Comment by gnosygnu** [comment] 2017-02-01 22:02
I uploaded a new build (v4.0.3.1702) that should handle all the issues. See https://drive.google.com/open?id=0B9cb52zjL2rINkhhdVNSVjR5Mms . I give a detailed breakdown below the break. Note that I copy-pasted this from #125.

I also reply to one of your points below. Let me know if I missed anything above. In the meantime, I'm going to mark the issue resolved.

Finally, I like to give credit to users for reporting bugs. Right now, there is a line in the XOWA Change Log with "Rename files by replacing "spaces" with "underscores" {detected by anonymous}". There are a few other lines as well. Let me know if you want to be cited by nickname or would rather remain anonymous

Otherwise, thanks for sticking with the bug and figuring out the cause!

----

> So I guess that xowa expects images not to contain spaces, I don't know if this is a problem maybe of wikiteam which should insert underscores or if translation should allow a reference with `_` to translate to a space when looking for the image. 

Yeah, IMHO, it should always be underscore. The url has underscore (http://vignette3.wikia.nocookie.net/masterofmagic/images/3/33/SpellIcon_PsionicBlast.png/revision/latest?cb=20120115004618) and everything I've seen in MediaWiki code treats it as an underscore.

I do agree that the dumpgenerator.py script should be changed. I detailed the change at http://xowa.org/home/wiki/App/Wiki_types/Wikia.com . I'll try to put in a pull request for this later

The new build will automatically rename these files so that the spaces are replaced with underscores. See more below.

Also, out of curiosity, you mentioned that you customized the css to reproduce the look and feel of the Wikia wiki. Out of curiosity, how difficult was it? I'm curious if it could be automated, but didn't want to jump down that rabbit hole yet.

----

Changes in v4.0.3.1702
* **Images in the File namespace will now show**: For example, https://nethackwiki.com/wiki/File:Keyboard_shortcuts.svg . Note that clicking on an image here will also open it up in your image viewer.
* **File names with spaces are automatically renamed to use underscores**: For example, <code>SpellIcon PsionicBlast.png</code> will be renamed to <code>SpellIcon_PsionicBlast.png</code>
    * This matches online behavior where the url has an "_" not a space. For example, http://vignette3.wikia.nocookie.net/masterofmagic/images/3/33/SpellIcon_PsionicBlast.png/revision/latest?cb=20120115004618
    * A log is generated of all renames and saved to "orig.changes.log"
* **SVG thumbnails will now use ".png" instead of ".svg"**: For example, "C:\xowa\file\nethackwiki.com\thumb\8\3\f\d\Keyboard_shortcuts.svg\800px.png"
* **View HTML will now show the img src and width info**: For example, &lt;img id="xoimg_1" alt="File%3AKeyboard+shortcuts.svg" src="file:///D:/xowa_temp/file/nethackwiki.com/thumb/8/3/f/d/Keyboard_shortcuts.svg/800px.png" width="800" height="293" /&gt;
* **Images are now integrated directly into the app file cache**: See <code>home/wiki/Special:XowaCfg?grp=xowa.files.general</code>. This means that a separate thumbs directory is no longer generated
* **A startup script is no longer needed**: You can (and should) remove the startup script at <code>home/wiki/Special:XowaCfg?grp=xowa.app.startup</code>. XOWA now automatically assumes that all non-WMF wikis will have offline files in the wiki directory. For example, <code>C:\\xowa\\wiki\\your_wiki\\file\\orig\\</code>
* **Updated instructions**: I updated the instructions at http://xowa.org/home/wiki/App/Wiki_types/Wikia.com

**Comment by gnosygnu** [comment] 2017-02-05 01:26
Tonight's release officially includes the fixes listed above. I'm going to go ahead and close this ticket. Let me know if there's anything else. Thanks.

**Closed by gnosygnu** 2017-02-05 01:26 UTC
Labels: images, non wikimedia, resolved

**Comment by Jakz** [comment] 2017-02-15 20:17
Sorry for the late of response, I've been away for some days!
Thanks you for fixing the issue, it's fine if you use my nickname or keep it anonymous, doesn't really matter, I'm glad to have helped!

Customizing the CSS hasn't been too difficult, I've started inspecting the original CSS through Firebug and copied everything in the one embedded in XOWA, then by opening and reopening the application I saw what was working and what wasn't and patched the CSS accordingly.

**Comment by gnosygnu** [comment] 2017-02-15 21:24
Hey, no worries for the delay.

> Thanks you for fixing the issue, it's fine if you use my nickname or keep it anonymous, doesn't really matter, I'm glad to have helped!

Cool. I put it down for Jakz. It'll show up after next week's update at http://xowa.org/home/wiki/Change_log/v4.1.0.1702 . Feel free to change your mind

> The only real problem is that there is no way to refresh the page directly (I guess the CSS is cached) 

Yup, the CSS is cached, but it's still available directly on disk. For example, for <code>en.wikipedia.org</code> they'd be at <code>C:\xowa\user\anonymous\wiki\en.wikipedia.org\html</code> You should be able to edit them in a text editor and see the results immediately when you refresh the page in XOWA

> and that there's no way to inspect the result HTML in a practical way, having a way to have a static version of current XOWA page saved on disk and refreshed automatically would help since you would be able to use external tools to check and verify the generated HTML.

Yeah, the process is a bit tedious. I'm hoping to integrate XOWA with Chromium someday which should make real-time DOM inspection easier.

Until that day arrives, I do the following when experimenting with HTML / CSS.
* Do <code>View HTML</code> for the page in question
* Save it to a text file like <code>C:\xowa\temp.html</code>
* View <code>C:\xowa\temp.html</code> in Chrome
* Also open the page in XOWA
* Open <code>C:\xowa\temp.html</code> in notepad++
* Open the following in notepad++:
    * **Wiki's CSS**: The CSS files in <code>C:\xowa\user\anonymous\wiki\en.wikipedia.org\html</code>. For example, <code>C:\xowa\user\anonymous\wiki\en.wikipedia.org\html\xowa_common.css</code>
    * **XOWA's master page layout**: <code>C:\xowa\bin\any\xowa\cfg\app\xowa.gfs</code>. The relevant section is under <code>page_read</code>

So, regarding changes:
* Changes to <code>Wiki CSS</code> can be seen by just reloading the page in XOWA
* Changes to <code>xowa.gfs</code> can only be seen by restarting XOWA. I'll change that sometime in the future, but I've been wanting to make that section a "mustache template" file.
* Changes to <code>temp.html</code> and <code>Wiki CSS</code> can be seen by reloading in Chrome. I usually do the bulk of my changes here before pushing anything to <code>xowa.gfs</code>

Finally, keep in mind that <code>xowa.gfs</code> is replaced on every application update. If you're making changes, you should make them to <code>Wiki CSS</code> (and back up those files too)

If you need to make changes to <code>xowa.gfs</code>, let me know, and I'll add a user-configurable version of <code>xowa.gfs</code> for a future release. Otherwise, you will need to manually update the <code>xowa.gfs</code> on your side yourself.

Anyway, hope this is useful.

Thanks!
