### ISSUE TITLE
Synced/Updated pages only appear after refresh.

### ISSUE THREAD

**Issue by khanhhung2512** [gnosygnu/xowa#137] opened 2017-03-10 02:24 UTC
I accessed some pages for the first time and they showed the old wiki pages. Only after hitting F5 do the new updated pages appear.

Example: en.wikipedia.org/wiki/2016–17_UEFA_Champions_League_knockout_phase

**Comment by gnosygnu** [comment] 2017-03-10 03:45
Hey, thanks for creating the issue.

I tried it just now, but couldn't reproduce. Here were my steps:
* Make sure Automatic page sync was disabled
* Open en.wikipedia.org/wiki/2016–17_UEFA_Champions_League_knockout_phase
* Scroll down to the scores section
* Enable Automatic page sync
* Reopen en.wikipedia.org/wiki/2016–17_UEFA_Champions_League_knockout_phase
* Scroll down to the scores section: The score section was updated.

You could also refer to the gif below

Does this happen for every single automatic page sync page? If so, I can add some more logging and see if it can pinpoint what is going on.

Let me know if you have any thoughts. Thanks.

----

![page_sync](https://cloud.githubusercontent.com/assets/4994104/23781206/ab5bf83a-0519-11e7-8744-6f9bd74d651b.gif)

**Comment by khanhhung2512** [comment] 2017-03-10 11:46
> Does this happen for every single automatic page sync page? If so, I can add some more logging and see if it can pinpoint what is going on.

It happens for every page I checked.
[session.txt](https://github.com/gnosygnu/xowa/files/833815/session.txt)

**Comment by gnosygnu** [comment] 2017-03-11 03:40
Thanks for the log but unfortunately it doesn't show much:
* 2016–17_FA_Cup looks like it required a double-load
* 2016–17_DFB-Pokal looks like just a single one

Out of curiosity what are your options at Special:XowaCfg?grp=xowa.bldr.page_sync
* Enabled should be checked
* Time to wait: the default is 1440 but I'm wondering if you changed it
* Pages to sync: the default is * but I'm wondering if you changed it

You can also try deleting C:\xowa\wiki\en.wikipedia.org\en.wikipedia.org-sync.xowa . This stores when you last sync'd the page. It's possible that maybe you have dates for previously viewed pages here.

**Comment by khanhhung2512** [comment] 2017-03-11 12:46
Manual and automatic syncs enabled. The other things are just as defaults. And I'm pretty sure I'd never opened those pages before.

The thing is it does sync, but it only shows the updated pages after I hit Refresh (F5).

**Comment by gnosygnu** [comment] 2017-03-12 03:00
Ok. Thanks for the confirm. Those options should be fine.

I walked through it in debug mode and the sequence is definitely:
* Check to see if page needs sync
* If sync is needed, sync page from online
* Show page using the sync copy.

So unfortunately, I don't have any immediate ideas.

Let me think about it some more. If I can't figure anything out, I'll add more logging code and ask you to try reproducing it again.

Thanks.

**Comment by gnosygnu** [comment] 2017-03-14 02:57
I think I was able to find the cause of the issue. When you get a chance, try again with https://github.com/gnosygnu/xowa/releases/tag/v4.4.2.1703 . If it still doesn't work, upload the log again; there will be a few more logging statements.

Thanks.

**Comment by khanhhung2512** [comment] 2017-03-18 16:46
Apparently, it works.

**Comment by gnosygnu** [comment] 2017-03-19 00:29
Cool. Thanks for the follow-up. Let me know if you find anything else. Otherwise, I'll mark this issue closed after the next official release.

**Comment by gnosygnu** [comment] 2017-03-30 02:34
As the fix was part of tonight's v4.5 release, I'm going to close this issue. Thanks.

**Closed by gnosygnu** 2017-03-30 02:34 UTC
Labels: page sync, resolved
