### ISSUE TITLE
coordinate precision

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#792] opened 2020-08-24 22:28 UTC
Looking at `en.wikipedia.org/wiki/Huntington_Plaza` (enwiki dump 2020-08-01)
mw shows the coordinate as `39°57'42.37"N 83°0'7.06"W`
whereas xowa is `39°57'42.4"N 83°0'7.1"W`

Note the difference in precision of the seconds (2 for mw, 1 for xowa)

The logic doing the work is in `400_xowa\src\gplx\xowa\xtns\mapSources\Map_math.java`

However looking at the PHP `https://github.com/wikimedia/mediawiki-extensions-MapSources/blob/master/includes/MapSourcesMath.php`, I cannot see how this level of precision is captured
Both mw and xowa seem to be doing the same amount of rounding - but somehow there is a difference

Another way of showing this is the wikitext

    {{#property:P625|from=Q97626701}}

BTW there is a small bug in Map_math. In the function Set_coord is a check for `prec > 0` line 77
This should be `prec > 4`

**Comment by gnosygnu** [comment] 2020-08-25 13:38
Hey, thanks for the detailed breakdown as well as the catch for the bug on line 77

I think the problem is this line: https://github.com/gnosygnu/xowa/blob/f73164d55e70817bced6ab4bfea0dcc413008ddc/400_xowa/src/gplx/xowa/xtns/wbases/Wdata_prop_val_visitor.java#L160 It takes a value of `1.0e-5` and returns back a precision of `5`. If it's 6, the rest works properly

I tried to find the corresponding line in Wikidata source code but could not. The logic above looks suspect, b/c I don't think `3600` should just get log'd 10 to be `3`.

Will look more later.

**Comment by desb42** [comment] 2020-08-28 14:45
Even with the fix to #565, I have just rebuilt xowa and the coordinate precision is still 'off by one'

I wonder if the precision is being determined in a different way (say, from the longitudinal value?)

**Comment by desb42** [comment] 2020-09-01 15:32
To add grit to the idea of determining precision in a different way
Looking at `en.wikipedia.org/wiki/College_and_university_rankings`, a number of #invoke errors occur to do with coordinates

This page includes `en.wikipedia.org/wiki/U.S._News_%26_World_Report_Best_Colleges_Ranking`
which in turn uses `en.wikipedia.org/wiki/Template:U.S. News top 10`

This template uses `en.wikipedia.org/wiki/Template:U.S._News_top_10/institution`
which goes on to use `en.wikipedia.org/wiki/Template:Wikidata`

This is where it gets 'interesting'

substituting for two of the Universities

    {{wikidata|property|raw|page=Duke University|coord}}
    {{wikidata|property|raw|page=Johns Hopkins University|coord}}

gives

    36/N/79/W
    39/19/44/N/76/37/14/W

respectively (the first result would lead to the invoke error)

Looking at the wikidata for these two universities

`www.wikidata.org/wiki/Q193727` (Johns Hopkins University), the location info  (in JSON) is

    { "P625":
      [ 
        { "snaktype":"value"
        , "property":"P625"
        , "hash":"58258df2ce0bb139c71bf8dc2e9c823d6919e90b"
        , "datavalue":
          { "value":
            { "latitude":39.32888888888889
            , "longitude":-76.62027777777777
            , "altitude":null
            , "precision":0.0002777777777777778
            , "globe":"http:\/\/www.wikidata.org\/entity\/Q2"
            }
          , "type":"globecoordinate"
          }
        }
      ]

`www.wikidata.org/wiki/Q168751` (Duke University)

    "P625":
    [ 
      { "mainsnak":
        { "snaktype":"value"
        , "property":"P625"
        , "hash":"bf28d1eef46674a5493f47c9e50b0dcb831f5947"
        , "datavalue":
          { "value":
            { "latitude":36.001111111111
            , "longitude":-78.938888888889
            , "altitude":null
            , "precision":null
            , "globe":"http:\/\/www.wikidata.org\/entity\/Q2"
            }
          , "type":"globecoordinate"
          }
        }
Note for Johns Hopkins there is a `precision`, but not for Duke

putting the two lines of wikitext in en.wikipedi.org/wiki/Wikipedia:Sandbox gives

    36/0/4/N/78/56/20/W
    39/19/44/N/76/37/14/W

It seems mw is doing something different

**Comment by gnosygnu** [comment] 2020-09-02 12:51
> To add grit to the idea of determining precision in a different way

Nice breakdown! The problem is this line of code: 
https://github.com/gnosygnu/xowa/blob/341d2e13a43bb91e40b0c0204a750a5f56780a26/400_xowa/src/gplx/xowa/xtns/wbases/claims/itms/Wbase_claim_globecoordinate.java#L33

If I change `null` to be `0` instead of `1` than the output matches MW for the text below. I'll change it tomorrow (want to add a test)

The other interesting thing is that [`{{wikidata}}`](https://en.wikipedia.org/w/index.php?title=Module:Wd&action=edit) calculates the display string differently than Wdata_prop_val_visitor. I'll go through the code and see why precision is different

```
{{wikidata|property|raw|page=Huntington Plaza|coord}}<br/>
{{wikidata|property|raw|page=Duke University|coord}}<br/>
{{wikidata|property|raw|page=Johns Hopkins University|coord}}<br/>
```

**Comment by gnosygnu** [comment] 2020-09-07 21:29
Fixed with the commit above. Basically, took logic from https://en.wikipedia.org/w/index.php?title=Module:Wd&action=edit 

Confirmed with en.wikipedia.org/wiki/Huntington_Plaza as well as with unit tests

Thanks for the awesome breakdown!

**Comment by desb42** [comment] 2020-09-19 08:55
Found another exception
`en.wikipedia.org/wiki/Goonhilly_Satellite_Earth_Station`

The coordinates are not showing correctly

I have pinned this down to the following wikitext

    {{Coord
    |3=type:landmark
    |qid=Q1537712
    |display=inline,title
    |format=dms
    }}
which can be 'run' in Wikipedia:Sandbox to show the issue (a nan)

**Comment by desb42** [comment] 2020-09-19 12:31
This is my attempt to make it work

[Wbase_claim_globecoordinate.zip](https://github.com/gnosygnu/xowa/files/5249835/Wbase_claim_globecoordinate.zip)

**Comment by gnosygnu** [comment] 2020-09-19 13:51
Nice! Thanks for the commit as well as reopening the ticket. Will return to this issue after the Simple Wikipedia ones

**Comment by gnosygnu** [comment] 2020-09-25 12:46
Pushed with the commit above. Thanks for the contribution!

**Closed** 2020-10-20 12:29 UTC
Labels: [effort 3 - less than a week], [priority 3 - moderate], [resolved - commit], [risk 2 - major], [schedule 2 - within weeks], [type - bug], core - parser, xtn - wikibase
