### ISSUE TITLE
invoke failed: Portal:Germany {{#invoke:Excerpt slideshow|listItemExcerpt}}

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#366] opened 2019-02-23 10:18 UTC
this is a follow on from #365 

I have tracked this error to the template (inside Portal:Germany)

    {{Transclude list item excerpts as random slideshow | paragraphs=1-3 | files=1 | more=
    | Template:Germany topics
    |
    }}
This in turn invokes Module:Excerpt slideshow
By manipulating the code in this module I can trigger the error
If I add the following to the start of the function p._excerpt

    p._excerpt = function(_args, method)
    local exc = 'sajhdsgkjgdkhagdjhsgdkjashgdkashdgkjsdgjhdgkjadgksdjhskjhk'
    readmore_start_index, readmore_end_index, readmore_text = mw.ustring.find(exc, "('''%b[]''')$", -350)
It fails with the above error
The ustring.find line comes from elsewhere within this module

I do not think this should cause an error - just return 'unfound' values

**Comment by gnosygnu** [comment] 2019-02-23 15:33
Wow, thanks for the write-up.

I was able to reproduce the bug here.

```
function p.test21(frame)
  local exc = 'sajhdsgkjgdkhagdjhsgdkjashgdkashdgkjsdgjhdgkjadgksdjhskjhk'
  return mw.ustring.find(exc, "('''%b[]''')$", -350)
end
```

The problem is the -350.
* In MediaWiki, the ustring.find returns ""
* In XOWA, the ustring.find fails with an ``` java.lang.IndexOutOfBoundsException: Illegal start index```

I'll have a fix for this either later today or tomorrow.

Thanks!

**Comment by gnosygnu** [comment] 2019-02-24 21:21
So, this became a more complicated fix. I discovered that I had inconsistent usages of string-lengths / positions in different parts of ustring.find (and ustring.match)

In summary:
* Fixed the -350 bug above
* Fixed a variety of bugs related to using supplementary characters (codepoints that are 3 bytes and 4 bytes: think Chinese characters)
* Refactored the code a bit to add more comments
* Added an auto-generating test suite to generate wikitext to test against Wikipedia and XOWA. See example below

----

```
-- Preview at https://en.wikipedia.org/wiki/Project:Sandbox
-- Generate by changing dbg=true in Scrib_lib_ustring__find__tst and running test
{| class=wikitable
! rslt !! expd !! actl !! code 
|-
| {{#ifeq:{{#invoke:Sandbox/Gnosygnu|ustring_find|a|()|2|false}}|2;1;2|<span style='color:green'>pass</span>|<span style='color:red'>fail</span>}}
| 2;1;2
| {{#invoke:Sandbox/Gnosygnu|ustring_find|a|()|2|false}}
| <nowiki>{{#invoke:Sandbox/Gnosygnu|ustring_find|a|()|2|false}}</nowiki>
|-
| {{#ifeq:{{#invoke:Sandbox/Gnosygnu|ustring_find|abab|b|-1|true}}|4;4|<span style='color:green'>pass</span>|<span style='color:red'>fail</span>}}
| 4;4
| {{#invoke:Sandbox/Gnosygnu|ustring_find|abab|b|-1|true}}
| <nowiki>{{#invoke:Sandbox/Gnosygnu|ustring_find|abab|b|-1|true}}</nowiki>
|-
| {{#ifeq:{{#invoke:Sandbox/Gnosygnu|ustring_find|abab|b|-9|true}}|2;2|<span style='color:green'>pass</span>|<span style='color:red'>fail</span>}}
| 2;2
| {{#invoke:Sandbox/Gnosygnu|ustring_find|abab|b|-9|true}}
| <nowiki>{{#invoke:Sandbox/Gnosygnu|ustring_find|abab|b|-9|true}}</nowiki>
|-
| {{#ifeq:{{#invoke:Sandbox/Gnosygnu|ustring_find|𤭢|𤭢|-1|true}}|1;1|<span style='color:green'>pass</span>|<span style='color:red'>fail</span>}}
| 1;1
| {{#invoke:Sandbox/Gnosygnu|ustring_find|𤭢|𤭢|-1|true}}
| <nowiki>{{#invoke:Sandbox/Gnosygnu|ustring_find|𤭢|𤭢|-1|true}}</nowiki>
...
|}
```

**Closed** 2019-03-02 14:09 UTC
Labels: [effort 3 - days], [impact 3 - few classes], [priority 2 - major], [resolved - commit], [schedule 1 - within days], [type - bug], core - parser, xtn - scribunto
