### ISSUE TITLE
Script error No such module

### ISSUE THREAD

**Issue by GitterHubber** [gnosygnu/xowa#109] opened 2016-12-04 15:52 UTC
I've been using Xowa for over a year now and no issues whatsover many thanks for the great app that you have created.

Today I tried installing it on another PC at another location.

Xowa Ver		3.2.1.1 64bit
Target Arch 	64bit
Target OS 		Windows

I was trying to import a text dump from wikipedia **enwiki-20160204-pages-articles.xml.bz2**
In Xowa I went to Tools > Import Offline and pointed to the location where the bz2 file existed
For category system I selected "version 2" and kept all other settings untouched.
Then I clicked "Import" and the process started, unfortunately the process got terminated before it could complete.

So If I visit the main page of Wikipedia in Xowa I get around 3million articles while on my PC where I have been using Xowa for a year I have 5 million articles.

I have read your answer to a similar problem [here](https://sourceforge.net/p/xowa/discussion/general/thread/88b582f6/)

I just needed some basic steps as how to correct this issue, I mean what folders do I have to  delete, what do I have to extract and where etc.

This is a screen shot

![error wiki xowa](https://cloud.githubusercontent.com/assets/2816034/20867315/e2174f66-ba67-11e6-9d29-d6236cae5c03.png)

**Comment by gnosygnu** [comment] 2016-12-04 17:03
Hi! Thanks for the screenshot as well as the detail.

Based on the fact that you're using v3.2.1.1 and a 2016-02 dump, it sounds like it was just a bad import. Is it possible that you ran out of disk space during the import process (as described in the referenced sourceforge link?)

Really, the best thing to do is to just redo the entire import. That would just involve deleting all files in C:\xowa\wiki\en.wikipedia.org . (Don't delete "enwiki-20160204-pages-articles.xml.bz2" if you put it there)

If it fails again, can you post the log from home/wiki/Special:XowaSystemData?type=log_session

**Comment by GitterHubber** [comment] 2016-12-04 17:55
Thanks for the immediate response! 

I will do as you said and respond as soon as I have something.

Many thanks for your time again!!

**Comment by GitterHubber** [comment] 2016-12-05 05:56
> Is it possible that you ran out of disk space during the import process

Sorry! I missed your question the last time around, In fact it was a power outage that interrupted the process so I tried re-importing again without deleting any folders, and then I got the script error as mentioned in my original post.

This type around I will follow your steps though.

**Comment by gnosygnu** [comment] 2016-12-05 06:32
> I missed your question the last time around, In fact it was a power outage that interrupted the process so I tried re-importing again without deleting any folders, and then I got the script error as mentioned in my original post.

Yeah, a power outage would probably cause the above.

A re-import should fix it. If it doesn't, post a log and I'll take a look.

Thanks!

**Comment by GitterHubber** [comment] 2016-12-05 08:44
Hi again! I re-imported it again and this time there was no interruption to the process. C and I (where xowa is currently) drive also have free space of 24GB and 170GB each.

I am getting an sql file not found error, this happened even yesterday I missed telling you that.
Attaching the logs.

![sql error](https://cloud.githubusercontent.com/assets/2816034/20878465/210e4142-baf5-11e6-885d-6c76c5299904.png)
[internet.txt](https://github.com/gnosygnu/xowa/files/630548/internet.txt)
[session.txt](https://github.com/gnosygnu/xowa/files/630549/session.txt)
[err.txt](https://github.com/gnosygnu/xowa/files/630550/err.txt)

**Comment by gnosygnu** [comment] 2016-12-06 03:11
> Hi again! I re-imported it again and this time there was no interruption to the process. C and I (where xowa is currently) drive also have free space of 24GB and 170GB each.

Hmm... It still looks like a lot of data is missing. 170 GB is enough for the import, so my above guess about running out of space doesn't seem relevant.

How big is the following file: enwiki-20160204-pages-articles.xml.bz2 ? It should be around 12.0 GB. Is yours smaller, like 8 GB?

If it is 12 GB, then I don't know why XOWA isn't importing it all. There is no import error in the log file, but the total number of pages is 9,373,103 . There haven't been 9.3 million pages in several years.

> I am getting an sql file not found error, this happened even yesterday I missed telling you that.
Attaching the logs.

Thanks for the logs. It looks like the category setup is failing because you are using Import/Offline and don't have the Category dump files (categorylinks.sql and page_props.sql)

You can ignore these if you don't use the Category system. For example, https://en.wikipedia.org/wiki/Category:Earth

If you do use the Category system, then you're going to have to download the two dump files. However, Wikimedia no longer has 20160204 dump files available: https://dumps.wikimedia.org/enwiki/. You're going to have to download a more recent set, for example 20160720.

Hope this helps. Thanks.

**Comment by GitterHubber** [comment] 2016-12-06 05:29
Hi again!

> How big is the following file: enwiki-20160204-pages-articles.xml.bz2 ?
its around 12 GB

> 
It looks like the category setup is failing because you are using Import/Offline and don't have the Category dump files (categorylinks.sql and page_props.sql)

So should I delete the en.wikipedia.org folder and re-import with the default 'version 1' setting for Category system?

**Comment by gnosygnu** [comment] 2016-12-07 02:58
>> How big is the following file: enwiki-20160204-pages-articles.xml.bz2 ?

> its around 12 GB

Thanks. That sounds like the right size. Don't know why it's failing though...

> So should I delete the en.wikipedia.org folder and re-import with the default 'version 1' setting for Category system?

Yeah, you can give that a try. "Version 1" doesn't need the category dumps, so that will handle the category error. Maybe another import may handle the missing pages, though at this point, I don't have any ideas....

Hope that helps.

**Comment by GitterHubber** [comment] 2016-12-07 07:30
I deleted the directory (en.wikipedia.org) and re-imported with Category system as "Version 1" however the problem still persists.

I have now 2 options:

1. Make a copy of the wikipedia that is working on my PC and clone and transfer it to the other PC.
2. Download the latest wiki pages and articles dump along with the .sql files that you referred to and try importing with that.

**Comment by gnosygnu** [comment] 2016-12-08 02:12
> I deleted the directory (en.wikipedia.org) and re-imported with Category system as "Version 1" however the problem still persists.

Sorry to hear that. I'm a bit surprised that 3.2 is still failing for the missing category dump, but I can't really reproduce 3.2 / 201602 on my side.

> Make a copy of the wikipedia that is working on my PC and clone and transfer it to the other PC.

This is the easiest. In the end, you should only have to transfer one folder between the two machines: C:\xowa\wiki\en.wikipedia.org (or wherever you installed XOWA). This is just a straight file copy, and doesn't require any special handling

> Download the latest wiki pages and articles dump along with the .sql files that you referred to and try importing with that.

If you download the latest wiki pages, then you'll also need the latest XOWA. I made a number of changes to XOWA in v3.9.2 and up to handle changes in the Wikipedia Category system. You can look at https://github.com/gnosygnu/xowa/issues/108#issuecomment-264715672 for more info. Also, you may want to look at the reported issue in #111 as well.

Let me know which way you go, and if there's anything I can do to help.

Thanks.

**Comment by GitterHubber** [comment] 2017-01-07 10:29
I ended up making a copy of Xowa that was working on my PC to another hard drive, and have given it for testing at another location. Will let you know how it goes...

**Comment by gnosygnu** [comment] 2017-01-08 03:00
Cool. I'll probably close this ticket out in a few days. If you have more information, please do comment in this ticket, and I'll reopen and resume investigation.

Thanks!

**Comment by gnosygnu** [comment] 2017-02-05 01:30
I'm going to go ahead and close out this ticket. Let me know if this resurfaces and I'll reinvestigate. Thanks.

**Closed by gnosygnu** 2017-02-05 01:30 UTC
Labels: category, import, needs more information
