### ISSUE TITLE
unsafe multithreading

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#347] opened 2019-01-28 17:04 UTC
I was trying to rebuild enwikisource with num_wkrs=8 in the cfg section of wiki.mass_parse.exec
When I did this, about half way through I would start to get many errors of the form

    invoke failed: Author:Frances_Harper {{#invoke:Author|dates |dates={{{dates|}}} |birthyear={{{birthyear|}}} |deathyear={{{deathyear|}}} |wikidata_id={{{wikidata|}}} }} [err 0] <gplx> @g:/xowa_dev/bin/any/xowa/xtns/Scribunto/engines/Luaj/MWServer.lua:59 vm error: gplx.Err: counts do not match: hash=119846 list=119845
the error is Err: counts do not match (at the right most part of the line)
I have run this rebuild process multiple times and this error always crops up, but inconsistently

If I set num_wkrs=1 then it seems to run to the end OK without the error above

On investigating this I believe that it is related to the fact that enwikisource does a lot of wikidata queries

These queries are cached and I think tha the logic for checking and adding (if neccessary) are not being coordinated between threads correctly.

The current code in Wbase_doc_mgr.java from line 71:

    public Wdata_doc Get_by_exact_id_or_null(byte[] ttl_bry) {// must correct case and ns; EX:"Q2" or "Property:P1"; not "q2" or "P2"
        // load from cache
        Wdata_doc rv = null;
        synchronized (thread_lock) {
            rv = doc_cache.Get_or_null(ttl_bry);
        }
        if (rv == null) {
            // load from db
            rv = Load_wdoc_or_null(ttl_bry); 
            if (rv == null) return null;    // page not found
            Add(ttl_bry, rv);// NOTE: use ttl_bry, not rv.Qid; allows subsequent lookups to skip this redirect cycle
        }
        return rv;
    }
I think should be written as

    public Wdata_doc Get_by_exact_id_or_null(byte[] ttl_bry) {// must correct case and ns; EX:"Q2" or "Property:P1"; not "q2" or "P2"
        // load from cache
        Wdata_doc rv = null;
        synchronized (thread_lock) {
            rv = doc_cache.Get_or_null(ttl_bry);
            if (rv == null) {
                // load from db
                rv = Load_wdoc_or_null(ttl_bry); 
                if (rv == null) return null;    // page not found
                Add(ttl_bry, rv);// NOTE: use ttl_bry, not rv.Qid; allows subsequent lookups to skip this redirect cycle
            }
        }
        return rv;
    }
That is, the add part should also be synchronized

Or I could be totally wrong (nothing new there)

**Comment by gnosygnu** [comment] 2019-01-29 05:19
Nah, most probably you're right. I think I was over-conservative in the scope of the thread_locks.

My only concern is deadlocks, as I remember some issue when trying to handle wikidata. Out of curiosity, if you make the change above, does it avoid the above failure?

**Comment by desb42** [comment] 2019-01-29 06:32
I should have concluded that having made those changes I was able to get a successful run through
Now to work on some of the other errors thrown up

looks like you have a new box of crayons - ahh, thats what you meant about labels and projects!

**Comment by gnosygnu** [comment] 2019-01-30 05:03
> I should have concluded that having made those changes I was able to get a successful run through

Cool. Thanks for the confirm. Committed above.

> Now to work on some of the other errors thrown up

Nice. By the way, nice work on tracking down the cause. It usually takes me an hour or so to find multi-threading errors

> looks like you have a new box of crayons - ahh, thats what you meant about labels and projects!

Yeah, trying a few things out here:
* Give quicker feedback on issues. If I can't comment in depth, I should at least be able to add some basic labels
* Giving better transparency to my thinking. If my priority / effort seems off, feel free to call out
* Keeping track of my estimates. Just want to see if I estimate something as easy and it turns out to be hard. Or vice-versa

And the only downside is a colorful clutter to the issues. In my opinion, it's well worth it. :)

**Closed** 2019-02-01 04:52 UTC
Labels: [effort 5 - minutes], [impact 5 - few lines], [priority 2 - major], [resolved - commit], [schedule 1 - within days]
