### ISSUE TITLE
Another infinite loop?

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#335] opened 2019-01-18 07:23 UTC
I have just tried to build enwiktionary and at the html generation stage it goes into an infinite loop.

The wikitext xowa files have been generated so I could get some pages to showup in the browser
However, some page requests cause things to not complete

In the http_server version
en.wiktionary.org/wiki/Thesaurus:naive produces a page for viewing
en.wiktionary.org/wiki/Thesaurus:naive?action=edit does not finish

running in debug mode, I think I have tracked it down to a lua module.
Inside en.wiktionary.org/wiki/Module:syllables the function export.getVowels

    function export.getVowels(remainder, lang)
      if string.find(remainder, "^[%\[/]?%-") or string.find(remainder, "%-[%\[/]?$") then
        return nil
      end -- If a hyphen is at the beginning or end of the transcription, do not count syllables.
      
      local count = 0
      local diphs = diphthongs[lang:getCode()] or {}
      
      remainder = mw.ustring.toNFD(remainder)
      remainder = string.gsub(remainder, "%((.*)%)", "%1") -- Remove parentheses.
    
      while remainder ~= "" do
        -- Ignore nonsyllabic vowels
        remainder = mw.ustring.gsub(remainder, "^" .. vowel .. nonsyllabicDiacritic, "")
        
        local m =
          mw.ustring.match(remainder, "^." .. syllabicDiacritic) or  -- Syllabic consonant
          mw.ustring.match(remainder, "^" .. vowel .. tie .. vowel)  -- Tie bar
        
        -- Starts with a recognised diphthong?
        for _, diph in ipairs(diphs) do
          if m then
            break
          end
          
          m = m or mw.ustring.match(remainder, "^" .. diph)
        end
        
        -- If we haven't found anything yet, just match on a single vowel
        m = m or mw.ustring.match(remainder, "^" .. vowel)
        
        if m then
          -- Found a vowel, add it
          count = count + 1
          remainder = string.sub(remainder, #m + 1)
        else
          -- Found a non-vowel, skip it
          remainder = string.gsub(remainder, "^" .. UTF8Char, "")
        end
      end

has a loop `while remainder ~= "" do` that should terminate; however I think there may be a Unicode/regex issue
Putting a breakpoint on Procs_exec in Scrib_lib_ustring
The successive breaks cycle through gsub and match calls (and then again and again)
I do not think the matching is happening correctly

**Comment by desb42** [comment] 2019-01-18 07:35
I have also tried this in the gui
I requested Thesaurus:naive and hovered over 'affected'
![loop](https://user-images.githubusercontent.com/861631/51371415-02a0a100-1af2-11e9-85d1-4c63604eb377.jpg)
Note the message in the status bar
Loading page for Module:syllables
and the window message (Not Responding)

**Comment by gnosygnu** [comment] 2019-01-21 02:51
Hey, sorry for the delay, but I was working till very late on Friday, and ended up spending this weekend on something else (to be explained shortly).

Unfortunately, I can't reproduce this either on my dev machine. I also brought down the latest source on github and couldn't reproduce.

![affected](https://user-images.githubusercontent.com/4994104/51449964-a9f12400-1cfc-11e9-9224-d241d51cb57f.png)

I spent some time this weekend automating the XOWA get and make process. Basically, it's a 50 line shell script (really 14 lines after ignoring whitespace and comments) See https://github.com/gnosygnu/xowa/blob/master/xowa_get_and_make.sh .

 I figure it would help for the following:
* Give us a common setup to reproduce bugs
* Allow any other newcomers an easy way to download XOWA and start hacking

When you get a chance, can you try this script and the steps below?
* If this issue no longer occurs, then the issue is probably something in your local repo. Can you zip it up and upload it here?
* If this issue still occurs, then I need to go back to the drawing board and figure out why the same setup still yields different results

Thanks

---

* Ran [xowa_get_and_make_script](https://github.com/gnosygnu/xowa/blob/master/xowa_get_and_make.sh) to pull down latest copy from github and make xowa_dev.jar
* Copied commons.wikimedia.org, www.wikidata.org, de.wikipedia.org, en.wiktionary.org to /xowa_dev/wiki . Note that all versions are 2019-01 versions
* Ran xowa_dev.jar and went to en.d:naive
  * Hovered over affected (as per screenshot above)
  * Switched to edit mode

**Comment by desb42** [comment] 2019-01-21 15:04
trials and tribulations

went to https://www.cygwin.com/ to downloaded https://www.cygwin.com/setup-x86_64.exe
ran the exe and installed everything to g:\cygwin64

went to https://ant.apache.org/bindownload.cgi and downloaded http://apache.mirrors.nublue.co.uk//ant/binaries/apache-ant-1.10.5-bin.zip
expanded this to g:\apache-ant-1.10.5

I have a copy of java 1.8 installed on my c: drive; however I cannot remember if spaces in directory paths still cause an issue
So I copied the whole of the java jdk to g:\Java\jdk1.8.0_181

I created the directory g:\xowa_dev and placed a copy of xowa_get_and_make.sh in it
I set the following environment variables

    JAVA_JDK_VERSION=1.8
    PLAT_NAME=windows_64
    ROOT_DIR=g:/xowa_dev
    ANT_BINARY=/cygdrive/g/apache-ant-1.10.5/bin/ant
    JAVA_JDK_DIR=/cygdrive/g/Java/jdk1.8.0_181

Then I tried to run the script

First issue - no wget
I happen to have a version of wget from the gnuwin32 sourceforge.net package
So I changed the path to find wget (this also needed an extra switch as well)

    /cygdrive/c/gnuwin32/bin/wget --no-check-certificate https://api.github.com/repos/gnosygnu/xowa/tarball/master

Once the download of approx 110Mb completed the expanding and reoganising occured smoothly

Second issue - Ant complains of no JAVA_HOME setup
I resolved this by adding

    export JAVA_HOME=/cygdrive/g/Java/jdk1.8.0_181
just after the JAVA_JDK_DIR line

Everything built after that

When I startup the jar file with `g:\Java\jdk1.8.0_181\bin\java -jar g:\xowa_dev\xowa_dev.jar`
In the console I get

    SplashScreen.getSplashScreen() returned null
    1548078448351   addons.manager  ERROR   startup failed: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIPrefBranch.setCharPref]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/AddonManager.jsm :: AMI_startup :: line 645"  data: no] Stack trace: AMI_startup()@resource://gre/modules/AddonManager.jsm:645 < AMP_startup()@resource://gre/modules/AddonManager.jsm:2318 < AMC_observe()@resource://gre/components/addonManager.js:55 < <file:unknown>

**Comment by desb42** [comment] 2019-01-21 15:14
Having followed all the steps above, this version does not produce the error as outlined

So, my bad
However I have done further research to see where/why the problem arose

I have tied it down to a different version of luaj_xowa.jar

So this issue could be closed

**Comment by gnosygnu** [comment] 2019-01-22 08:34
> trials and tribulations

Ugh. Sorry.

> went to https://www.cygwin.com/ to downloaded https://www.cygwin.com/setup-x86_64.exe
> ran the exe and installed everything to g:\cygwin64

Yeah, I required cygwin for bash regularity. I could make this a cmd script, but curl / wget is always an issue on Windows (outside of Powershell)

> I have a copy of java 1.8 installed on my c: drive; however I cannot remember if spaces in directory paths still cause an issue
> So I copied the whole of the java jdk to g:\Java\jdk1.8.0_181

Unfortunately, that's the easiest way. I think the alternative is to use the shortened form such as mentioned [in this post here](https://stackoverflow.com/questions/14567191/export-java-home-with-spaces-in-cygwin). For example, ```/cygdrive/c/PROGR~1/Java/jdk1.8.0_181```

> First issue - no wget

My mistake. I thought wget was standard. I changed this to use curl, which I believe comes by default on cygwin (as well as macosx). 

> Second issue - Ant complains of no JAVA_HOME setup

Another mistake. I changed JAVA_JDK_DIR to JAVA_HOME (I didn't realize I wasn't using it for the rest of the script)

> SplashScreen.getSplashScreen() returned null
> 1548078448351   addons.manager  ERROR   startup failed: [Exception... "Component returned failure  code: 0x80070057

Yeah, I should have mentioned that I get the same console.out on my side. XULRunner is unfortunately deprecated tech, so it spits out weird error messages. Fortunately, XOWA still runs. :)

> I have tied it down to a different version of luaj_xowa.jar
> So this issue could be closed

Cool, thanks for the follow-up. Will close the issue. It's a bit late on my side, and I had a crummy day at work, so I'll post on your other comments later. Thanks.

**Closed by gnosygnu** 2019-01-22 08:34 UTC
Labels: scribunto
