### ISSUE TITLE
user limitation in http server mode

### ISSUE THREAD

**Issue by yonisolo** [gnosygnu/xowa#23] opened 2015-09-18 07:36 UTC
Hi, my apologies for my post on source forge....
So my problem is to limit the number of user accessing to xowa http web server, is there a parameter along with --http_server, for example --max_user=15 ?
Best regards

**Comment by gnosygnu** [comment] 2015-09-18 11:41
[reposting from sourceforge: https://sourceforge.net/p/xowa/discussion/general/thread/304f86e5/]

Hi! Thanks for the praise!

There's currently no option to limit the number of concurrent users. I think this should be rather straightforward. I'll take a look at it this weekend and try to add it for v2.9.3. I'll track progress here.

Thanks!

**Comment by yonisolo** [comment] 2015-09-18 12:00
Thank you for your quick answer, that would be great

**Comment by gnosygnu** [comment] 2015-09-21 04:10
Hi! v2.9.3 has 2 new command-line arguments

* --http_server.max_clients: maximum number of concurrent clients (connections) allowed
* --http_server.max_clients_timeout: time to wait for new connections before trying again

I tested this locally on my side by running  the following:

~~~
java -jar /xowa/xowa_linux.jar --app_mode http_server --http_server.max_clients 5 --http_server.max_clients_timeout 250
~~~~

Let me know how it goes for you. If there are no problems, I'll close this issue out at the end of the week.

Thanks!

**Comment by yonisolo** [comment] 2015-09-21 07:03
This is more than expected :), you can close this issue, thank you again

**Comment by gnosygnu** [comment] 2015-09-21 12:45
Cool! Thanks for the quick response. Let me know if there is anything else!

**Comment by gnosygnu** [comment] 2015-09-23 04:11
I noticed a minor bug. Occasionally the command window will output a ClassCast exception. This is due to the unique ids not being released correctly. It causes the unique ids to continue climbing and will overflow at Int.MaxValue (2^32). 

I fixed this for v2.9.4. I'll close this issue again after the release. Thanks.

**Comment by yonisolo** [comment] 2015-09-23 06:54
No problem, I saw that yesterday and i was about to open a new issue for this. Thanks

**Comment by gnosygnu** [comment] 2015-09-28 03:57
v2.9.4 fixes this issue. I added a test to detect this issue. I also confirmed by setting max clients to 5 and loading en.w:Earth multiple times. The error no longer shows.

**Closed by gnosygnu** 2015-09-28 03:57 UTC
Labels: http server

**Comment by yonisolo** [comment] 2015-09-28 07:28
Thank you for your support, I can confirm that this error is fixed. :)

**Comment by gnosygnu** [comment] 2015-09-28 11:35
No problem! Thanks for the follow-up!
