### ISSUE TITLE
(3.10.4.1) Importation of English Wikipedia is stuck at creating "db index (please wait); db=xowa.temp.category idx=tmp_cat_link__cl_to_ttl"

### ISSUE THREAD

**Issue by khanhhung2512** [gnosygnu/xowa#98] opened 2016-11-11 02:14 UTC
I have xowa 3.10.4.1 and 3 files enwiki-20161101-categorylinks.sql.gz, enwiki-20161101-page_props.sql.gz, and enwiki-20161101-pages-articles.xml.bz2 in xowa\wiki\en.wikipedia.org

I ran the importation with "web access" disabled (because otherwise xowa would try to download the categorylinks and page_props files even though they were already inside xowa\wiki\en.wikipedia.org

The process was stuck in both my desktop (windows 7 64-bit with 8GB RAM) and laptop (windows 10 64-bit with 4GB RAM) at "db index (please wait); db=xowa.temp.category idx=tmp_cat_link__cl_to_ttl". It was stuck there for hours in my desktop and more than a day already in my laptop.

At first, I thought I needed to rename the dump files from 20161101 to latest. However, I tried with Simple English and Vietnamese Wikipedia and they worked whether it's 20161101 or latest.

So, what should I do?

**Comment by gnosygnu** [comment] 2016-11-11 06:28
Hi! Thanks for the detailed issue.

There is a known issue with Windows XP (32-bit). However, as you noted, your system is Windows 7 64-bit.

Two questions off the top of my head:
* **SSD hard drives**: Do either of your machines have SSD hard drives? These typically are much faster, especially for SQLite. They're not required, but I'm curious if you do have them and the performance is that slow 
* **Disk space**: Do you have at least 20 GB of free space when you reach the category stage? It's possible that the index is failing because of disk space usage and the error isn't thrown.

Just so you know, I run the full English Wikipedia build on a Linux 64-bit machine with a command-line script (similar to http://xowa.org/home/wiki/Dev/Command-line/Dumps) . There's nothing special about the machine, though it does have an SSD and 16 GB RAM (also an i5 processor) I ran it for 2016-11 earlier this week and didn't have a problem.

With that said, let me run the English Wikipedia update on my Windows 7 64-bit box with the Import/Offline page. I'll report again sometime later tomorrow.

> I ran the importation with "web access" disabled (because otherwise xowa would try to download the categorylinks and page_props files even though they were already inside xowa\wiki\en.wikipedia.org

This is probably a bug from the recent changes to the Category system. I'll try to remove the redundant download in the next release. Thanks for reporting it!

**Comment by khanhhung2512** [comment] 2016-11-11 07:11
I don't have SSD hard drives but the disk space was more than enough in both my laptop and desktop. Btw, the link in your comment mentions commons.wikimedia.org and www.wikidata.org. They aren't mentioned in the offline import instructions, so do I absolutely need those two?

**Comment by khanhhung2512** [comment] 2016-11-11 08:45
Btw, in http://xowa.org/home/wiki/Dev/Command-line/Dumps, I also see 'image', 'pagelinks', and 'imagelinks' (in addition to 'pages-articles', 'categorylinks', and 'page_props'). Do I need to download those dumps as well?

PS: I corrected myself that my laptop is actually Windows 10 64-bit. Only my desktop is Windows 7 64-bit.

**Comment by gnosygnu** [comment] 2016-11-11 14:59
> I don't have SSD hard drives but the disk space was more than enough in both my laptop and desktop. 

Cool. Thanks for clarifying. As long as you have enough disk space, it should be fine. (SSDs are not required) My Windows 7 64-bit has an SSD and a regular HDD. I'm running the import now on the HDD but it'll take a few hours before completing.

> Btw, the link in your comment mentions commons.wikimedia.org and www.wikidata.org. They aren't mentioned in the offline import instructions, so do I absolutely need those two?

Nope. I guess I'm saying I usually do my imports using the command-line script whereas you're using the Import/Offline page. It's possible that Import/Offline could be broken, though it is unlikely (the error is on a SQLite level).

Specifically, commons and wikidata are not needed at all in the import process. They are needed for generating HTML dumps which is the reason why they are in my script.

> Btw, in http://xowa.org/home/wiki/Dev/Command-line/Dumps, I also see 'image', 'pagelinks', and 'imagelinks' (in addition to 'pages-articles', 'categorylinks', and 'page_props'). Do I need to download those dumps as well?

Hmm, mostly the same as above. 'image' and 'imagelinks' are only needed to generate HTML dumps. I'll update the script later to clarify the difference. 

'pagelinks' is required for the search component. If you don't have it, the wiki isn't technically complete (you won't get the auto-dropdown when searching for articles). However, this won't stop the wiki from importing (as you saw with Simple and Vietnamese Wikipedia)

At any rate, I'll post again in a few hours when the import is done on my side.

Thanks!

**Comment by khanhhung2512** [comment] 2016-11-11 16:37
> 'pagelinks' is required for the search component. If you don't have it, the wiki isn't technically complete (you won't get the auto-dropdown when searching for articles). However, this won't stop the wiki from importing (as you saw with Simple and Vietnamese 

I just tried a test with Simple English. When I put the 'wiki-_date_-pagelinks.sql.gz' file inside the import folder, the file was deleted after importation, so I guess it was used at some point but I just don't know when. However, whether I have the 'pagelinks' file or not, the auto-dropdown is still functional inside the "wiki search box" and not functional in the "Search using Special:AllPages" box (next to the Address box). So, basically, I don't see any difference between having and not having the 'pagelinks' file.

**Comment by gnosygnu** [comment] 2016-11-11 17:49
Thanks for the follow-up. The pagelinks is necessary for this dropdown:

![xowa__url_search](https://cloud.githubusercontent.com/assets/4994104/20224533/dac3dbc0-a80c-11e6-995e-17a84d8cd77c.png)

This dropdown works because it falls back on older code. The results are probably different:

![xowa__html_search](https://cloud.githubusercontent.com/assets/4994104/20224557/ff2a78d4-a80c-11e6-811e-382be9d5e052.png)

The Special:AllPages one doesn't have a drop down. I may end up removing that in a far-future release.

> In another issue, are there any ways to perform a full-text search like in the actually wikipedia? I still have to rely on Kiwix for this function.

No, unfortunately, I haven't had time to add this. Of any missing feature in XOWA, would you feel that full-text search is the most important? Just trying to gauge priority....

**Comment by gnosygnu** [comment] 2016-11-11 18:59
The import finished now. Unfortunately (?) it worked. I pasted the log here: https://gist.github.com/anonymous/9214c9c5743b7234a18191ac73aac991

I'm not sure why it would fail on your machine. I'm planning to change some parts of the Import/Offline page, so maybe I can break it up into two separate steps: (1) for the main wiki; (2) for the category (where your import is failing). I don't know if that will help on you machine, but it'll allow you to move forward.

Finally, if you get a chance, can you rerun it on your desktop? Once it freezes for more than one hour, grab the log and paste it here. The log would be at <code>home/wiki/Special:XowaSystemData?type=log_session</code>

Let me know if you have any other thoughts. Thanks!

**Comment by khanhhung2512** [comment] 2016-11-11 19:30
[session.txt](https://github.com/gnosygnu/xowa/files/586590/session.txt)
The import is actually still running on my desktop, and I'm testing with your 3.10.4.7 today and it's still stuck at "db index (please wait); db=xowa.temp.category idx=tmp_cat_link__cl_to_ttl".

Btw, the auto-dropdown in the address bar still works without the 'pagelinks' file (tested in Simple English).

And, yes, the full-text search is one of the most important function (along with page sync) because when you're offline, Offline Wikipedia with full-text search can serve as replacement of the internet.

Example in Vietnamese Wikipedia: Search for WXGA in:
+ Online Wikipedia: https://vi.wikipedia.org/w/index.php?search=wxga&title=%C4%90%E1%BA%B7c_bi%E1%BB%87t:T%C3%ACm_ki%E1%BA%BFm&go=Xem&searchToken=41dwamo9nb6i31q0v0wauavgd
+ Xowa Wikipedia: No result.

Without full-text search, the use of Offline Wikipedia is rather limited.

**Comment by khanhhung2512** [comment] 2016-11-12 00:31
Here's a better log:
[err.txt](https://github.com/gnosygnu/xowa/files/586966/err.txt)
[internet.txt](https://github.com/gnosygnu/xowa/files/586967/internet.txt)
[session.txt](https://github.com/gnosygnu/xowa/files/586968/session.txt)

**Comment by gnosygnu** [comment] 2016-11-12 04:57
> Here's a better log:

Thanks. I went through it and it looks like the main wiki should be complete. Have you tried opening the "incomplete" English Wikipedia? It should still function like normal, except you won't get Category pages.

I don't know why the category import is failing. I generated another build to output some more log information. When you get a chance, please try the following (it should take about 20 min):
* Download the latest from my google drive: https://drive.google.com/open?id=0B9cb52zjL2rIdERYejdzb243ZW8
* Make sure the page_props and categorylinks files are in <code>E:\Portable Programs\xowa\wiki\en.wikipedia.org</code>
* Launch XOWA and go to <code>home/wiki/Dashboard/Import/Offline</code>
* Paste the following into the edit box: <code>app.setup.cmds.dump_add_many( 'en.wikipedia.org', 'latest', '', 'wiki.category2.build');</code>
* Press <code>Run script</code>
* Wait for about 5 minutes
* Go to <code>home/wiki/Special:XowaSystemData?type=log_session</code>. You should see lines like: <code>20161112_044114.623 inserting cat_link row: 1,000</code>.
    * If you don't see them, wait no more than 30 minutes and refresh the page.
    * Once you get a few lines, upload your session.txt.
    * If you don't get any lines, let me know how long you waited and I'll go back to the drawing board.

Basically I'm trying to figure out how long it takes to process 1,000 rows on your machine. On my machine, I process 300,000 per second. (there are 100 million category rows on English Wikipedia). This should be primarily a function of hard drive speed, but even when I'm on a 7200 RPM HDD, my output is still "fast".

> Btw, the auto-dropdown in the address bar still works without the 'pagelinks' file (tested in Simple English).

Thanks. I mis-remembered earlier. The pagelinks dump is only used to assign sorting to the search rankings. So you will have a dropdown in both images, but the sorting will be based on page length. If you had the pagelinks dump, you get a more sophisticated sorting based on https://en.wikipedia.org/wiki/PageRank.

However, that sophisticated sorting comes at a price, as it takes another few hours to build. So, for now, skip the pagelinks.sql until we get to the bottom of the category import issue.

> And, yes, the full-text search is one of the most important function (along with page sync) because when you're offline, Offline Wikipedia with full-text search can serve as replacement of the internet.

Ok. Thanks for the feedback. Let me look at integrating an existing full-text search engine like Lucene. I've held off on this because I don't think Lucene works well on Android, and I really didn't want to write my own from scratch. But I know this is an important feature, and I'll take a look and see what's involved.

**Comment by khanhhung2512** [comment] 2016-11-12 05:08
> Make sure the page_props and categorylinks files are in E:\Portable Programs\xowa\wiki\en.wikipedia.org

You mean the .sql.gz files or the extracted .sql files?

**Comment by gnosygnu** [comment] 2016-11-12 05:10
Either the .sql.gz or the .sql work. XOWA will use the .sql if it's there, or auto-extract it from the .sql.gz . 

Hope that helps.

**Comment by khanhhung2512** [comment] 2016-11-12 05:23
I haven't seen the line yet. Btw, my files are 20161101, not latest. Besides, I have never seen the .sql.gz extracted by xowa, only the bz2 file to xml.

**Comment by gnosygnu** [comment] 2016-11-12 05:27
> Btw, my files are 20161101, not latest. 

Ok. Shouldn't make a difference.

> Besides, I have never seen the .sql.gz extracted by xowa, only the bz2 file to xml.

Hmm, that's strange.  You can try with a smaller wiki like Simple Wikipedia

If you want to do IRC, I'll still be up for another 15 min or so. Just hop on  at http://webchat.freenode.net/?channels=#xowa

Thanks

**Comment by khanhhung2512** [comment] 2016-11-12 09:26
The counting didn't even start with English Wikipedia.
[session_en.txt](https://github.com/gnosygnu/xowa/files/587141/session_en.txt)

Later, I ran the test with Simple English. The count started and I believe it was fast enough.
[session_simple.txt](https://github.com/gnosygnu/xowa/files/587142/session_simple.txt)

**Comment by gnosygnu** [comment] 2016-11-12 17:53
Thanks. I looked at the log files and am still puzzled.

One thing that is particularly strange is that at the bottom of the file your en.w starts from db 2: <code>en.wikipedia.org-xtn.category.link-db.002</code>. Your previous atttempt (and in general, all attempts) should start from db 1: <code>en.wikipedia.org-xtn.category.link-db.001</code>

Let me look at it on my side and some more debugging code. Once that's done, I may ask you to delete some category files and try again.

Thanks.

**Comment by gnosygnu** [comment] 2016-11-14 06:36
As per our IRC tonight, here's a possible wild guess:

* Download the latest SQLite JDBC jar: https://drive.google.com/open?id=0B9cb52zjL2rIWXhveDQzSi1Tdjg
* Copy it to C:\xowa\bin\any\java\jdbc\sqlite\sqlite-jdbc-3.8.11.2.jar
* Start XOWA
* Go to home/wiki/Dashboard/Import/Offline
* Enter in app.setup.cmds.dump_add_many( 'en.wikipedia.org', 'latest', '', 'wiki.category2.build');
* Make sure your category dump files are in place
* Run it again
* See if it freezes

**Comment by khanhhung2512** [comment] 2016-11-14 12:52
Since I deleted English Wikipedia on my desktop, I have imported it instead of just rebuilding the category like you suggested. (And yeah, I used the new sqlite in your link above.) It froze again. I waited 52 min. from the last change (which is "db.schema.load.bgn: conn=data source=E:\xowa\wiki\en.wikipedia.org\en.wikipedia.org-xtn.category.link-db.001.xowa;version=3;") but "inserting cat_link row:" hadn't started yet (Yeah, I know you add it in this new release from the Simple English import log).

The log is as always, so I don't upload it. Instead, I think this picture which was taken when the program froze might prove helpful.
![stuck 1](https://cloud.githubusercontent.com/assets/23390760/20265337/19a49724-aaa3-11e6-8cc9-e4105b8162ef.jpg)
If I understand it correctly, in "db.schema.load.bgn: conn=data source=E:\xowa\wiki\en.wikipedia.org\en.wikipedia.org-xtn.category.core.xowa;version=3;" data will be copied into en.wikipedia.org-xtn.category.core.xowa, but the file is almost empty. Same goes for en.wikipedia.org-xtn.category.link-db.001.xowa.

**Comment by gnosygnu** [comment] 2016-11-15 20:16
> If I understand it correctly, in "db.schema.load.bgn: conn=data source=E:\xowa\wiki\en.wikipedia.org\en.wikipedia.org-xtn.category.core.xowa;version=3;" data will be copied into en.wikipedia.org-xtn.category.core.xowa, but the file is almost empty. Same goes for en.wikipedia.org-xtn.category.link-db.001.xowa.

Yup, your understanding is correct. Both files should be filled with data. Instead they are essentially empty.

I don't really know what else to try at the moment. I'll hunt up some spare Windows 7 and Windows 10 boxes around here, and see if I can replicate the issue. Will keep you posted. As always, thanks for the excellent reporting.

**Comment by khanhhung2512** [comment] 2016-11-25 00:35
> Yup, your understanding is correct. Both files should be filled with data. Instead they are essentially empty.

I wonder if you've figured out what happened.

**Comment by gnosygnu** [comment] 2016-11-25 03:33
Sorry. I've been busy with other things here and I really only have one spare Windows 7 box lying around.

I'll give it a try tomorrow with the Windows 7 box. I still have a Windows XP box, and I'll see if I can reproduce it there.

Thanks.

**Comment by gnosygnu** [comment] 2016-11-26 05:19
I was able to reproduce it on my Windows 7 box. After some investigation, I realized I needed to add another SQL index. Without it, it still runs fine on an SSD, but it takes forever on a HDD.

I uploaded a new version here. https://drive.google.com/open?id=0B9cb52zjL2rIclRNUlp2N3pqcDg

It still takes a long time to do the category rebuild (probably 10 hours), but you'll see the files start growing after about an hour. Of course, if it still doesn't work, please post your log here, and I'll resume investigating 

Thanks

**Comment by gnosygnu** [comment] 2016-11-27 22:40
I made a new version that now handles English Wikipedia Categories on my Windows 7 box. Please download it from here: https://drive.google.com/open?id=0B9cb52zjL2rIY1ppR3MwbjdoWXc

It takes about 2 hours just to do categories (ignore the earlier 10 hours projection). It's still a long time, so you may want to run it overnight.

As before, if it fails, please post your log here, and I'll investigate again.

Thanks.

**Comment by gnosygnu** [comment] 2016-12-05 02:25
@XowaWilliam was kind enough to confirm that this fix worked on his machine (see #108) . This fix is included in tonight's [v3.12.1.1](https://github.com/gnosygnu/xowa/releases) release. 

I'm marking this issue resolved and closing it for now. Let me know if it still doesn't work, and I'll reinvestigate

Thanks again for reporting the issue and trying all the multiple imports.

**Closed by gnosygnu** 2016-12-05 02:25 UTC
Labels: category, import
