### ISSUE TITLE
Section editing and scroll bar position

### ISSUE THREAD

**Issue by AlexanderMisel** [gnosygnu/xowa#106] opened 2016-11-25 14:48 UTC
It would be more convenient if section editing is allowed for long article editing. And it will be better if after I clicked the Preview button, the postion of the scroll bar position is still at the position where I was just editing.

**Comment by gnosygnu** [comment] 2016-11-26 01:55
Thanks for the well-worded issue.

I think section editing would involve:
* Adding new section "edit" links of the form https://en.wikipedia.org/w/index.php?title=Earth&action=edit&section=1
* Having XOWA handle this url to only show the specified section (and not the entire article)
* Having "Save" splice in the edited section into the rest of the article.

None of these are difficult, but all combined it would be a few hours of time. Do you think you'd use this feature a lot? If so, I can bump the priority up. Otherwise, I'd like to leave it for sometime in the future as I'd like to either start working on page-sync (for new pages) or full-text search

Regarding scroll bar position, wouldn't that request be unnecessary if section editing was enabled? Otherwise, I think you're asking for something like this:
* You visit en.w:Earth
* You scroll down to the middle of the page
* You click edit for the entire article (not the section)
* You scroll down to the middle of the page where you want to make the edit
* You make the edit and press Preview
* You expect XOWA to Preview the entire page, but scroll the middle of the page into view (where the edit was made)

If so, I think this would be difficult for a few reasons (detecting where the edit was in the page; "scrolling" to the middle of the page). Also, this behavior would be different than Wikipedia (in either Firefox / Chrome)

Let me know if I'm misunderstanding anything. Thanks.

**Comment by AlexanderMisel** [comment] 2016-11-26 03:50
* It would be so kind if you add section editing as soon as possible. I often want to use this feature but there is not.
* The scroll bar of the editor don't have to be at the position where I just edited, it can just remain the position where it is before I previewed, i.e. store the previous position and automatically scroll to that position after loading the preview.

**Comment by gnosygnu** [comment] 2016-11-27 03:43
Thanks for the feedback. I took a look at this today, and the section editing would be difficult. The hard part would be doing section editing for templates. More detail is below if you're interested. I'll look at it later next week, but it may be too difficult without changing the underlying parser

As for the scroll bar, that may be possible, but I'll probably delay further investigation until next week also. I'll post again here when I have more info.

Thanks.

----

Here's a specific example illustrating "section editing" for templates:
* <code>Page_1</code> transcludes <code>Template:A</code>
* <code>Template:A</code> has a Header: <code>==Heading 1==</code>
* When <code>Page_1</code> is viewed it will show <code>Heading 1</code> with a link of  <code>https://en.wikipedia.org/w/index.php?title=Template:A&action=edit&section=T-1</code>. Note that the edit link is to <code>Template:A</code> not <code>Page_1</code>
* When XOWA shows the page, it doesn't know that <code>==Heading 1==</code> is from <code>Template:A</code>. This information is omitted because XOWA rolls up all the nested templates into one giant page. Offhand, I don't know a way to preserve this information about <code>==Heading 1==</code> all the way to the <code>Page 1</code> level

**Comment by AlexanderMisel** [comment] 2016-11-27 08:32
My friend made a test [here](https://zh.wikipedia.org/w/index.php?title=Wikipedia:%E6%B2%99%E7%9B%92&oldid=42283264), getting the transclusion-expanded text of My userpage (which transcludes User:Alexander_Misel/sign), and we found that at section headers like
```MediaWiki
== 访客登记 ==
```
MediaWiki generates something like
```MediaWiki
=='"`UNIQ--h-0--QINU`"' 访客登记 ==
```
And I think it's a unique id for sections which will help the identification of sections.

**Comment by gnosygnu** [comment] 2016-11-27 22:42
Hi, thanks for the information.

The problem is that XOWA's parser works differently than MediaWiki's parser. It doesn't include the <code>UNIQ</code> tokens which MediaWiki does.

I'll take a look at it later this week, but I really can't promise anything. Thanks.

**Comment by gnosygnu** [comment] 2016-12-05 02:30
I've been working on section-editing thru the week. I may be able to have something for next week's release. I'll post again here with an updated status later

**Comment by gnosygnu** [comment] 2016-12-09 00:30
I uploaded a preview build with basic section-editing. Here's how to try it:
* Download the Windows 64-bit from my google drive: https://drive.google.com/open?id=0B9cb52zjL2rIT1lFcWpyb3k1RVE
* Unzip it to wherever you have XOWA installed.
* Go to home/wiki/Special:XowaCfg?grp=xowa.edit
* Check the "Enabled" box for section-editing. Note that the change is immediate (there is no save button).
* Reload home/wiki/Main_Page and try it out

Keep in mind there are some limitations:

### Transcluded headers are not supported.
I've discussed this above, and it turns out to be quite difficult

* If you click an edit link for a transcluded header, then you'll get an error message. You can check home/wiki/Wikipedia:Sandbox and click on the Edit link for "A" as an example
* If you need to edit a header on a transcluded page, then you'll have to manually open the transcluded page and edit the entire source. I'm hoping that these are fairly uncommon (like 1%). If the frequency is higher, let me know (specific pages would be helpful), and I'll revisit. However, keep in mind it does require a lot of time, and even getting this far was more hours than I expected.

### The url is a different format than MediaWiki
* MediaWiki uses a number for section id. For example, <code>/wiki/Page?section=1</code>
* XOWA uses a string for section id. For example, <code>/wiki/Page?section_key=Header_1</code>

I tried to do the numerical approach, but I ran into issues due to transcluded headers. The string approach is non-standard, but it should work for now.

Let me know if there are any issues.

Thanks.

**Comment by AlexanderMisel** [comment] 2016-12-09 06:28
I think there's reason that MediaWiki uses a number as section id. Let's first see the test I've done.
```MediaWiki
==tests==
012
==test==
==tests==
123
===<math>\delta</math> function===
345
===<span style="color:green">Green header<span>===
567
==={{lang|ja|日本語テスト}}===
678
```
Problems are listed as follows:
* The edit link on the h2 header (tests) should get all content under the header until reaches a header whose level is h1 or h2. But the version gives only `==tests==123`.
* Header with `<math>` tags failed to extract the section.
* Header with style settings such as color of the font.
* Also when using a language template.
* MediaWiki allows us to have sections in the same name, but your code does not support that.
That's all I found in this preview build.

**Comment by gnosygnu** [comment] 2016-12-09 19:00
Thanks for the quick feedback and the excellent counterpoints.

In short, I made another build to address the problems above. Please try the latest version from https://drive.google.com/open?id=0B9cb52zjL2rIaFI1QzUzVWltLXM .

Also, you can test using the diagnostics page at home/wiki/Diagnostics/Section_edit. I reference it below.

I comment in more length below. Let me know if there's anything else.

Thanks.

----
> I think there's reason that MediaWiki uses a number as section id

I agree. Although I think a string is better for clarity's sake, it has a number of issues.

In particular, I noticed that headers with non-ASCII characters create verbose url-encoded urls . See the UTF-8 section.

For now, I'm still going to stick with the strings until I hit something unresolvable. I really think that switching to numbers forces me to figure out transcluded headers which in turn will require a significant parser overhaul.

> The edit link on the h2 header (tests) should get all content under the header until reaches a header whose level is h1 or h2. But the version gives only ==tests==123.

Agreed. I had this working in an early implementation, but forgot about it when I rewrote the approach to be string-based. It is working now (see "Covering" in the diag page)

> Header with <math> tags failed to extract the section.

Good point. This should be fixed now as shown by "Math".

> Header with style settings such as color of the font.

Actually, I wasn't even handling HTML before. I am now.

Your example was an extra layer of complication b/c it was malformed HTML which MediaWiki corrects (<code>&lt;span>some text&lt;span></code>: notice no <code>&lt;/span></code>). This too should be fixed.

> Also when using a language template.

This is just templates in general. XOWA has the same problem with templates in the header (== {{some_template}} ==) as it does with headers in transcluded pages.

With that said, I put in a workaround for this, though it is ugly. It does work for a simple example like that shown in "Template".

If it doesn't work on another Template, let me know which page and template, and I'll triage it on my side.

> MediaWiki allows us to have sections in the same name, but your code does not support that.

Good catch. I changed the code to use the same approach as the Table of Contents (which appends a number to duplicate headers; "a" -> "a_2")

> That's all I found in this preview build.

Yeah, that's more than I wished was there. Hopefully this build is better for you.

**Comment by AlexanderMisel** [comment] 2016-12-11 12:09
Thanks for this build. All above problems disappeared. By the way, is it possible to add an [edit] link for the lead section of a page? It is a gadget on Wikipedia.

**Comment by gnosygnu** [comment] 2016-12-11 16:05
Cool! Thanks for the feedback, and glad to hear it looks good so far

> By the way, is it possible to add an [edit] link for the lead section of a page? It is a gadget on Wikipedia.

I took a look at the Gadget (which I think is https://en.wikipedia.org/wiki/MediaWiki:Gadget-edittop.js). It's pretty small, but it hooks into the <code>mw</code> object which XOWA does not support. I'd like to support Gadgets natively in the future, but right now, it's not doable

Let me look at hard-coding the edittop.js directly into XOWA, which should be doable. I'll have a firm yes or no later this week.

Thanks.

**Comment by gnosygnu** [comment] 2016-12-12 01:12
Hi. So, technically, it is later in the week, and I do have a firm answer. Yes. :)

Please try the following:
* Download the latest version: https://drive.google.com/open?id=0B9cb52zjL2rISG56VWtoT1hmaEU
* Test with home/wiki/Diagnostics/Section_edit as well as any other page. Note that I have automated tests for the earlier cases (UTF8; malformed HTML; Math, etc.) so you don't need to test these.

Finally, I took a quick look at the scroll bar position. I noticed that I had a line of code which always scrolled the view to the top of the page after preview.

I commented out that line in the build above. Let me know if that works for you. If it does, I'll make an option for it in the next build. 

Let me know if there's anything else.

Thanks.

**Comment by gnosygnu** [comment] 2017-01-04 02:59
The section-editing feature was officially released in tonight's release. Let me know if you still want the scrollbar position change as I described above. Otherwise, I'm marking this issue closed for now.

Thanks.

**Closed by gnosygnu** 2017-01-04 02:59 UTC
Labels: editing, enhancement, gui
