### ISSUE TITLE
not respecting paragraph break

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#326] opened 2019-01-12 07:55 UTC
I am trying a german wiki to test out some of the spelling/word order differences and came across this page. de.wikipedia.org/wiki/Geographie - comparing xowa and dewiki
![german1](https://user-images.githubusercontent.com/861631/51044202-6ee24880-15b8-11e9-8d0c-85e2c3eb6d12.gif)
Note that there is a paragraph break in dewiki
The wikitext associated with this is 

    Die '''Geographie''' (oder '''Geografie''', {{grcS|γεωγραφία|geographía}}, zusammengesetzt aus γῆ ''gē'' ‚Erde‘ und γράφειν ''gráphein'' ‚(be-)schreiben‘) oder '''Erdkunde''' ist die sich mit der [[Erdoberfläche]] befassende [[Wissenschaft]], sowohl in ihrer physischen Beschaffenheit wie auch als Raum und Ort des menschlichen Lebens und Handelns.<ref>Diercke: ''Wörterbuch der Allgemeinen Geographie.''</ref><ref>{{Literatur|Autor=[[Hans Heinrich Blotevogel]]|Titel=Geographie|Herausgeber=E. Brunotte u.&nbsp;a.|Sammelwerk=Lexikon der Geographie|Verlag=Spektrum|Ort=Heidelberg|Jahr=2002|ISBN=3-8274-0416-9|Seiten=15}}</ref> Sie bewegt sich dabei an der Schnittstelle zwischen den [[Naturwissenschaft]]en, [[Geisteswissenschaften|Geistes-]] und [[Sozialwissenschaft]]en.
    
    Gegenstand der Geographie ist die Erfassung, Beschreibung und Erklärung der Strukturen, Prozesse und Wechselwirkungen in der [[Geosphäre]]. Die physikalische, chemische und biologische Erforschung ihrer Einzelerscheinungen ist jedoch Gegenstand anderer [[Geowissenschaften]].

Note that `Gegenstand` should start a new paragraph

I can get the paragraph behaviour if I remove the `grcS` template - but I do not know why

**Comment by gnosygnu** [comment] 2019-01-14 04:20
Hey, thanks for gif and source excerpt. The above issue is possible, as templates can cause weird issues for whitespaces. 

That said, I tried to reproduce now, and the line break is there. See screenshot below. My wiki version is 2019-01 and the page modified date is ```8 November 2018 um 09:56 Uhr geändert.```. I also tried the wikitext sample above as well as HTTP Server

Can you try reloading the page again and seeing if anything is in the Help -> System Data -> Session Log ?

![dewiki](https://user-images.githubusercontent.com/4994104/51096289-5a08df00-1789-11e9-9867-6cbe7e6a0af2.png)

**Comment by desb42** [comment] 2019-01-15 08:03
I too am using 2019-01 with the same timestamp
My investigations indicate that the template `grcS`  is definitely involved
{{grcS|γεωγραφία|geographía}} internaly expands to

    <span style="font-style:normal;font-weight:normal">[[Altgriechische Sprache|altgriechisch]]</span> <span lang="grc-Grek" class="Grek" style="font-style:normal">γεωγραφία</span> <templatestyles src="Latn/styles.css"></templatestyles><span class="Latn" lang="grc-Latn" style="font-weight:normal;font-style:italic">geographía</span>

And it is the processing of `templatestyles` that is causing the problem
In my version of the code Template_styles_nde.java
L34 is

    ctx.Para().Process_block__xnde(xnde.Tag(), Xop_xnde_tag.Block_bgn);
If I comment this out then things display properly
I am not sure what that line is there to do
(And I may be barking up the wrong tree)

**Comment by gnosygnu** [comment] 2019-01-15 11:40
> If I comment this out then things display properly
> I am not sure what that line is there to do

That's interesting. The line is actually there to force the new line for paragraphs.

That said, that same line is a bit of cargo-cult code that I carry around and just apply to all xml nodes.  I tried removing it and there is no difference. (it only applies to certain cases though) 

Let me look at it more later and figure out how to reproduce it.

Thanks.

**Comment by desb42** [comment] 2019-01-21 15:48
Following the notes in #335, I have built a version of xowa_dev.jar from the latest git sources
This issue continues to be reproducible in this latest version

**Comment by gnosygnu** [comment] 2020-03-25 10:46
Hey, again, sorry for the late reply (1 year plus in this case :()

As per #590, I can't reproduce this on my side. I think this was resolved by #616 which occurred after this tickets (2019-11-17).

Can you try getting latest and seeing if this is still an issue?

Thanks

**Comment by gnosygnu** [comment] 2020-04-10 12:06
I'm going to mark this resolved and try to track this in #590. Feel free to reopen if you want to track separately. Thanks!

**Closed by gnosygnu** 2020-04-10 12:06 UTC
Labels: core - parser, misc - needs more information
