### ISSUE TITLE
2014 Wiki Data Files and latest "xowa_app_windows_v3.3.4.1"

### ISSUE THREAD

**Issue by XowaWilliam** [gnosygnu/xowa#51] opened 2016-04-03 09:36 UTC
Hi Mr Gnosy.

While waiting for fix of latest corrupt file "_Xowa_enwiki_2016-03-05_wiki_text_ns-100.7z_" I [posted](https://github.com/gnosygnu/xowa/issues/50) Saturday 2 April 2016, I decided to test latest platform "**xowa_app_windows_v3.3.4.1**" on my old set of data files from 2014, and did offline installation of three **simple.wiki** files below:

-  _simplewiki-latest-pages-articles.xml.bz2_
-  _simplewiki-20140116-categorylinks.sql_
-  _simplewiki-20140116-page_props.sql_

To my surprise upon the audible ping with "**Script Done**" message, everything worked perfectly, and so did the new **search** feature incorporated in the latest release. 

Excitedly I proceeded to do the same with my 2014 set of **en.wikipedia** files, but this time after the ping and "**Script Done**" message, **en.wikipedia** looked OK, but the moment I typed into the **search** box, the screen came up with a message box prompting me to an upgrade on the **search** database. I thought this was strange since this did not happen on **simple.wiki**. So I complied with the request, and after another 40 minutes or so, another ping came, but the **search** menu just prompted me to do an upgrade again.

Not sure if latest set of data files of 2016-3 is going to fix this. I will report back later after I download the fixed "_Xowa_enwiki_2016-03-05_wiki_text_ns-100.7z_" I'm expecting you to upload later today.

By the way the **search** feature is yet another great improvement of the already exemplary **Xowa** offline Wikipedia product. **Thank you** for all your hard work, it is greatly appreciated.
William

**OS**: Windows 7 32

**Comment by MacSquirrel-Jedi** [comment] 2016-04-03 11:54
Hello,
- latest platform "xowa_app_windows_v3.3.4.1_x64" is also replacing original images file, after offline upgrade. For example en.wikibooks.org-file.xowa (1,82 GB) is replaced en.wikibooks.org-file.xowa (56 kB). Same situations is for others. 
- after offline upgrade home/wiki/Dashboard/Wiki_maintenance is showing that search level is v1
- im not able to finish offline upgrade for en.wikisource.org with enwikisource-20160305-pages-articles.xml.bz2 the import proces freeze. 

Wish you the best. this is anyway great app, great idea to have a knowledge of mankind in PC :) 
(windows 10 x64, jre-8u77)

**Comment by gnosygnu** [comment] 2016-04-04 01:44
Hi. Thanks for the detailed explanation.

> Excitedly I proceeded to do the same with my 2014 set of en.wikipedia files, but this time after the ping and "Script Done" message, en.wikipedia looked OK, but the moment I typed into the search box, the screen came up with a message box prompting me to an upgrade on the search database. I

Yeah, the 2014 set is not going to work with the new data. It will behave just as you described: it will keep prompting you to upgrade.

The best fix is to just use the 2015-03 set. I uploaded the corrupt archive tonight, and you should just be able to use them all

I'm also trying to see if I can fix this issue. If it's easy, I'll add the fix to the next version -- possibly tomorrow. Even then, I would still ask you to use the 2015-03 set.

> By the way the search feature is yet another great improvement of the already exemplary Xowa offline Wikipedia product. Thank you for all your hard work, it is greatly appreciated.

Thanks for the praise. :) Really appreciate it, and glad that the new feature is useful!

**Comment by gnosygnu** [comment] 2016-04-04 01:49
@MacSquirrel-Jedi 

Hi! Thanks for the detailed report. I reply to your points below. Let me know if I miss anything. Thanks!

>  latest platform "xowa_app_windows_v3.3.4.1_x64" is also replacing original images file, after offline upgrade. For example en.wikibooks.org-file.xowa (1,82 GB) is replaced en.wikibooks.org-file.xowa (56 kB). Same situations is for others.

Yup, this is how it works. The 56 KB files are basically empty files. They should be replaced with the files you downloaded from archive.org. I'll make this part of the upgrade process more automatica in the future, but in the meantime, you will need to manually replace the data.

> after offline upgrade home/wiki/Dashboard/Wiki_maintenance is showing that search level is v1

Sadly, I confirm this is a bug. I will fix this in the future, but the Wiki_maintenance page needs a general rewrite. I'll try to at least have it reflect the correct search version level

>    im not able to finish offline upgrade for en.wikisource.org with enwikisource-20160305-pages-articles.xml.bz2 the import proces freeze.

That's odd. I'll try to reproduce it again tomorrow and report back here.

**Comment by XowaWilliam** [comment] 2016-04-04 11:26
Hi Mr Gnosy.

I downloaded the new uploaded "_Xowa_enwiki_2016-03-05_wiki_text_ns-100.7z_" file, but after installation the **Search** feature failed to work again, in the same manner as when I used 2014 data set as described in my first post.
I am concerned that the latest file I downloaded might be the cause, because for some strange reason, the icon is a different color to other downloads. _Indicated by red arrow in image below_
![en wiki image](https://cloud.githubusercontent.com/assets/12995082/14240408/0aa024fa-fa45-11e5-9111-9c96d036ebb9.gif)

Using 7ZIP utility, I did a test of the archive and it passed, but I remain sceptical. _See image details_
![zip test](https://cloud.githubusercontent.com/assets/12995082/14240492/9a817448-fa45-11e5-9926-0dbfb5377d1d.gif)
Please confirm that all the file info is correct, I have virtually depleted my April data quota, and I would be disappointed doing another 4GB download that was not necessary.


**Some additional information**.

After decompressing all six 7z data files, I had **33** files in the **en.wikipedia.org** directory.
After doing a manual installation of **search** feature through "**Wiki maintenance**" I had **38** files in the **en.wikipedia.org** directory.

When the **search** feature completed I observed that the mouse icon would appear as a black block when hovering over any text in Xowa.

I have also sent you a **Session Log** file by email, which might help to solve this problem.

Thanks.
William

**Comment by gnosygnu** [comment] 2016-04-04 23:47
@XowaWilliam Sorry for the problems. 

* The search.7z on archive.org was incomplete. It was missing two files. I uploaded a new .7z that is about 650 MB: https://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2015-12-06_wiki_xtn_search.7z . Hopefully that will be small enough to download again.
* The Xowa_enwiki_2016-03-05_wiki_text_ns-100.7z file is fine. It only has article data and does not affect the search. I don't know why it has a different icon color in your picture. It looks like you selected it for a cut-operation. I'd try restarting your computer and seeing if the color still remains.
* Your listing of six 7z files is correct. If you still have problems with English Wikipedia, I'll download the files again from archive.org to make sure nothing got corrupted.
* All six 7z files do decompress to 33 files. However, as I mentioned above, I made a mistake and omitted two files. There should be 35 files in total.
* 38 files seems like too many for the old wiki. I think the count should be at 35 for your old wiki. If you want, you can open a command prompt and do
```
dir X:\xowa\wiki\your_old_enwiki_folder > X:\wiki.txt
```
Afterwards, send me the text file in X:\wiki.txt
* I don't have an explanation for the black block. It sounds like a weird UI glitch. Can you try restarting XOWA and seeing if it remains? If it does, please send me a screenshot.
* Thanks for the session log. It indicated an incomplete build of the search database. Unfortunately, the new search databases may take some time to build (3-5 hours). I'm working on making it faster, but your best bet is to let it run overnight.

Hope this helps. Thanks.

**Comment by gnosygnu** [comment] 2016-04-05 01:50
@MacSquirrel-Jedi 

>> im not able to finish offline upgrade for en.wikisource.org with enwikisource-20160305-pages-articles.xml.bz2 the import proces freeze.

> That's odd. I'll try to reproduce it again tomorrow and report back here.

This turned out to be a bug. The new search system broke offline imports for large wikis (wikis with a dump > 1.5 GB).

It's fixed in tonight's release. I tested specifically with enwikisource-20160305.

Also, I like to credit users for reporting bugs. Currently there's a line in the Change log that says "Import: Fix offline import for large wikis. {detected by anonymous}". Let me know if you'd like to be cited by a nickname, or would rather remain anonymous.

Thanks again for the report!

**Comment by MacSquirrel-Jedi** [comment] 2016-04-06 02:22
@gnosygnu 
i have no problem to be citated by nickname :) thx

**Comment by gnosygnu** [comment] 2016-04-07 01:24
@MacSquirrel-Jedi Cool. Thanks for the confirm. I changed it to "Import: Fix offline import for large wikis. {detected by MacSquirrel-Jedi}". It'll be in the change log for the next version of XOWA.

Thanks again for the report!

**Comment by gnosygnu** [comment] 2016-04-11 05:15
I'm marking this ticket closed. Let's use https://github.com/gnosygnu/xowa/issues/53 to track problems with the search-database-rebuild. All other issues should be handled above. Let me know if I missed anything. Thanks.

**Closed by gnosygnu** 2016-04-11 05:15 UTC
Labels: setup
