### ISSUE TITLE
Request for images in gu wiki

### ISSUE THREAD

**Issue by cyberorg** [gnosygnu/xowa#130] opened 2017-02-14 06:47 UTC
Hi, how do I get images in these wikis? Not sure if I have to request here for them.

http://gu.wikipedia.org/wiki/
http://gu.wiktionary.org/
http://gu.wikisource.org/
http://gu.wikibooks.org/
http://gu.wikiquote.org/

Thanks and apologies if I've missed something obvious(like I posted this on sourceforge before finding out about move to github).

**Comment by gnosygnu** [comment] 2017-02-14 13:21
Hey! Thanks for the interest in XOWA!

My current build machine is in the process of being rebuilt, but the above wikis look small enough. (at least compared to en.wikipedia.org)

Let me try to get something to you by next week. Will post again here then

Thanks!

**Comment by cyberorg** [comment] 2017-02-15 04:32
Thanks for creating amazing XOWA and all the support you provide to all users :)

**Comment by gnosygnu** [comment] 2017-02-21 03:53
I uploaded the Gujarati wikis tonight. When you get a chance, please try the following:

* Go to Download Central
    * On XOWA: Tools -> Download Central (also home/wiki/Special:XowaDownloadCentral)
    * ON XOWA Android: Left menu -> XOWA -> Download button
* On the "Available" table, click the "blue down arrow" all the way to the right
* You'll see a status message in the bottom right about the recent additions
* Select <code>Gujarati</code> from the language dropdown
* Add the wikis and download

I'm going to mark this issue resolved, and will probably close sometime tomorrow. Let me know if there's anything else.

Thanks!

**Comment by gnosygnu** [comment] 2017-02-22 02:58
As mentioned last night, the gu.\* wikis have been uploaded. I'm going to mark this ticket closed. Let me know if there's anything else.

**Comment by cyberorg** [comment] 2017-02-25 08:15
Sorry for late reply, just tested the latest, there are still some issues:

1. Images are missing from most pages for example gu.wikipedia.org/wiki/યુસૈન_બોલ્ટ 

2. https://gu.wiktionary.org/wiki/વિકિકોશ:શબ્દ_અનુક્રમણિકા is the index page that is missing from gu.wiktionary.org

3. You can remove gu.wikibooks.org/ as there is nothing in there "This wiki has been closed"

Thanks again

**Comment by gnosygnu** [comment] 2017-02-25 15:50
Hey, thanks for the feedback. Unfortunately I wasn't able to reproduce either 1 or 2. See the screenshots below.

I'm going to guess that maybe the files weren't pulled down from Download Central? If you can, put in the following into your url bar <code>home/wiki/Special:XowaDiag?type=fs.check&wiki=gu.wikipedia.org</code>

I get output like this:

```
scanning: C:\xowa\wiki\gu.wikipedia.org\
fil|gu.wikipedia.org-core.xowa|5705728|20170220 224136.019
fil|gu.wikipedia.org-file-core.xowa|3104768|20170220 224856.572
fil|gu.wikipedia.org-file-ns.000-db.001.xowa|216289280|20170220 225104.696
fil|gu.wikipedia.org-file-ns.004-db.001.xowa|5234688|20170220 225109.701
fil|gu.wikipedia.org-file-ns.014-db.001.xowa|364544|20170220 225111.633
fil|gu.wikipedia.org-file-user.xowa|57344|20170220 224136.351
fil|gu.wikipedia.org-html-ns.000.xowa|133484544|20170220 224826.965
fil|gu.wikipedia.org-html-ns.004.xowa|1945600|20170220 224833.835
fil|gu.wikipedia.org-html-ns.008.xowa|212992|20170220 224835.910
fil|gu.wikipedia.org-html-ns.014.xowa|286720|20170220 224835.152
fil|gu.wikipedia.org-xtn.category.core.xowa|36864|20170220 224837.534
fil|gu.wikipedia.org-xtn.category.link-db.001.xowa|24702976|20170220 224853.272
fil|gu.wikipedia.org-xtn.search.core.xowa|3608576|20170220 224144.460
fil|gu.wikipedia.org-xtn.search.link-title-ns.000-db.001.xowa|2658304|20170220 224144.481
fil|gu.wikipedia.org-xtn.search.link-title-ns.999-db.001.xowa|925696|20170220 224144.488

scanning: C:\xowa\file\gu.wikipedia.org\

scanning: C:\xowa\file\gu.wikipedia.org\fsdb.main\

scanning: C:\xowa\file\gu.wikipedia.org\fsdb.user\

scanning: C:\xowa\file\gu.wikipedia.org\fsdb.update_00\
```

I'd guess that your files are different

Regarding gu.wikibooks.org: Yeah, I realized that after I proofed them. I uploaded them anyway since they were generated. I'll remove them whenever I generate the set again.

![guwiki](https://cloud.githubusercontent.com/assets/4994104/23332449/b4346126-fb47-11e6-9c78-30aa8ca7c96c.png)
![guwiktionary](https://cloud.githubusercontent.com/assets/4994104/23332450/b439c6ca-fb47-11e6-80a4-167e65ee7678.png)

**Comment by cyberorg** [comment] 2017-02-26 06:51
Sorry about that, Got images on wikipedia.

The error on gu.wiktionary.org is that
વિક્શનરી:શબ્દ અનુક્રમણિકા links to વિકિકોશ:શબ્દ_અનુક્રમણિકા on https://gu.wiktionary.org/wiki while on xowa વિક્શનરી:શબ્દ અનુક્રમણિકા links to વિક્શનરી:શબ્દ અનુક્રમણિકા which is broken.

Same for all વિક્શનરી:* links,  it links to વિકિકોશ:* online but not on xowa.

Directly putting in વિકિકોશ:* works, but without the links working correctly on home page it is impossible to get too that index page without knowing exactly what to type.

**Comment by gnosygnu** [comment] 2017-02-26 16:24
> Sorry about that, Got images on wikipedia.

No worries. Glad it works. 👍 

> The error on gu.wiktionary.org is that
વિક્શનરી:શબ્દ અનુક્રમણિકા links/redirects to વિકિકોશ:શબ્દ_અનુક્રમણિકા on https://gu.wiktionary.org/wiki while on xowa વિક્શનરી:શબ્દ અનુક્રમણિકા links to વિક્શનરી:શબ્દ અનુક્રમણિકા which is broken.

Ah, I see the issue now.

You can work around this manually if you're only planning to use this on the PC (not Android HTML databases)

* Open up C:\xowa\bin\any\xowa\cfg\wiki\core\gu.wiktionary.org.gfs (or wherever you have XOWA set up) in a text editor. Make sure the text editor supports Unix style line-breaks (\n), not Windows (\r\n)
* Add the following line as line 4 in the file: <code>4|વિક્શનરી</code>. When you're done, the top should look like this
```
// wiki.ns_mgr.aliases.bgn
ns_mgr.add_alias_bulk("
4|Wiktionary
4|વિક્શનરી
6|Image
7|Image_talk
");
```
* Save the file and restart XOWA. The links will be blue, not red

Let me know if you need Android, and I'll rebuild and reupload the databases.  Otherwise, if you don't, I'll try to rebuild them in a week or so

Also, if you're interested, the technical reason this fails is that these gu.wiktionary.org links rely on "વિક્શનરી" as a **namespace alias** for "Project" (id=4). Most links in most wikis use the official **namespace name**, which in this case happens to be "Wikibooks".

I need to regen all the .gfs files to update them with **namespace aliases**. I've been meaning to do that for a while, but haven't had the motivation for them.

Hope this helps. Thanks.

**Comment by cyberorg** [comment] 2017-02-27 13:08
adding 4|વિક્શનરી fixed it, consider all issues resolved, thanks.

**Comment by gnosygnu** [comment] 2017-03-01 03:04
Good to hear. 👍 

I'm going to close the issue. Let me know if there's anything else.

Thanks!

**Closed by gnosygnu** 2017-03-01 03:04 UTC
Labels: resolved, wiki requests
