### ISSUE TITLE
Allow custom Javascript for Wikis

### ISSUE THREAD

**Issue by darkdreamingdan** [gnosygnu/xowa#88] opened 2016-10-04 02:04 UTC
Hello

I'm wanting to use Xowa to distribute offline copies of our wiki ( https://wiki.multitheftauto.com ).  I used a wikiteam generated XML dump, and it largely worked well (after disabling common.css downloading).

However, our Wiki makes use of some custom javascript and custom extensions.  For example: https://wiki.multitheftauto.com/wiki/GetPlayerName
This page has the `{{Server client function}}` template, which imports the following MediaWiki hooked tags:
`<pageclass class="both" subcaption="Shared function"></pageclass>
<lowercasetitle></lowercasetitle>`
We have written an extension to do the following:
1) For 'pageclass' tags, set a coloured page outline and print the subcaption.  Remove the tag from visibility.
2) For 'lowercasetitle' tag, change the firstHeading to have a lowercase first character, to match our function name.

Now, I don't expect Xowa to offer MediaWiki's setHook or any extensive MW Extension functionality.  However, I would like to see a simple way to import JS without modifying the Xowa core files.  I would like to distribute .xowa or .xml.bz2 MediaWiki dumps, alongside a JS to replicate the above functionality. 

[wikimultitheftautocom-20161004-current.xml.bz2.zip](https://github.com/gnosygnu/xowa/files/507520/wikimultitheftautocom-20161004-current.xml.bz2.zip)

Obviously the core XOWA files can be modified to achieve this, but I would rather try and find a more elegant solution.  I couldn't find any way to load JS from the wiki dump, and MediaWiki:Common.js is seemingly ignored.

Cheers

**Comment by gnosygnu** [comment] 2016-10-04 04:23
Hi! Thanks for the interest in XOWA!

Your issue is an interesting one. Let me answer some points from your comment:
* MediaWiki:Common.js: XOWA doesn't load this page because it often calls functions that would fail in the offline object. Particularly, the "mw" object and methods like "mw.loader" or "mw.log". Ideally, I'd reproduce some sort of offline "mw" object that simulates the full functionality of the online one, but it's pretty involved. Generally, whenever I find something in Common.js, I just manually extract it and call it from an extension.
* Simple way of embedding js in XOWA: If you want to embed custom js in XOWA, there is an unsupported way
    * Open /xowa/bin/any/xowa/cfg/app/xowa.gfs
    * Search for the following line:  <code>&lt;script src="~{app_root_dir}bin/any/xowa/html/res/src/xowa/find/xowa_find_html.js" type='text/javascript'>&lt;/script></code>
    * Replace it with the following
```
<script src="~{app_root_dir}bin/any/xowa/html/res/src/xowa/find/xowa_find_html.js" type='text/javascript'></script>
<script>
alert('your custom script');
</script>
```
* MediaWiki extensions: XOWA selectively rewrites MediaWiki extensions in Java. Unfortunately, that means that most extensions like your pageclass and lowercasetitle will need to be ported over manually. If it's simple to port, I can do it myself. Just point me to the source, and I'll give you an idea.

If you want a customized way of including extensions, I've thought about allowing extensions via Javascript or Lua. Something like the following:
* Write an extension called my_extension.js (or my_extension.lua)
* Place it in a certain file location. For example, /xowa/bin/any/xowa/xtns/js/my_extension.js
* When XOWA finds a tag like "&ltmy_extension>" or "{{#my_extension}}", it calls the code in my_extension.js

I don't know if this is what you had in mind for a more elegant solution. If you are interested in this, let me know, and I can try to get that done over the course of the month.

Let me know if I missed anything from above. Thanks!

**Comment by darkdreamingdan** [comment] 2016-10-04 13:18
Your customised extension suggestion sounds awesome!  I think it would be better this way, rather than you coming up with a bespoke solution just for us (as flattering as that is).  This is simply because I've simplified the matter for this bug report, but in reality we have a number of customisations that I'd like to port across - and I expect the nature of them may change with time.

Here's some functionality I'd like to see:
- A generic way to include any JS file, without hooks, perhaps with 'inject' locations at either the top or bottom of the DOM.  This would effectively be just like adding `<script/>` to xowa.gfs as you proposed, but hopefully without interfering with Xowa's core files.  For example, we make use of [Google Prettify](https://www.mediawiki.org/wiki/Extension:GoogleCodePrettify) to do our syntax highlighting rather than MediaWiki's own, and including generic JS would allow us to (most likely) achieve this. We also have some custom JavaScript to highlight keywords in our syntax highlights. (For example, [here you can see](https://wiki.multitheftauto.com/wiki/GetPlayerName) clickable 'string' and 'getPlayerName' keywords in the syntax box).  
This would effectively be just like adding `<script/>` to xowa.gfs as you proposed, but hopefully without interfering with Xowa's core files.
 - _Sidenote: I notice Xowa doesn't offer syntax highlighting on it's own, which is no surprise given the complexity of Pygments and PHP bindings.  You may be interested in employing a pure JavaScript solution such as Google Prettify which would be way easier for you to implement and replicate the same functionality_
- As you describe, bindings of `<tag></tag>` just like MediaWiki's setHook function.  This should really happen _before_ XOWA renders anything, just like MW's own.  
 - The reason this should happen is we use `<section></section>` tags with some JS magic to replicate the big yellow and red boxes in the "Example" section at the bottom of the [getPlayerName ](https://wiki.multitheftauto.com/wiki/GetPlayerName) page.  Unfortunately, there is some Markup conflict here, and MediaWiki and Xowa (correctly) seems to strip anything in between `<section/>` tags.  If you access the same page in Xowa the content just dissappears.  Hence, the hooks should occur before Xowa renders (ideally), just like MediaWiki - so that we can override these tags ourself.
 - I understand this is probably a bit of a picky request, so if it's too difficult it's no big deal.  My backup plan is to simply find+replace `<section>` and replace it with e.g. `<_section>` in the XML dump so there's no longer a conflict.

I would also suggest if there's someway that the JS files sit closer to the Wiki files themselves, rather than Xowa's own directory.  This just means we can advise users to download a generic Xowa release and install our offline wiki in it's own directory.  Once again, this isn't vital.

I've attached the main code for our extensions which might help in understanding our strange customisations.  

[extension_wiki.zip](https://github.com/gnosygnu/xowa/files/508486/extension_wiki.zip)


Thanks for your speedy response, I'm amazed at how well Xowa works already, you've got a great project here.

**Comment by gnosygnu** [comment] 2016-10-05 04:25
> Your customised extension suggestion sounds awesome! I think it would be better this way, rather than you coming up with a bespoke solution just for us (as flattering as that is). This is simply because I've simplified the matter for this bug report, but in reality we have a number of customisations that I'd like to port across - and I expect the nature of them may change with time.

Cool! If you have a number of customizations planned, then I agree that a general extension framework is best.

> Here's some functionality I'd like to see:
>  A generic way to include any JS file, without hooks, perhaps with 'inject' locations at either the top or bottom of the DOM....

Sure. As a rough proposal, how about something like this?:
* XOWA checks the wiki directory for a subfolder called <code>/bin/html/include/top</code> or <code>/bin/html/include/bot</code>. For example, <code>/xowa/wiki/multitheftauto.com/bin/html/include/top</code>
* If any .css or .js files exist, XOWA includes them into the HTML document with the corresponding <code>&lt;style></code> or <code>&lt;script></code> tag.

For example, <code>/xowa/wiki/multitheftauto.com/bin/html/include/bot/lowercasetitle.js</code> would automatically add a <code>&lt;script src='file:///xowa/wiki/multitheftauto.com/bin/html/include/bot/lowercasetitle.js'></code> for every document at the bottom of the page

In turn, lowercasetitle.js would have the following:
```
function makeTitleLowercaseFirstLetter() {
	var content = document.getElementById("content");
	var h1Elements = content.getElementsByTagName("h1");
	if ( h1Elements.length != 0 ) {
		var current =  h1Elements[0].innerHTML;
		h1Elements[0].innerHTML = current[0].toLowerCase() + current.substr(1);
		
		document.title = document.title[0].toLowerCase() + document.title.substr(1);
	}
}
makeTitleLowercaseFirstLetter();
```

> Sidenote: I notice Xowa doesn't offer syntax highlighting on it's own, which is no surprise given the complexity of Pygments and PHP bindings. You may be interested in employing a pure JavaScript solution such as Google Prettify which would be way easier for you to implement and replicate the same functionality

Yeah, I looked at Pygments, and Python is not my thing. I didn't consider Google Prettify at the time, but I'll definitely revisit again. Thanks for the recommendation!

> As you describe, bindings of <tag></tag> just like MediaWiki's setHook function. This should really happen before XOWA renders anything, just like MW's own.

If I follow correctly, I think this is doable. Just to be clear, XOWA handles extensions by doing the following:
* Sees an extension tag. For example, <code>&lt;my_xtn key1=val1></code>.
* Looks for the closing tag. For example, <code>&lt;/my_xtn></code>.
* Takes all the content in between the tags and submits it and the attributes to the extension code. For example, <code>&lt;my_xtn key1=val1>some text&lt;/my_xtn></code> passes <code>some_text</code> and <code>key1=val1</code> to the extension code.

This is pretty much how MediaWiki works. It allows extensions to embed wikitext (<code>&lt;poem></code> tag) or some custom format (<code>&lt;math></code> tag) and process it. I can't think of any extension that strictly allows raw HTML, but I can't think of anything that would forbid it -- so long as you don't reuse the closing extension tag. So something like <code>&lt;my_xtn>&lt;a href=multitheftauto.com>a&lt;/a>&lt;/my_xtn></code> should be possible.

> I would also suggest if there's someway that the JS files sit closer to the Wiki files themselves, rather than Xowa's own directory. This just means we can advise users to download a generic Xowa release and install our offline wiki in it's own directory. Once again, this isn't vital.

File location is easily doable, so no worries. ;)

Again, similar to the above, I'm imagining something like the following:
* XOWA checks the wiki directory for a subfolder called <code>/bin/xtn/js</code>
* XOWA looks for a file ending with <code>.xtn.json</code>. For example, <code>/xowa/wiki/multitheftauto.com/bin/xtn/js/my_xtn.xtn.json</code>
* XOWA pulls out some metadata from the json file. For now, I'm thinking something like <code>{xml={name='my_xtn'} js={file='my_xtn.js', proc='my_xtn'}}</code>
* When XOWA sees a <code>&lt;my_xtn></code> in the wikitext, it loads up <code>my_xtn.js</code> and calls a function called <code>my_xtn(app, wiki, page, node_attributes, node_text)</code>.

A sample my_xtn.js could look like this:
```
function my_xtn(app, wiki, page, node_attributes, node_text) {
  return node_text + ' (from XOWA!)'
}

```

A sample wikitext could look like this:
```
<my_xtn>Hello, world!</my_xtn>
```

And the corresponding HTML output would be this:
```
Hello, world! (from XOWA!)
```

> I've attached the main code for our extensions which might help in understanding our strange customisations.

Can't really comment on the main.php (I don't have experience in extending MediaWiki), but the extension functions looked fine.

> Thanks for your speedy response, I'm amazed at how well Xowa works already, you've got a great project here.

No problem. Thanks for the kind words! Let me know what you think regarding the above!

**Comment by darkdreamingdan** [comment] 2016-10-05 12:20
Everything sounds great to me, with one minor criticism:
> XOWA checks the wiki directory for a subfolder called /bin/html/include/top or /bin/html/include/bot. For example, /xowa/wiki/multitheftauto.com/bin/html/include/top

The issue here is that there's not a specification for the order of load within each directory.  Perhaps a meta is required here, because the order of loaded files within a folder might need to be specified.  Otherwise i assume it would depend on OS traversal (alphabetical?) to specify the order of load - this might be problematic when loading JS libraries and dependencies.

Also, the 'top' loader should probably come after Xowa's own JS scripts, so we don't end up reloading stuff like JQuery etc.

**Comment by gnosygnu** [comment] 2016-10-06 06:37
> The issue here is that there's not a specification for the order of load within each directory. Perhaps a meta is required here, because the order of loaded files within a folder might need to be specified. 

Yup. Excellent point. I'll add some sort of <code>/bin/html/include/manifest.json</code> to help control load order

> Also, the 'top' loader should probably come after Xowa's own JS scripts, so we don't end up reloading stuff like JQuery etc.

Good point here too. I'm thinking about specifying this in the manifest.json. Something like:
```
{ "batches":
  [ 
    { "name":"batch1"
    , "location":"top-before or top-after or bottom"
    , "files":
      [ 
        { "file":"./top/file1.js"
        }
      , { "file":"./top/file2.js"
        }
      ]
    }
  ]
}
```

Hope that looks good. Thanks!

**Comment by gnosygnu** [comment] 2016-10-13 16:55
Hey. Sorry for the delay, but I've been caught up with rewriting parts of the Categories system.

I put together a dirty version for the first part of the custom JavaScript solution (injecting javascript files). I'm still going to clean it up over the next few days.

If you want to take a look, please try the following:
* Download the beta for your OS from here: https://github.com/gnosygnu/xowa/releases/BETA_v3.9.4.6
* Download the script.zip file: [simple.wikipedia.org_script.zip](https://github.com/gnosygnu/xowa/files/527708/simple.wikipedia.org_script.zip)
* If you haven't, install Simple Wikipedia. It takes about 5 minutes and there's a "Set up Simple Wikipedia" link on home/wiki/Main_Page
    * Note that you can use the steps below for any wiki, but I'd like to use simplewiki first to make sure we're comparing apples to apples.
* Extract the zip file to the following location: <code>C:\xowa\wiki\simple.wikipedia.org</code>. When you're done, you should have a file like <code>C:\xowa\wiki\simple.wikipedia.org\bin\html\script\boot.js</code>
* Run XOWA and load simple.wikipedia.org/wiki/Earth (or any page). You'll see that "Earth" is lowercased in the &lt;h1> element, as per your <code>makeTitleLowercaseFirstLetter</code>.

Here's some details on how it works:
* XOWA loads all .js files in <code>bin\html\script</code>. For now, there's just "boot.js", but technically, you can add "jquery.js" or something else for "boot.js" to use.
* boot.js has the following code (ignore the commented section):
```
var xowa_script = new Object();
xowa_script.main = function (page)
{
  page.Doc().Head().Add_elem("<meta name='lowercasetitle' content=''>", "top");
  page.Doc().Tail().Add_js_file("./exec/main.js", "");
  // page.Doc().Html_("<b>hi</b>");      
  /*
  if (  page.Url().Wiki_name() == 'simple.wikipedia.org'
     && page.Url().Page_name() == 'A')
  {
  }
  */
}
```
* The most important part is the <code>xowa_script</code> object and its corresponding <code>main</code> function. XOWA uses this as its entry point.
* In the example above, two things are done:
    * A &lt;meta> element is added to the head of the HTML document
    * A &lt;script> element is added to the bottom of the document. This will include the file at <code>C:\xowa\wiki\simple.wikipedia.org\bin\html\script\exec\main.js</code>
* The rest works as normal. The HTML document loads and it runs <code>main.js</code> which will lowercase the firstLetter of the title.

Much of the steps is subject to change, though the general approach should be the same. I just wanted to put something out there for now so you can take a look and see if there's anything I'm missing.

I'll add the second part (adding extension functions to handle &lt;lowercasename>) once most of the first part is finalized.

Looking forward to any input. Thanks!

**Comment by gnosygnu** [comment] 2016-10-16 17:26
For tonight's release, I added a lot more changes to the scripting system. In brief:
* Supports lua scripts
* Syntax tweaks (lowercase; no direct objects)
* More API functions for changing the page
* Load utility functions

If you want to try it on your system, you should be able to do the following:
* Download tonight's release
* Download the following zip file: [simple_wikipedia.org_scripting.zip](https://github.com/gnosygnu/xowa/files/531975/simple_wikipedia.org_scripting.zip)
* Unzip the file to simple.wikipedia.org (or you can try unzipping directly into your mulitheftauto wiki). You'll need a file like <code>C:\xowa\wiki\simple.wikipedia.org\bin\any\script\xowa.script.main.js when done.</code>
* Enable scripting at <code>home/wiki/Options/Scripting</code>
* Visit any page in simple.wikipedia.org

I added the documentation in-line within the script file. See: http://xowa.org/home/wiki/App/Xtn/Scripting . If anything's unclear, please feel free to ask.

I think the 1st stage is done for now (injecting js / lua via standalone files). I'll work on the 2nd stage (running js / lua files directly from the wikitext; EX: &lt;lowercasename>) either later this week / month.

Thanks.

**Comment by darkdreamingdan** [comment] 2016-10-16 19:15
Sorry I didn't reply to your last message - I've been swamped.  This all looks super awesome.  I'll give it a try as soon as I get a chance.

**Comment by gnosygnu** [comment] 2016-10-16 20:28
No worries! Take your time and get to it whenever you can. Thanks!

**Comment by gnosygnu** [comment] 2017-01-04 03:09
Hey, I'm marking the 2nd stage as a future enhancement for now. Let me know if you're still interested in it, and I'll resume then.

Thanks!

**Closed by gnosygnu** 2017-01-04 03:09 UTC
Labels: future enhancement, javascript, non wikimedia
