### ISSUE TITLE
Unicode Character 'LEFT-TO-RIGHT MARK' appearing

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#501] opened 2019-06-21 06:21 UTC
200th issue !!!!!

I was looking at redirections and came across this
commons.wikimedia.org/wiki/Primula_eliator -> Primula#Primula_eliator

I then compared xowa and mediawiki and got this:
![ltor](https://user-images.githubusercontent.com/861631/59901912-a3262480-93f4-11e9-8620-2968e54c6fa7.gif)
I have high-lit `xE2x80x8E`, this is the hex representation of \\u200e which is the unicode left-to-right mark 
In the screen shot there are a number of these

I am not sure how they are getting there (and hence how to remove them)

**Comment by desb42** [comment] 2019-06-21 07:29
On further investigation,
this page 'calls' Template:VN, 
which in turn 'calls' Module:Wikidata4Bio, function getLanguagesManagedByVN,
this 'calls' mw.language.fetchLanguageNames

which seems to point the finger at
\xowa\bin\any\xowa\cfg\lang\data\names.json
As this contains lines of the form

    , "name":"қазақша (кирил)\xE2\x80\x8E"

I can (and in my version will) remove the 'excess' \xE2\x80\x8E - but I do not know if there are other consequences

There are also some \xE2\x80\x8F (Right-to-left mark) that I removed as well

**Comment by gnosygnu** [comment] 2019-06-22 03:53
> 200th issue !!!!!

Lol. I wish I could keep up with just half your pace. I think I'm struggling to get to your 70th or so issue. :(

Still, nice going. And, as always, thanks for all the work!

> I can (and in my version will) remove the 'excess' \xE2\x80\x8E - but I do not know if there are other consequences

> There are also some \xE2\x80\x8F (Right-to-left mark) that I removed as well

First, nice detective work. :+1: 

Just so you know, the ltr and rtl marks originated from here: https://github.com/wikimedia/mediawiki/blob/master/languages/data/Names.php#L126

The problem is that XOWA does not correctly parse "\x" sequences. (it does handle "\u" as well as basic "\n", "\t"). 

You can work around this on your side by changing to "\u200E". I'll fix the json parsing code to read "\u{200E} as well as \xE2\x80\x8E"

You can also keep it omitted. I think the main problem is when showing an ltr word in a rtl language (see the C++ example here: https://en.wikipedia.org/wiki/Left-to-right_mark

```
Without an LRM control character, the result looks like this:

??? ++C ?? ??? ????? ??????...

With an LRM entered in the HTML after the ++, it looks like this, as the writer intends:

??? C++? ?? ??? ????? ??????...
```

**Comment by gnosygnu** [comment] 2019-06-24 01:37
Fixed with the commit above. Specifically:
* Updated names.json to use \u2000E
* Changed XOWA's home-made bare-bones PHP parser to properly read \xE2\x80\x8#

Verified against commons.wikimedia.org/wiki/Primula_eliator

Thanks again for all the detail!

**Closed** 2019-06-28 02:05 UTC
Labels: [effort 4 - hours], [priority 3 - moderate], [resolved - commit], [risk 3 - moderate], [schedule 1 - within days], [type - bug], core - parser
