### ISSUE TITLE
extra visual space in 'listen'

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#703] opened 2020-04-10 09:36 UTC
I was looking at `en.wikipedia.org/wiki/Poland` for another reason and noticed this discrepancy
![poland3](https://user-images.githubusercontent.com/861631/78980381-b20dcd00-7b15-11ea-9b84-c8041d8ce995.gif)
In the first paragraph the word `listen` appears twice.
xowa shows 'listen' as `listen )` whereas mediawiki shows `listen)` 
That is, there seems to be an additional space

On investigating the page source, the difference between xowa and mediawiki (in this case) is a linefeed.
That is
mediawiki has the snippet

    .ogg">listen</a></span>
whereas the equivalent in xowa is

    .ogg">listen
    </a></span>
I have tracked this down to the classfile `Xoh_file_fmtr__basic.java`
Line 30 deliberately inserts a linefeed

    private final    Bry_fmt fmtr_full_media = Bry_fmt.Auto("<a href=\"~{a_href}\" xowa_title=\"~{a_xowa_title}\">~{html}\n</a>");

removing that linefeed seems to cure this discrepancy

**Comment by gnosygnu** [comment] 2020-04-10 11:59
Again, amazing eye for detail! I don't think I would have ever noticed that extra whitespace. Really appreciate the hunting down the cause too!

For reference, I generally added a bunch of extra whitespace (new-lines; spaces) so that the HTML would "line" up properly. I assumed that the whitespace would not affect the HTML, but it does in this case.

Anyway, fixed with your recommended commit above. Thanks!

**Closed** 2020-04-19 13:16 UTC
Labels: [effort 5 - less than an hour], [priority 3 - moderate], [resolved - commit], [risk 4 - minor], [schedule 1 - within days], [type - bug], core - parser, misc - commit submitted
