### ISSUE TITLE
enwikisource Page not found

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#719] opened 2020-05-07 09:20 UTC
This is very minor

I was using the navigation `Random transcription` and suddenly I got a `Page not found`

I would expect the randomising to at least find a page.

The specific page is `en.wikisource.org/wiki/Tlingit_Myths_and_Texts`

In the Main namespace, pages of the form `Tlingit_Myths_and_Texts/3` exist

I suspect but have not checked, that the randomiser tries to suggest top level pages

**Comment by gnosygnu** [comment] 2020-05-07 13:47
Thanks for the report! That's odd though: the randomiser doesn't have logic for top-level pages

My "random" guess is that maybe you've deleted pages, or something else is wrong with the data? See details below

---

I debugged now with a 2020-01 English Wikisource version, and confirmed that it hits this code:
https://github.com/gnosygnu/xowa/blob/341d2e13a43bb91e40b0c0204a750a5f56780a26/400_xowa/src/gplx/xowa/wikis/data/tbls/Xowd_page_tbl.java#L208-L215

The XOWA way of randomly selecting pages is different than MW. Basically, it does the following:
* When "building" / "importing" a new wiki, assign each page an incrementing number starting at 1
  * Page_A -> page_random_int = 1
  * Page_B -> page_random_int = 2
  * Page_C -> page_random_int = 3
  * etc.
* Store the count of all pages in a namespace within a separate namespace table
* When "Random page" is requested

```
sqlite> SELECT Count(*) FROM page WHERE page_namespace = 106;
Count(*)
----------
14996
sqlite> SELECT Max(page_random_int) FROM page WHERE page_namespace = 106;
Max(page_random_int)
--------------------
14996
sqlite> SELECT * FROM site_ns WHERE ns_id = 106;
ns_id       ns_name     ns_case     ns_is_alias  ns_count
----------  ----------  ----------  -----------  ----------
106         Index       1           0            14996
```

**Comment by desb42** [comment] 2020-05-08 09:34
The version of data I am using is 2020-03-01 - with no additions or deletions
I also misremembered - I was using `Random work` not `Random transcription`

Having done a little more analysis, I can see the pseudo randomness is working as stated.

However - there is something not quite right

I have been repeatedly pressing `Random work` and have just got this
![wolfe](https://user-images.githubusercontent.com/861631/81392553-c34af900-9116-11ea-9629-542408a789e3.jpg)
Note that the redirection is exactly the same as itself

I think that although in the case where the randomly selected page results in a redirection, the generated page contains a 'redirected from' link of itself rather than the original redirection.

I have had further instance of `Page not found` but have not yet been able to tell if the above issue contributes to this problem

**Comment by gnosygnu** [comment] 2020-05-08 14:00
> The version of data I am using is 2020-03-01 - with no additions or deletions

Cool. Thanks for confirm

> I also misremembered - I was using Random work not Random transcription

Yup, no worries. `Random work` is the same as `Random transcription`

> Having done a little more analysis, I can see the pseudo randomness is working as stated.

Yeah, don't have an explanation for the above then. I verified that my 2020-01 Main namespace is also "correct" (see **Pseudo-verification** section below)

More replies below (and SQL requests). If you're having problems running the SQL, can you upload your `en.wikisource.org-core.xowa` and I'll take a look at it?

Thanks!

---

> I have been repeatedly pressing Random work and have just got this
> Note that the redirection is exactly the same as itself

That's odd. Try this SQL statement and see if you there is a `Wolfe v. United States`? Basically it lists all pages which will redirect to `Wolfe`-like pages (for example: en.wikisource.org/wiki/291_U.S._7)

```
SELECT  * 
FROM    page 
WHERE   page_redirect_id 
   IN (SELECT page_id FROM page WHERE page_title LIKE 'Wolfle%United%');
```
> I think that although in the case where the randomly selected page results in a redirection, the generated page contains a 'redirected from' link of itself rather than the original redirection.

That's an interesting theory. Try this SQL statement. It should find all pages redirecting to itself.

```
SELECT  r.page_id          AS redirect_page_id
,       r.page_title       AS redirect_page_title
,       r.page_redirect_id AS redirect_target_page_id
FROM    page r
WHERE   r.page_redirect_id = r.page_id
;
```

> I have had further instance of Page not found but have not yet been able to tell if the above issue contributes to this problem

I thought of one other thing. It's possible that the MediaWiki dump data was bad and the redirect points to a deleted page

Try running this SQL. It'll find any redirects pointing to missing pages

```
SELECT  r.page_id          AS redirect_page_id
,       r.page_title       AS redirect_page_title
,       r.page_redirect_id AS redirect_target_page_id
,       p.page_id          AS target_page_id
,       p.page_title       AS target_page_title
FROM    page r
        LEFT JOIN page p ON r.page_redirect_id = p.page_id
WHERE   r.page_redirect_id != -1
AND     p.page_id IS NULL
--AND     p.page_title LIKE 'Wolfle%United%'
--LIMIT 10
;
```

---

### Pseudo-confirmation of pseudo-random data for Main namespace

```
sqlite> SELECT Count(*) FROM page WHERE page_namespace = 0;
Count(*)
----------
585492
sqlite> SELECT Max(page_random_int) FROM page WHERE page_namespace = 0;
Max(page_random_int)
--------------------
585492
sqlite> SELECT * FROM site_ns WHERE ns_id = 0;
ns_id       ns_name     ns_case     ns_is_alias  ns_count
----------  ----------  ----------  -----------  ----------
0                       1           0            585492
```

**Comment by desb42** [comment] 2020-05-09 06:45
On a deeper dive
Taking the class file `400_xowa\src\gplx\xowa\addons\wikis\pages\randoms\specials\Rndm_root_special.java`
Line 23 does the randomising

    byte[] random_ttl_bry = wiki.Db_mgr().Load_mgr().Find_random_ttl(ns);
Replacing this line with a fixed result like

    byte[] random_ttl_bry = Bry_.new_a7("291_U.S._7");
where page `291_U.S._7` is a redirect to `Wolfle_v._United_States`

This will produce the pages as shown above (with a seeming redirect to self)

This is happening as a consequence of the Special: page handling in `400_xowa\src\gplx\xowa\wikis\pages\Xow_page_mgr.java` Line 40
It is attempting to redirect to the 'real' page (in this case the 'real' page is also a redirect)

Somewhere along the way, the Xoae_page object is being updated with the result of the 'real' redirect, confusing some subsequent logic

**Comment by desb42** [comment] 2020-05-09 07:08
I have found that the call to Redirect in `Rndm_root_special.java`

    wiki.Data_mgr().Redirect(page, ns.Gen_ttl(root_bry));
is probably the cause

This routine in 'Xow_page_mgr.java`

    public void Redirect(Xoae_page page, byte[] page_bry) {
        Xoa_ttl trg_ttl = Xoa_ttl.Parse(wiki, page_bry);
        Xoa_url trg_url = Xoa_url.New(wiki.Domain_bry(), page_bry);
        page.Ttl_(trg_ttl).Url_(trg_url);
        page.Redirect_trail().Itms__add__article(trg_url, trg_ttl, null);
        wiki.Data_mgr().Load_from_db(page, trg_ttl.Ns(), trg_ttl, trg_url.Qargs_mgr().IsNoRedirect());
    }
calls `Load_from_db`

For the random page logic, this call is unnecessary  (it may be useful for other places)

If I take the first four lines of this routine and place them in the Rndm_root_special.java (instead of the call to Redirect) - it produces the result I expect

**Comment by desb42** [comment] 2020-05-09 07:27
Back to the original issue

`Rndm_root_special.java` contains the line

    byte[] root_bry = Xoa_ttl.Parse(wiki, random_ttl_bry).Root_txt();
which is stripping any subpages (Root_txt())

In my data `Tlingit_Myths_and_Texts/3` exists but `Tlingit_Myths_and_Texts` does not, hence the error.

should the call be to Page_txt()?

**Comment by gnosygnu** [comment] 2020-05-11 12:52
> For the random page logic, this call is unnecessary (it may be useful for other places)

Nice catch! Agree that this is unnecessary for Random and causes the weird `Redirected from` listing. Will fix for this issue

> byte[] root_bry = Xoa_ttl.Parse(wiki, random_ttl_bry).Root_txt();

And nice catch again redux! Yeah, that's the root cause of the issue above

The problem is that the "Random Root" page function deliberately skips any titles with "/". See: https://github.com/wikimedia/mediawiki/blob/master/includes/specials/SpecialRandomrootpage.php

So `Tlingit_Myths_and_Texts/3` can never be returned even though it sits in the Main namespace

At this point, I'm leaning towards this option:
* Change Random behavior to do a `SELECT page_id, page_title FROM page WHERE <<SOME_CONDITION>>`. 
  * In the case of random root page, the condition would be ```page_title NOT LIKE `%/%` AND page_redirect_id = -1 AND page_namespace = 0```
* Pick a random title from that recordset using `random(recordset.count)`
* Continue as normal

This won't be as "quick" as the current behavior, but it's more true to the MediaWiki behavior and eliminates the bug above.

Will do in a commit tomorrow-ish

Thanks!

**Comment by gnosygnu** [comment] 2020-05-13 13:23
Made the commit above to address both issues ('Page not found' and 'Redirected from redirected title')

Commit is a bit large, b/c I added some extra database infrastructure to support selectRandomRow and unit-testing (the current database infrastructure tries to abstract away literal SQL as much as possible)

Thanks again @desb42 !

**Closed** 2020-05-17 21:07 UTC
Labels: [effort 5 - less than an hour], [priority 4 - minor], [resolved - commit], [risk 4 - minor], [schedule 2 - within weeks], [type - bug], core - special
