### ISSUE TITLE
ask a function

### ISSUE THREAD

**Issue by amirh123123** [gnosygnu/xowa#207] opened 2018-01-21 07:00 UTC
hi i export many pages from bayern munich from en.wikipedia.org i import in xowa 3 4 10 my pages import but cant load main page i copy this wiki in xowa 4 5 0 and go to all pages in wiki and read my page please add this function in next version of xowa and please add customizable main page example i want in main page i see bayern munich article thanks

**Comment by gnosygnu** [comment] 2018-01-22 04:08
Hi,

This is a duplicate of #191. I'm closing this issue now. If you want to discuss this issue, please do so at #191. Please do not create another duplicate issue.

Thanks.

**Closed by gnosygnu** 2018-01-22 04:08 UTC
Labels: duplicate
