### ISSUE TITLE
Problem with section of source code ending in ">".

### ISSUE THREAD

**Issue by bmihai** [gnosygnu/xowa#26] opened 2015-09-26 08:52 UTC
On version 2.9.2.1 (2015-09-13 18:11) I'm seeing a problem with the article

en.wikipedia.org/wiki/Type_system

Towards the end where there's some example code ending in ">". The rest of the article shows up all as code as well.

Let me know if this is too vague, I'm hoping it's obvious when looking at that article.

**Comment by gnosygnu** [comment] 2015-09-26 15:37
Hi! Thanks for the report! It made complete sense (the URL is the most important part).

The problem is the part starting with "&lt;do something> else" . &lt;do> is an extension for Wikivoyage and "eats up" the rest of the content if it's unclosed. You can see something similar at https://en.wikivoyage.org/w/index.php?title=Wikivoyage:Graffiti_wall&action=submit and previewing the following code:

```
the code:

<code>if <complex test> then <do something> else <generate type error></code>

Even if the expression <code><complex test></code> always evaluates to <code>true</code> at run-time, most type-checkers will 
```

By default, XOWA loads all extensions for all wikis. It really should disable the &lt;do> extension for English Wikipedia (just like the online version). I've been working on this change for all wikis, but probably won't have it until next week. I'll try to get in a limited patch (ignore &lt;do> in English Wikipedia) in the meantime.

Also, whenever the fix is released, I like to credit users for reporting bugs. There'll be a line in the changelog with something like "Do not load all extensions for each wiki {detected by anonymous}". Let me know if you prefer a nickname or would rather remain anonymous.

I'll post more in this thread when I have a fix. Thanks!

**Comment by gnosygnu** [comment] 2015-09-26 15:40
Also, as a simple workaround, you can Edit the page, change "&lt;do" to "&amp;lt;do" and save it. This will cause the rest of the page to show correctly.

Hopefully there'll just be a few pages with "&lt;do" on them.

**Comment by bmihai** [comment] 2015-09-26 18:13
Hi gnosygnu! Thank you for the great in-depth reply. Looking forward to the fix. I tried the quick workaround and it fixed it. I didn't know you could edit pages, either!

I don't feel worthy of a mention but "bmihai" would be fine. I promise to be more conscientious about bug reports to earn it. Thanks for being so consistently great to your users! :)

**Comment by gnosygnu** [comment] 2015-09-27 13:20
> I tried the quick workaround and it fixed it.

Cool! Thanks for the follow-up

> I didn't know you could edit pages, either!

Yup, I think that's one of the unique features of XOWA

> I don't feel worthy of a mention but "bmihai" would be fine.

Of course you absolutely deserve it! "bmihal" it is.

>  I promise to be more conscientious about bug reports to earn it. Thanks for being so consistently great to your users! :)

No need. Your bug report was great.

Thanks again!

**Comment by gnosygnu** [comment] 2015-10-12 05:27
This was fixed in tonight's v2.10.2 release. Thanks again for the report!

**Closed by gnosygnu** 2015-10-12 05:27 UTC
Labels: interwiki, parser

**Comment by bmihai** [comment] 2015-10-13 15:37
Thank you!

**Comment by gnosygnu** [comment] 2015-10-14 03:15
No problem. All thanks belong to you! :)
