### ISSUE TITLE
Can't get xowa to start

### ISSUE THREAD

**Issue by dankwartp** [gnosygnu/xowa#13] opened 2015-07-28 21:47 UTC
Hi,
sorry in advance whether I've got something wrong, I'm new to all this.
Trying to get xowa to start on Windows 8, with no success so far.
First, I've copied the folder to c:\programs. From the cmd windows, this is the log it gave me:

Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. Alle Rechte vorbehalten.

C:\Users\Dankwart>java -version
java version "1.8.0_51"
Java(TM) SE Runtime Environment (build 1.8.0_51-b16)
Java HotSpot(TM) Client VM (build 25.51-b03, mixed mode, sharing)

C:\Users\Dankwart>cd\

C:\>cd programme

C:\Programme>cd xowa

C:\Programme\xowa>java -Xmx256m -jar xowa_windows.jar --cmd_file xowa_build.gfs
--app_mode cmd
XOWA: the XOWA Offline Wiki Application
Copyright (c) 2012 gnosygnu@gmail.com

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

--------------------------------------------------------------------------------

version: 2.7.3.3; build date: 2015-07-21 17:34

arguments:
  [0] = '--cmd_file'
  [1] = 'xowa_build.gfs'
  [2] = '--app_mode'
  [3] = 'cmd'

[err 0] <java.io.FileNotFoundException> C:\Programme\xowa\user\anonymous\app\tmp
\log\current\session.txt (Das System kann den angegebenen Pfad nicht finden)
[err 1] <io> file not found: url=C:\Programme\xowa\user\anonymous\app\tmp\log\cu
rrent\session.txt
[trace]:
  java.io.FileOutputStream.open0(Native Method)
  java.io.FileOutputStream.open(Unknown Source)
  java.io.FileOutputStream.<init>(Unknown Source)
  java.io.FileOutputStream.<init>(Unknown Source)
  gplx.ios.IoEngine_system.SaveFilText_api(Unknown Source)
  gplx.ios.IoEngine_xrg_saveFilStr.Exec(Unknown Source)
  gplx.Io_mgr.AppendFilStr(Unknown Source)
  gplx.Usr_log_fil.Flush(Unknown Source)
  gplx.Gfo_usr_dlg__log_base.Flush(Unknown Source)
  gplx.Gfo_usr_dlg__log_base.Queue_enabled_(Unknown Source)
  gplx.xowa.Xoa_app_boot_mgr.Run_app(Unknown Source)
  gplx.xowa.Xoa_app_boot_mgr.Run(Unknown Source)
  gplx.xowa.Xoa_app_.Run(Unknown Source)
  gplx.xowa.Xowa_main.main(Unknown Source)
app launch failed: args_process [err 0] <java.io.FileNotFoundException> C:\Progr
amme\xowa\user\anonymous\app\tmp\log\current\session.txt (Das System kann den an
gegebenen Pfad nicht finden)
[err 1] <io> file not found: url=C:\Programme\xowa\user\anonymous\app\tmp\log\cu
rrent\session.txt
[trace]:
  java.io.FileOutputStream.open0(Native Method)
  java.io.FileOutputStream.open(Unknown Source)
  java.io.FileOutputStream.<init>(Unknown Source)
  java.io.FileOutputStream.<init>(Unknown Source)
  gplx.ios.IoEngine_system.SaveFilText_api(Unknown Source)
  gplx.ios.IoEngine_xrg_saveFilStr.Exec(Unknown Source)
  gplx.Io_mgr.AppendFilStr(Unknown Source)
  gplx.Gfo_usr_dlg__log_base.Log_msg(Unknown Source)
  gplx.Gfo_usr_dlg__log_base.Log_to_session(Unknown Source)
  gplx.Gfo_usr_dlg__log_base.Log_to_session_fmt(Unknown Source)
  gplx.xowa.Xoa_app_boot_mgr.Run_app(Unknown Source)
  gplx.xowa.Xoa_app_boot_mgr.Run(Unknown Source)
  gplx.xowa.Xoa_app_.Run(Unknown Source)
  gplx.xowa.Xowa_main.main(Unknown Source)

C:\Programme\xowa>

After reckoning it may be a problem with my rights, I've moved the xowa folder to c.\, and now session.txt looks like the following:

20150728_212915.982 env.init: version=2.7.3.3
20150728_212916.092 env.init: jar_url=xowa_windows.jar; build_date=2015-07-21 17:34
20150728_212916.093 env.init: op_sys=windows32
20150728_212916.106 
arguments:
  **** NONE ****
  use --help to show help

20150728_212917.076 app.init
20150728_212917.081 creating user_system_cfg.gfs: C:\xowa\user\anonymous\app\data\cfg\user_system_cfg.gfs
20150728_212917.591 db.schema.load.bgn: conn=data source=C:\xowa\user\xowa.user.anonymous.sqlite3;version=3;
20150728_212917.625 db.schema.load.end
20150728_212918.318 creating bookmarks page
20150728_212918.529 wiki.init: circular call canceled: home
20150728_212918.532 wiki.init: circular call canceled: home
20150728_212918.535 wiki.init: circular call canceled: home
20150728_212918.541 wiki.init: circular call canceled: home
20150728_212918.544 wiki.init: circular call canceled: home
20150728_212918.546 wiki.init: circular call canceled: home
20150728_212918.321 wiki.init.bgn: home
20150728_212918.568 wiki.init.end
20150728_212918.711 moving history files
20150728_212918.716 moved history files: 0
20150728_212918.774 xowa_cfg_os generated; url=C:\xowa\bin\windows\xowa\cfg\xowa_cfg_os.gfs
20150728_212918.783 gfs.done: C:\xowa\bin\windows\xowa\cfg\xowa_cfg_os.gfs
20150728_212918.822 gfs.done: C:\xowa\user\anonymous\app\data\cfg\xowa_user_cfg.gfs
20150728_212918.824 gfs.done: C:\xowa\user\anonymous\app\data\cfg\user_custom_cfg.gfs
20150728_212918.827 gfs.done: C:\xowa\xowa.gfs
20150728_212918.831 setup:checking if dir exists: version_prv= version_del=1.8.2.1 dir=C:\xowa\user\anonymous\lang\
20150728_212918.834 setup:checking if dir exists: version_prv= version_del=1.8.2.1 dir=C:\xowa\user\anonymous\wiki\#cfg\
20150728_212918.837 setup:checking if dir exists: version_prv= version_del=1.10.2.1 dir=C:\xowa\bin\any\javascript\
20150728_212918.839 setup:checking if dir exists: version_prv= version_del=1.10.2.1 dir=C:\xowa\bin\any\xowa\html\modules\
20150728_212918.858 converted options to v2
20150728_212918.842 app.upgrade.done
20150728_212918.860 wiki.init.bgn: home
20150728_212918.995 wiki.init.end
20150728_212919.300 swt.kit.init.done

xowa still doesn't start, and I have no idea why. Could you possible point me to a solution?
Thanks a lot!

**Comment by gnosygnu** [comment] 2015-07-28 22:33
Thanks for the command output!

I do agree. The 1st run is probably a permissions issue. I'm guessing this is Windows 8 related. I'll try to reproduce it later with a Windows 7 machine.

Also, part of the problem is that you're trying to run XOWA in command-line mode. Specifically this line:

> java -Xmx256m -jar xowa_windows.jar --cmd_file xowa_build.gfs --app_mode cmd

To launch the GUI, use this:

```
java -Xmx256m -jar xowa_windows.jar
```

However, this looks like what you did in the 2nd run. In that case, it runs, but seems to hang.

I've had another user say they had problems with Windows 8, but didn't give any details. You might be running across the same. I'll try to find a Windows 8 box, but unfortunately, I don't have any other ideas for now.

**Comment by dankwartp** [comment] 2015-07-29 10:15
OK, thanks. Btw and fyi, I have a 2nd Win8 machine. Can't get it to run on that one either.

**Comment by gnosygnu** [comment] 2015-07-30 04:20
Hmm... That's a bit worrisome. I'll try to set up a Windows 8 machine tomorrow or later this week. Thanks for the follow-up

**Comment by gnosygnu** [comment] 2015-07-31 03:33
Hi! Another user reported the same problem with a Windows 8 box, and was able to fix it. See: https://github.com/gnosygnu/xowa/issues/14

If you get a chance, can you try the following versions and let me know what works?:
* SWT 4.4 and XULRunner 24 (worked for bilde2910): https://drive.google.com/file/d/0B9cb52zjL2rIbUFSREloanpfcDA/view?usp=sharing
* SWT 4.5 and XULRunner 24 (not sure if it will work): https://drive.google.com/file/d/0B9cb52zjL2rINlFpREo0bExnMW8/view?usp=sharing

Let me know if you need any other info.

Thanks!

**Comment by gnosygnu** [comment] 2015-08-03 04:44
This should be fixed in tonight's v2.8.1 release. I'm going to close this ticket for now. If there are any issues, let me know, and I'll reopen. Thanks.

**Closed by gnosygnu** 2015-08-03 04:44 UTC
Labels: setup

**Comment by gnosygnu** [comment] 2015-08-10 02:40
I was able to reproduce a similar issue on a loaner Windows 8.1 (with a 32 bit JVM). I managed to fix this issue by upgrading to SWT 4.6M1.

If you get a chance, please try out the version v2.8.2: https://github.com/gnosygnu/xowa/releases

Hope it helps. Thanks.

**Comment by dankwartp** [comment] 2015-08-30 16:02
Hi,
I am in holidays now and won't find the time until the beginnning of 
october to test the fix. Please drop me a line if your fix is still 
untested at the beginning of october.
Best


Am 31.07.2015 um 05:33 schrieb gnosygnu:

**Comment by gnosygnu** [comment] 2015-08-31 03:13
No problem. Actually, I had 2 others confirm that it worked, so I think it's good.

Thanks for the offer and enjoy your holidays!
