### ISSUE TITLE
Strange Behaviour of Search Menu

### ISSUE THREAD

**Issue by XowaWilliam** [gnosygnu/xowa#54] opened 2016-04-07 09:47 UTC
Hi Mr. Gnosy.

Just noticed this small defect in the new **SEARCH** implementation.

Some words typed bring up a blank space followed by 3 dots _( ... )_ on the RHS of results output box.
In the example below, I search for **Washington** in **en.wikipedia** module.

![search](https://cloud.githubusercontent.com/assets/12995082/14347111/a31a28c6-fcb5-11e5-9777-b93969b95839.gif)

This issue is drastically exacerbated in the **en.wikibooks** module.
For example, type in the word **Book**, and you will see the 3 dots on nearly every line. 
Type in the word **Books**, and you will only see the 3 dots on every line. 

William

**Comment by gnosygnu** [comment] 2016-04-07 22:28
Hey, thanks for the screenshot. It looks like the "..." is for longer title names. For example, if you look at my screenshot below, you'll see that the first "..." is "National Register of Historic Places listings in Washington state"

That said, I don't know why it's happening. I tried this now on two separate Windows 7 machines but wasn't able to reproduce. I'll try this on a few other machines, but I'm puzzled.

A few thoughts:
* Did you upgrade using the xowa_app package or the xowa_upgrade package? If you used the xowa_app package, you should be fine. If you used the xowa_upgrade one, it might be possible that some files were missing (primarily the css for the search bar and the firefox version). This is probably unlikely, but I just want to rule it out.
* What resolution is your monitor running at? My main machine is 1600x1200 and regular font size while the other is 1920x1080 and 125% font size. Yours seems "standard" but the search box is narrower than on my machines
* Can you click on the "..."? I'm wondering if clicking on it does anything (shows the text; selects the entry)
* Until I figure out what's going on, you should use the auto-complete in the address bar, especially for wikibooks (where the titles are much longer). It works just like the one on the HTML page, except it doesn't have HTML formatting (or bold highlighting). It also allows you to customize more options: home/wiki/Options/Search_suggest

Hope this helps. Thanks.

![washington](https://cloud.githubusercontent.com/assets/4994104/14368777/f3e37004-fced-11e5-823e-2c524d673929.png)

**Comment by XowaWilliam** [comment] 2016-04-08 11:13
OK, I found the problem.

I used the latest 3.4.1.1 xowa_app package, and not the upgrade, so ruled that out.
My screen resolution was 1920 x 1080, so ruled that out.

So digging deeper I believe it is in fact the **CSS** file, and here is how I diagnosed.

I superimposed your image snapshot with mine, and found text size was identical, but your text box was about 40% wider, so I knew this was a clue.

I did a brand new installation of 3.4.1.1, with NO wiki's and NO images installed, and noticed the basic text box was similar to my image in my 1st post.
I installed **en.wikipedia.org** wiki's and image files, and opened, and on opening English Wikipedia, the Search box was wider.

Now here is where I think things went wrong:

My previous good working version of Xowa was 2.6.5.1 build date 2015-06-29 03:03 
When I tested **Washington** there, the Search box was the narrow that version.
When I employed new installation 3.4.1.1 replacing 2.6.51 , it defaulted to the old **CSS** format.

In my summary, many users who install the latest 3.4.1.1 over older versions might also experience this problem. Those who do complete new installations will not experience this problem.

So my temporary work around was as follows:
- Did brand new installation.
- Copied across all wiki data files, and image files.

After that, all wiki's opened perfectly.

Mr. Gnosy, I leave you to make final comments, and corrections where required.

**Comment by gnosygnu** [comment] 2016-04-09 02:39
Yup, you are correct! That's some pretty impressive sleuthing on your part.

Here's what I believed happened:
* XOWA uses a default CSS.
    * This CSS was downloaded in late 2014. I haven't updated it since then.
    * This CSS has the "narrow" search box.
* You imported your English Wikipedia from 2015-06.
    * When you import a wiki, you download the CSS from the Wikimedia site (or you use the XOWA default one if you don't have internet access).
    * Wherever you got it from, this 2015-06 CSS had the "narrow" search box
    * These CSS files get saved in C:\xowa\user\anonymous\wiki\en.wikipedia.org
* You downloaded English Wikipedia for 2016-03
    * XOWA reuses your CSS files if they are there. In your case, you still had CSS files from 2015-06 so XOWA just used them.
* You upgraded XOWA to v3.4.1 with an app package.
    * Your old CSS files are still being used. App packages don't replace CSS files in C:\xowa\user\anonymous\wiki\en.wikipedia.org
* You then created a new XOWA installation and moved your wikis over
    * This new installation didn't have any CSS files at C:\xowa\user\anonymous\wiki\en.wikipedia.org, so it went out and downloaded them. The new CSS files have the "wide" box.
    
Also, I recently built a new computer, so I didn't see this behavior on my main machine. I'm assuming the other machine worked because I downloaded a "wide" CSS sometime between 2015-06 and 2016-03

At any rate, here's what I'll close with:
* Your regenerated installation is completely fine. I document a similar process in home/wiki/App/Setup/Upgrading
* I'll update the default CSS so that it has the "wide" search box
* I'll change XOWA to replace old CSS with new ones. In your case, when you downloaded 2016-03, XOWA should have replaced your old CSS with the one from 2016-03. This would have automatically saved you from all the discrepancies.

Thanks again for all the legwork. I really appreciate the dedication!

**Comment by gnosygnu** [comment] 2016-04-11 05:11
Tonight's release updates the CSS for the home wiki. I confirm it is now the "wide" box, which will fix the problem encountered above.

I'm going to close this ticket. Let me know if there's anything else and I'll reopen. Thanks.

**Closed by gnosygnu** 2016-04-11 05:11 UTC
Labels: html
