### ISSUE TITLE
Problems setting up Xowa across partition <SOLVED>

### ISSUE THREAD

**Issue by mwang141** [gnosygnu/xowa#57] opened 2016-05-29 11:30 UTC
Hi,

kudos to xowa, please let me explain my system first;

1) 2 hard disks. 
disk 1: mount as rw with ubuntu 64bit , i.e. system disk
disk 2: mount as ro , ext4. i.e. data disk. all are mount as read only after data copied to it.
why I do that? to protect the data.

2) I download xowa program and install to disk 1: /home/xowa
    then I download the xowa simple wiki 1.9GB and then install disk 2: /media/disk2/xowa_wiki. 
    i.e. /media/disk2/xowa_wiki/wiki/simple.wikipedia.org. (of course, I need to mount as rw then copy      then change back to read only mode)
    then i do the following ln -s /media/disk2/xowa_wiki/wiki ~/xowa/wiki since my system disk is very small, so all data are link to data disk2.

3) then I run sh xowa64.sh.
    on the left, it did detect the 4 simple wikis. But when I click one of them I got the following error:

The file /site/simple.wikiquote.org/ cannot be found. Please check the location and try again.

[err 0] <gplx> val is not in switch/if: val=-4
[trace]:
  gplx.gfui.Swt_dlg_msg.Xto_gfui_btn(Unknown Source)
  gplx.gfui.Swt_dlg_msg.Ask(Unknown Source)
  gplx.gfui.Swt_dlg_msg.run(Unknown Source)
  org.eclipse.swt.widgets.Synchronizer.syncExec(Unknown Source)
  org.eclipse.swt.widgets.Display.syncExec(Unknown Source)
  gplx.gfui.Swt_kit.Ask_ok(Unknown Source)
  gplx.gfui.Swt_html_lnr_location.Pub_evt(Unknown Source)
  gplx.gfui.Swt_html_lnr_location.changing(Unknown Source)
  org.eclipse.swt.browser.Mozilla.sendChangingEvent(Unknown Source)
  org.eclipse.swt.browser.Mozilla.OnStartURIOpen(Unknown Source)
  org.eclipse.swt.browser.Mozilla$18.method3(Unknown Source)
  org.eclipse.swt.internal.mozilla.XPCOMObject.callback3(Unknown Source)
  org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
  org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(Unknown Source)
  org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
  gplx.gfui.Swt_kit.Kit_run(Unknown Source)
  gplx.xowa.guis.Xoa_gui_mgr.Run(Unknown Source)
  gplx.xowa.apps.boots.Xoa_boot_mgr.Run_app(Unknown Source)
  gplx.xowa.apps.boots.Xoa_boot_mgr.Run(Unknown Source)
  gplx.xowa.Xoa_app_.Run(Unknown Source)
  gplx.xowa.Xowa_main.main(Unknown Source)

Please let me know what did I do wrong, thanks.

**Comment by mwang141** [comment] 2016-05-29 12:11
i set disk2 to read and write, now the error window/message gone, seems java is running something, as there are new files being generated under the wiki tree e.g. simple.wikibooks.org-file-user.xowa I guess
that is what you mean by processing time. wonder if it necessary to process it at user's end? anything specific? what is the use of it? can we download it and modify some parameters in some setup file for individual config?

**Comment by gnosygnu** [comment] 2016-05-29 12:28
Hi! Thanks for the detailed report!

XOWA assumes a writable disk for the wikis for the following reaons:
* Editing wikitext (click on the Edit link near the top-right)
* Saving full-scale images (click on any image and then click again on the full-resolution to download the original image)
* Saving images in general (user doesn't have any image databases and views a page; XOWA downloads theses images and saves them a dabase)

The 2nd and 3rd points are causing the problem here. XOWA needs the "*-file.user.xowa" database to save the images. If one doesn't exist for a wiki, it tries to create them.

I thought I fixed this in v3.5.1.1 . I ignored this error because of Android. See https://github.com/gnosygnu/xowa/blob/master/400_xowa/src/gplx/fsdb/Fsdb_db_mgr_.java#L53 .

Would you confirm that you are using v3.5.1.1? If you are, then I'll try to reproduce here on my side.

In the meantime, for a read-only situation, you should be able to either:
* Copy a -file.user.xowa database from any wiki and just rename it. For example, for simple.wikiquote.org, copy "simple.wikipedia.org-file.user.xowa" and rename it to "simple.wikiquote.org-file.user.xowa"
* Open the wiki once and have XOWA create it automatically for you

Hope this helps.

**Comment by mwang141** [comment] 2016-05-29 15:23
thanks. I tried again.

0) environment Linux linuxmint 3.13.0-37-generic #64-Ubuntu SMP  x86_64 x86_64 x86_64 GNU/Linux
1) data : xowa_app_linux_64_v3.5.1.1 , simplewiki Xowa_simplebundle_2015-04-17 1.9G.
2) all unzip to /tmp/xowa (tmpfs /tmp tmpfs defaults,noatime,mode=1777,nosuid,size=10240M 0 0) large RAM disk..
3) open xowa -> click simple wikibooks -> bottom status bar showing downloading some files...
4) DONE. no error. working. 

thanks. please close this ticket. thanks.

**Comment by gnosygnu** [comment] 2016-05-29 19:23
Great! It sounds like v3.5.1. made the difference.

I'm not sure why (7) takes a long time. Are you saying the symlinked (ln -s) setup takes a long time to open the wiki the first time? Or every page? In either case, there really shouldn't be any noticeable difference.

If you want to investigate further, please send me the log file at home/wiki/Special:XowaSystemData?type=log_session . Or /xowa/user/anonymous/app/tmp/log/current/session.txt . The log file has timestamps, so the delay should be noticeable therein.

Thanks!

**Comment by gnosygnu** [comment] 2016-06-20 05:04
I'm going to mark this ticket closed as it looks like v3.5.1 made a difference. Let me know if there's anything else. Thanks.

**Closed by gnosygnu** 2016-06-20 05:04 UTC
Labels: linux, setup
