### ISSUE TITLE
Search Issue

### ISSUE THREAD

**Issue by Ope30** [gnosygnu/xowa#65] opened 2016-07-03 18:46 UTC
When I search something, for example "Leonardo Da Vinci", I get a "error during search" message after using the space key, nor does it show the Table of Contents. This is because I decided to get the newest version, I then cut my current Wiki into the newer folder, the newer one with the current version. What is causing this? Is it because I cut it?

**Comment by gnosygnu** [comment] 2016-07-03 19:07
Hi! Thanks for the report!

I was able to reproduce the font issue. This is a bug that should be fixed for tonight's release.

In the meantime, you can set the size manually.
* Go to home/wiki/Options/HTML
* Change Font size to a number like 25
* Click "Save" (near the upper left hand corner)
* Restart XOWA.

I tried to reproduce the search, but wasn't able to, see the image below.

I'm guessing you mean you moved your English Wikipedia files into a new folder with the new version? This is perfectly fine, but you should make sure all the files are there. You need three files for search:

* en.wikipedia.org-xtn.search.core.xowa
* en.wikipedia.org-xtn.search.link-title-ns.000-db.001.xowa
* en.wikipedia.org-xtn.search.link-title-ns.999-db.001.xowa

You can check it in Explorer. You can also go to this URL within XOWA: en.wikipedia.org/wiki/Special:XowaDiag?type=fs.check&wiki=en.wikipedia.org

If you have these files, can you do the following:
* Try searching for "Leonardo Da Vinci" again
* If it fails, go to home/wiki/Special:XowaSystemData?type=log_session
* Copy the log and paste it here

Hope this helps. Thanks!



![leonardo_da_vinci](https://cloud.githubusercontent.com/assets/4994104/16547077/c0d78f9e-412e-11e6-992e-24907a676a3d.png)

**Comment by Ope30** [comment] 2016-07-03 19:30
Yeah, I moved them into the new folder. I also made sure that those files, that you listed, are there.
They're there. Doesn't matter which Wiki I use, the same problem occurs.
Anyways, here's the log:

20160703_192818.450 term:log_wtr
20160703_192818.451 term:log_mgr
20160703_192818.465 term:wiki_mgr
20160703_192818.485 swt.kit.term:bgn
20160703_192818.485 swt.kit.term:cursor
20160703_192831.311 env.init: version=3.6.4.2
20160703_192831.344 env.init: jar_url=xowa_windows.jar; build_date=2016-06-27 13:16
20160703_192831.344 env.init: op_sys=windows32
20160703_192831.346 
arguments:
  **** NONE ****
  use --help to show help

20160703_192831.659 addons.init: xowa.builds.images
20160703_192831.659 addons.init: xowa.builds.pagelinks
20160703_192831.659 addons.init: xowa.builds.utils_rankings
20160703_192831.660 addons.init: xowa.builds.search
20160703_192831.660 addons.init: xowa.updates.files
20160703_192831.660 addons.init: xowa.builds.htmls
20160703_192831.660 addons.init: xowa.builds.repacks
20160703_192831.660 addons.init: xowa.builds.randoms
20160703_192831.661 addons.init: xowa.apps.wikis.registrys
20160703_192831.661 addons.init: xowa.apps.file_browsers
20160703_192831.661 addons.init: xowa.imports.downloads
20160703_192831.661 addons.init: xowa.apps.helps.logs
20160703_192831.704 app.init
20160703_192831.916 db.schema.load.bgn: conn=data source=D:\XOWA TEST\user\xowa.user.anonymous.sqlite3;version=3;
20160703_192832.156 gfs.done: D:\XOWA TEST\bin\windows\xowa\cfg\xowa_cfg_os.gfs
20160703_192832.177 gfs.done: D:\XOWA TEST\user\anonymous\app\data\cfg\xowa_user_cfg.gfs
20160703_192832.178 gfs.done: D:\XOWA TEST\user\anonymous\app\data\cfg\user_custom_cfg.gfs
20160703_192832.178 gfs.done: D:\XOWA TEST\bin\any\xowa\cfg\app\xowa.gfs
20160703_192832.182 wiki.db_core.v2: url=D:\XOWA TEST\bin\any\xowa\wiki\home\home.xowa
20160703_192832.201 fsdb.db_core.v2: type=all url=D:\XOWA TEST\bin\any\xowa\wiki\home\home.xowa
20160703_192832.214 db.schema.load.bgn: conn=data source=D:\XOWA TEST\bin\any\xowa\wiki\home\home.xowa;version=3;
20160703_192832.180 app.upgrade.done
20160703_192832.181 wiki.init.bgn: home
20160703_192832.293 wiki.init.end
20160703_192832.428 site_cfg loaded; wiki=home itm=extensiontags tid=itm
20160703_192832.535 site_cfg loaded; wiki=home itm=interwikimap tid=itm
20160703_192832.640 swt.kit.init.done
20160703_192833.157 wiki.db_core.v2: url=D:\XOWA TEST\wiki\de.wikipedia.org\de.wikipedia.org-core.xowa
20160703_192833.164 fsdb.db_core.v2: type=lot url=D:\XOWA TEST\wiki\de.wikipedia.org\de.wikipedia.org-file-core.xowa
20160703_192833.172 db.schema.load.bgn: conn=data source=D:\XOWA TEST\wiki\de.wikipedia.org\de.wikipedia.org-core.xowa;version=3;
20160703_192833.079 app.gui.kit_init.done
20160703_192833.138 app.gui.win_load.done
20160703_192833.139 app.launch.page.bgn
20160703_192833.143 wiki.init.bgn: de.wikipedia.org
20160703_192833.182 wiki.init.end
20160703_192833.183 site_cfg loaded; wiki=de.wikipedia.org itm=extensiontags tid=cfg
20160703_192833.184 site_cfg loaded; wiki=de.wikipedia.org itm=interwikimap tid=cfg
20160703_192833.432 page.load: url=de.wikipedia.org/wiki/Wikipedia:Hauptseite
20160703_192833.432 app.launch.page.end
20160703_192833.821 wiki.init.bgn: www.wikidata.org
20160703_192833.827 wiki.init.end
20160703_192833.866 page.async: url=de.wikipedia.org/wiki/Wikipedia:Hauptseite
20160703_192834.102 file.get: file=P_countries-lightblue.png width=30 page=Wikipedia:Hauptseite
20160703_192834.104 file.get: file=P_history-lightblue.png width=30 page=Wikipedia:Hauptseite
20160703_192834.105 file.get: file=P_social_sciences-lightblue.png width=30 page=Wikipedia:Hauptseite
20160703_192834.106 file.get: file=P_art-lightblue.png width=30 page=Wikipedia:Hauptseite
20160703_192834.108 file.get: file=P_religion-lightblue.png width=30 page=Wikipedia:Hauptseite
20160703_192834.109 file.get: file=P_sport-lightblue.png width=30 page=Wikipedia:Hauptseite
20160703_192834.110 file.get: file=P_transport-lightblue.png width=30 page=Wikipedia:Hauptseite
20160703_192834.112 file.get: file=P_ps-lightblue.png width=30 page=Wikipedia:Hauptseite
20160703_192834.113 file.get: file=Temesvar_1890er-Jahre_I.JPG width=159 page=Wikipedia:Hauptseite
20160703_192834.114 file.get: file=Feed-icon.svg width=12 page=Wikipedia:Hauptseite
20160703_192834.116 file.get: file=Duble_herma_of_Socrates_and_Seneca_Antikensammlung_Berlin_07.jpg width=88 page=Wikipedia:Hauptseite
20160703_192834.121 file.get: file=Feed-icon.svg width=12 page=Wikipedia:Hauptseite
20160703_192834.122 file.get: file=Sigmundur_Davíð_Gunnlaugssonin_Oct,_2014.jpg width=87 page=Wikipedia:Hauptseite
20160703_192834.124 file.get: file=Kiel_HWDW_IMG_3697_cropped.jpg width=128 page=Wikipedia:Hauptseite
20160703_192834.125 file.get: file=Wikimedia_Community_Logo.svg width=20 page=Wikipedia:Hauptseite
20160703_192834.126 file.get: file=Commons-logo.svg width=18 page=Wikipedia:Hauptseite
20160703_192834.127 file.get: file=Wiktionary_small.svg width=20 page=Wikipedia:Hauptseite
20160703_192834.129 file.get: file=Wikibooks-logo.svg width=21 page=Wikipedia:Hauptseite
20160703_192834.130 file.get: file=Wikiquote-logo.svg width=20 page=Wikipedia:Hauptseite
20160703_192834.131 file.get: file=Wikiversity-logo.svg width=20 page=Wikipedia:Hauptseite
20160703_192834.132 file.get: file=Wikisource-logo.svg width=20 page=Wikipedia:Hauptseite
20160703_192834.133 file.get: file=Wikinews-logo.svg width=26 page=Wikipedia:Hauptseite
20160703_192834.135 file.get: file=Wikidata-logo.svg width=20 page=Wikipedia:Hauptseite
20160703_192834.138 file.get: file=Wikivoyage-Logo-v3-icon.svg width=20 page=Wikipedia:Hauptseite
20160703_192834.140 redlink.redlink_bgn: page=Wikipedia:Hauptseite total_links=71
20160703_192834.152 redlink.redlink_end: redlinks_run=0
20160703_192836.142 db.schema.load.bgn: conn=data source=D:\XOWA TEST\wiki\de.wikipedia.org\de.wikipedia.org-xtn.search.core.xowa;version=3;
20160703_192836.153 addons.init: xowa.apps.search

**Comment by gnosygnu** [comment] 2016-07-03 22:36
Thanks for the log. Unfortunately it doesn't reveal anything.

I tried to reproduce on a WIndows 32 bit system with German Wikipedia. It also worked fine.

I'm going to add some logging statements to tonight's build. If you can, please bring it down and try again. Regardless of whether or not it fails, it should at least show more information in the logs

Also, with regards to the font issue, I just want to verify it only occurs when you hold Ctrl and Mouse Wheel Up or Down. If you choose Menu -> View -> Increase Font Size, it should automatically save.

Regardless, tonight's release will auto-save Ctrl and Mouse Wheel Up or Down

**Comment by XowaWilliam** [comment] 2016-07-04 02:56
I just made a comment on same search issue in [https://github.com/gnosygnu/xowa/issues/64](url)

**Comment by gnosygnu** [comment] 2016-07-04 03:36
@XowaWilliam  Thanks for the screenshot in the other issue. It helped a lot. I'm going to release a fix for this in the next 30 minutes or so. I'll comment again here when done.

**Comment by gnosygnu** [comment] 2016-07-04 04:05
@Ope30 I commented in #64, but I'll repeat it here too

Basically, I broke multiple word search in v3.6.3+ because of some tweaks to the Search algorithm. I never noticed on my machine because it only affected old wikis (2016-05 and earlier). All the wikis on my machines were new ones (2016-06 and up)

I release v3.7.1.2 tonight to handle the issue: https://github.com/gnosygnu/xowa/releases/tag/v3.7.1.2 . Please give it a try; it should resolve the issue.

Thanks!

**Comment by Ope30** [comment] 2016-07-04 11:43
It fixed the issue, thank you very much! As well as William, for making it more clear than I did.

Unfortunately, I have a problem with the Table of Contents, it doesn't appear in any articles. There's also one more thing I noticed ( that may be me, but who knows), that if you're clicking on a image, to get a bigger view of it, and you go back (One Page Back), every image of the article will lose its display until you refresh the page.
Edit: I've noticed that you get the Table of Contents once you refresh the page.

**Comment by gnosygnu** [comment] 2016-07-04 17:46
> It fixed the issue, thank you very much! As well as William, for making it more clear than I did.

No problem! Thanks for confirming! Your original error report was clear; I just needed the error message to pinpoint the problem.

> Unfortunately, I have a problem with the Table of Contents, it doesn't appear in any article

Yeah, I know, this is a known issue for users who have HTML databases.

If you want a TOC, you can force XOWA to use the Wikitext databases only:
* Go to home/wiki/Options/HTML_databases
* Uncheck "Prefer HTML databases for Read tab"
* Click "Save"

This will force XOWA to :
* Read the wikitext
* Parse the wikitext to generate HTML
* Show the HTML

In contrast, having it checked will
* Read pre-generated HTML
* Show the HTML

The latter will be much faster. It's what I use for XOWA Android. However, because the latter is more recent, it still needs a few more functions (like TOC)

> if you're clicking on a image, to get a bigger view of it, and you go back (One Page Back), every image of the article will lose its display until you refresh the page.

Okay. I'm able to reproduce that. I must have broken it with the HTML databases. I'll get a fix for next week's release. Maybe even a mid-week patch release. I'll post here again with info later. Thanks!

**Comment by gnosygnu** [comment] 2016-07-05 02:20
So, I looked at it more, and the TOC fix will only work for 2016-07 English Wikipedia HTML databases and beyond

For your purposes, the easiest thing to do is to use the Wikitext databases. As I said above, just do this:
* Go to home/wiki/Options/HTML_databases
* Uncheck "Prefer HTML databases for Read tab"
* Click "Save"

This will solve both these issues:
* The TOC will display all the time
* Clicking and going back won't lose images

The main drawback is that the Wikitext databases load slower than the HTML ones.

Hope this makes sense. Let me know if there's anything else. Thanks again for the initial report.

**Comment by Ope30** [comment] 2016-07-05 11:27
Yeah, that fixed it for me. I'll update my current Wiki anyway once I have more space. If I encounter any bugs I'll post them here if that's okay. Thanks!

**Comment by gnosygnu** [comment] 2016-07-06 00:47
Cool. Glad to hear the news.

I'll make the other two changes for this week's release. (Note that you'll need 2016-07 English Wikipedia for the TOC). Once that's done, I'll close this ticket.

Let me know if there's anything else. Thanks!

**Comment by gnosygnu** [comment] 2016-07-11 04:30
v3.7.2.1 resolves both the issues from above for HTML databases:

* TOC now displays all the time. Note that this will only apply to 2016-07 wikis and beyond
* Clicking on a link and going back will still show images

I'm going to mark this ticket closed for now. Let me know if I missed anything and I'll reopen. Thanks

**Closed by gnosygnu** 2016-07-11 04:30 UTC
Labels: resolved, search
