### ISSUE TITLE
Luaj: Empty captures ("anypos" or "()") should be base-1, not base-0 (Module:ja-ruby:624 Can not match ...)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#726] opened 2020-05-16 06:56 UTC
I have just finished rebuilding 2020-05-01 enwiktionary and the log file contains many of these errors

To take a specific example `en.wiktionary.org/wiki/仰`
Generates a number of these errors

Within this page is the wikitext `{{ja-r|仰%臥|ぎょう%が}}` which demonstrates the error

I have tracked this down to some logic in Module:ja-ruby
Line 574:

    mw.ustring.gsub(plain_term_noxml, '()['..pat_kanji_probable..pat_rubiable_probable..']+()', function(pos1, pos2)
Note that the call to gsub includes a function as the third parameter, and that this function takes two arguments (pos1, pos2)

If immediately after this line I place the dbg statement

    dbg(pos0, pos1, pos2)

and 'run' the preview for the oneliner above I get values `1 0 1` for the dbg statement

However, if in a 'real' enwiktionary module sandbox, I try the same logic (with the same display of values - but using mw.logObject) the values I get there are `1 1 2`

This suggests an off-by-one issue to me

If immediately after the dbg line I add

    pos1 = pos1 + 1
    pos2 = pos2 + 1

It kind of works (that is, the error does not occur but the display is not quite right)
I suspect that there are other uses of this same functionality I have not 'corrected'

**Comment by gnosygnu** [comment] 2020-05-16 21:10
Great breakdown! Thanks for the well written detail. Will comment more tomorrow, but brief comment. Am able to reproduce with below. Will triage tomorrow

Thanks again!

https://en.wikipedia.org/wiki/Module:Sandbox/Gnosygnu

```
function p.test_726()
--    mw.ustring.gsub("仰", "()[仰]+()", function(pos1, pos2)
    mw.ustring.gsub("a", "()[a]+()", function(pos1, pos2)
        mw.log(pos1);
        mw.log(pos2);
    end)
end
```

**Comment by gnosygnu** [comment] 2020-05-17 02:45
I think I have a fix for this. 

Basically change:
* fail: `? (Object)grp.Bgn()`
* pass: `? (Object)(grp.Bgn() + 1)`

Code locations is here: https://github.com/gnosygnu/xowa/blob/f860edf064cc9c868a20b3540cdd94a9f353d6f8/400_xowa/src/gplx/xowa/xtns/scribunto/libs/Scrib_lib_ustring_gsub_mgr.java#L181

Will review in morning, and add an official commit (with comment / test)

**Comment by gnosygnu** [comment] 2020-05-17 15:32
Thanks again for the well-written detail. I know these are difficult to track down, and finding the problem code-line is often more time-consuming than the actual fix itself. Nice work!

As it turns out, this was a 1-line fix similar to the above. However, I did make the following changes
* In LuaJ, add an assertion that `anypos` values should always be captured (basically, anytime `()` ("anypos") is called, make sure the values are captured)
* In XOWA / LuaJ, add a lot more documentation about why this is necessary. (See https://github.com/gnosygnu/xowa/issues/502#issuecomment-507068061, but can also expound below if needed)

Let me know if anything else. And let me say once again (for it can never be said enough), thanks!

**Comment by desb42** [comment] 2020-05-25 08:14
Not sure if completely fixed (or another issue)

Have just built enwiktionary (2020-05-01) with latest luaj fixes and have got 5 lines with the original issue - `Module:ja-ruby:624 Can not match`

The pages are:

    菩薩
    𠮟
    𦻙
    𪐷
    𨋳

**Comment by gnosygnu** [comment] 2020-05-31 05:22
Thanks for the extra report. Took a while to track down, but made 2 changes to fix the above pages. Both related to string-extraction on BMP strings.

Moving back to done. Let me know if anything else.

Thanks again!

**Closed** 2020-06-05 12:38 UTC
Labels: [effort 4 - less than a day], [priority 1 - critical], [resolved - commit], [risk 2 - major], [schedule 1 - within days], [type - bug], core - parser, xtn - lua
