### ISSUE TITLE
Stack trace error in de.wikipedia.org/wiki/Vorlage:Lang/Doku

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#330] opened 2019-01-14 16:47 UTC
on an initial start of xowa (gui or http_server) selecting the page de.wikipedia.org/wiki/Vorlage:Lang/Doku the following error

    20190114_163824.615 error while executing script: err=[err 0] <gplx> counts do not match: hash=3 list=4
    [trace]:
      gplx.Ordered_hash_base.AssertCounts(Ordered_hash_base.java:66)
      gplx.Ordered_hash_base.Add_base(Ordered_hash_base.java:24)
      gplx.core.lists.Hash_adp_base.Add_as_key_and_val(Hash_adp_base.java:23)
      gplx.xowa.langs.Xol_lang_itm.Fallback_bry_(Xol_lang_itm.java:63)
      gplx.xowa.langs.Xol_lang_itm.Exec_fallback_load(Xol_lang_itm.java:136)
      gplx.xowa.langs.Xol_lang_itm.Invk(Xol_lang_itm.java:104)
      gplx.langs.gfs.GfsCore_.Exec(GfsCore_.java:22)
      gplx.langs.gfs.GfsCore_.Exec(GfsCore_.java:50)
      gplx.langs.gfs.GfsCore.ExecOne_to(GfsCore.java:35)
      gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_str_for(Xoa_gfs_mgr.java:54)
      gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_str_for(Xoa_gfs_mgr.java:47)
      gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_url_for(Xoa_gfs_mgr.java:44)
      gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_url_for(Xoa_gfs_mgr.java:32)
      gplx.xowa.langs.Xol_lang_itm.Load_lang(Xol_lang_itm.java:145)
      gplx.xowa.langs.Xol_lang_itm.Exec_fallback_load(Xol_lang_itm.java:140)
      gplx.xowa.langs.Xol_lang_itm.Invk(Xol_lang_itm.java:104)
      gplx.langs.gfs.GfsCore_.Exec(GfsCore_.java:22)
      gplx.langs.gfs.GfsCore_.Exec(GfsCore_.java:50)
      gplx.langs.gfs.GfsCore.ExecOne_to(GfsCore.java:35)
      gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_str_for(Xoa_gfs_mgr.java:54)
      gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_str_for(Xoa_gfs_mgr.java:47)
      gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_url_for(Xoa_gfs_mgr.java:44)
      gplx.xowa.apps.gfs.Xoa_gfs_mgr.Run_url_for(Xoa_gfs_mgr.java:32)
      gplx.xowa.langs.Xol_lang_itm.Load_lang(Xol_lang_itm.java:145)
      gplx.xowa.langs.Xol_lang_itm.Init_by_load(Xol_lang_itm.java:130)
      gplx.xowa.langs.Xol_lang_itm.Init_by_load_assert(Xol_lang_itm.java:122)
      gplx.xowa.langs.Xoa_lang_mgr.Get_by_or_load(Xoa_lang_mgr.java:38)
      gplx.xowa.xtns.scribunto.libs.Scrib_lib_language.lang_(Scrib_lib_language.java:264)
      gplx.xowa.xtns.scribunto.libs.Scrib_lib_language.IsRTL(Scrib_lib_language.java:259)
      gplx.xowa.xtns.scribunto.libs.Scrib_lib_language.Procs_exec(Scrib_lib_language.java:55)
      gplx.xowa.xtns.scribunto.procs.Scrib_proc.Proc_exec(Scrib_proc.java:29)
      gplx.xowa.xtns.scribunto.engines.luaj.Luaj_engine.Server_recv_call(Luaj_engine.java:93)
      gplx.xowa.xtns.scribunto.engines.luaj.Luaj_server_func_recv.call(Luaj_server_func_recv.java:27)
      org.luaj.vm2.lib.OneArgFunction.invoke(Unknown Source)
      org.luaj.vm2.LuaValue.onInvoke(Unknown Source)
      org.luaj.vm2.TailcallVarargs.eval(Unknown Source)
      org.luaj.vm2.TailcallVarargs.arg1(Unknown Source)
      org.luaj.vm2.LuaClosure.call(Unknown Source)
      org.luaj.vm2.LuaClosure.execute(Unknown Source)
      org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
      org.luaj.vm2.TailcallVarargs.eval(Unknown Source)
      org.luaj.vm2.TailcallVarargs.arg1(Unknown Source)
      org.luaj.vm2.LuaClosure.call(Unknown Source)
      org.luaj.vm2.LuaClosure.execute(Unknown Source)
      org.luaj.vm2.LuaClosure.call(Unknown Source)
      org.luaj.vm2.LuaClosure.execute(Unknown Source)
      org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
      org.luaj.vm2.LuaClosure.invoke(Unknown Source)
      org.luaj.vm2.LuaClosure.execute(Unknown Source)
      org.luaj.vm2.LuaClosure.call(Unknown Source)
      org.luaj.vm2.LuaClosure.execute(Unknown Source)
      org.luaj.vm2.LuaClosure.call(Unknown Source)
      org.luaj.vm2.LuaClosure.execute(Unknown Source)
      org.luaj.vm2.LuaClosure.call(Unknown Source)
      org.luaj.vm2.LuaClosure.execute(Unknown Source)
      org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
      org.luaj.vm2.LuaClosure.invoke(Unknown Source)
      org.luaj.vm2.lib.BaseLib$pcall.invoke(Unknown Source)
      org.luaj.vm2.LuaClosure.execute(Unknown Source)
      org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
      org.luaj.vm2.TailcallVarargs.eval(Unknown Source)
      org.luaj.vm2.LuaClosure.invoke(Unknown Source)
      org.luaj.vm2.LuaClosure.execute(Unknown Source)
      org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
      org.luaj.vm2.TailcallVarargs.eval(Unknown Source)
      org.luaj.vm2.LuaClosure.invoke(Unknown Source)
      org.luaj.vm2.lib.BaseLib$xpcall.invoke(Unknown Source)
      org.luaj.vm2.LuaClosure.execute(Unknown Source)
      org.luaj.vm2.LuaClosure.onInvoke(Unknown Source)
      org.luaj.vm2.TailcallVarargs.eval(Unknown Source)
      org.luaj.vm2.TailcallVarargs.arg1(Unknown Source)
      org.luaj.vm2.LuaClosure.call(Unknown Source)
      org.luaj.vm2.LuaValue.method(Unknown Source)
      gplx.xowa.xtns.scribunto.engines.luaj.Luaj_server.Dispatch(Luaj_server.java:45)
      gplx.xowa.xtns.scribunto.engines.luaj.Luaj_engine.Dispatch_as_kv_ary(Luaj_engine.java:72)
      gplx.xowa.xtns.scribunto.engines.luaj.Luaj_engine.CallFunction(Luaj_engine.java:59)
      gplx.xowa.xtns.scribunto.Scrib_core.Invoke(Scrib_core.java:182)
      gplx.xowa.xtns.scribunto.Scrib_invoke_func.Func_evaluate(Scrib_invoke_func.java:60)
      gplx.xowa.parsers.tmpls.Xot_invk_tkn_.Eval_func(Xot_invk_tkn_.java:30)
      gplx.xowa.parsers.tmpls.Xot_invk_tkn.Tmpl_evaluate(Xot_invk_tkn.java:258)
      gplx.xowa.parsers.tmpls.Xot_defn_tmpl.Tmpl_evaluate(Xot_defn_tmpl.java:86)
      gplx.xowa.parsers.tmpls.Xot_invk_tkn.Tmpl_evaluate(Xot_invk_tkn.java:288)
      gplx.xowa.parsers.tmpls.Xot_tmpl_wtr.Write_tkn(Xot_tmpl_wtr.java:101)
      gplx.xowa.parsers.tmpls.Xot_tmpl_wtr.Write_tkn(Xot_tmpl_wtr.java:33)
      gplx.xowa.parsers.tmpls.Xot_tmpl_wtr.Write_all(Xot_tmpl_wtr.java:22)
      gplx.xowa.parsers.Xop_parser.Expand_tmpl(Xop_parser.java:50)
      gplx.xowa.parsers.Xop_parser.Expand_tmpl(Xop_parser.java:44)
      gplx.xowa.parsers.Xop_parser.Parse_text_to_wdom(Xop_parser.java:102)
      gplx.xowa.parsers.Xow_parser_mgr.Parse(Xow_parser_mgr.java:98)
      gplx.xowa.wikis.pages.Xowe_page_mgr.Load_page(Xowe_page_mgr.java:91)
      gplx.xowa.apps.servers.http.Http_server_mgr.Parse_page_to_html(Http_server_mgr.java:128)
      gplx.xowa.apps.servers.http.Http_server_wkr.Write_wiki(Http_server_wkr.java:111)
      gplx.xowa.apps.servers.http.Http_server_wkr.Process_get(Http_server_wkr.java:82)
      gplx.xowa.apps.servers.http.Http_server_wkr.Run(Http_server_wkr.java:60)
      gplx.xowa.apps.servers.http.Http_server_wkr.Invk(Http_server_wkr.java:282)
      gplx.Gfo_invk_.Invk_by_msg(Gfo_invk_.java:34)
      gplx.core.threads.Thread_adp.run(Thread_adp.java:33)
      java.lang.Thread.run(Thread.java:748)
On examination of this I believe the error is due to a circular reference in the language gfs files
That is, pt.gfs contains the line `.fallback_load('pt-br')` and pt-br.gfs also contains this line
Removing the line from pt.gfs seems to resolve this issue

**Comment by gnosygnu** [comment] 2019-01-15 11:44
Hmm... I couldn't reproduce this either. See my repro steps below.

The fallback_load can generate circular references, but XOWA has code to handle this. It's possible that XOWA may be missing it for some reason.

Let me look at this more later as well as figure out why I can't reproduce. Thanks.

----

* Launch XOWA in GUI mode
* Close all tabs
* Load de.wikipedia.org/wiki/Vorlage:Lang/Doku 
* Close XOWA
* Launch XOWA in GUI mode
* de.wikipedia.org/wiki/Vorlage:Lang/Doku  loads automatically
* Checked de.wikipedia.org/wiki/Spezial:XowaSystemData?type=log_session and no errors

**Comment by desb42** [comment] 2019-01-16 13:59
That is unfortunate.
It is so difficult if it cannot be reproduced
I suspect that our code bases are diverging (I know mine is)
Have you got a timeframe for your next release?
When that happens I think that is the point to revisit the two unrepeatable issues (so far)

**Comment by desb42** [comment] 2019-01-21 15:57
I have just rebuilt xowa_dev.jar (notes from #335)
Even with this the issue here is reproduced
The logs from the session are: 
[20190121_154159.794.zip](https://github.com/gnosygnu/xowa/files/2779571/20190121_154159.794.zip)

**Comment by gnosygnu** [comment] 2019-01-23 04:42
Thanks for the upload. So, I think you're right that there may be some sort of code problem (probably adding the same language twice in Fallback_bry_)

However, I'm a bit puzzled by the log. It looks like your wikidatawiki and dewiki are incomplete. Specifically, it seems that you're missing a lot of the text databases in the 000 namespace.

When you get a chance, can you go to the following urls?
* home/wiki/Special:XowaDiag?type=fs.check&wiki=www.wikidata.org
* home/wiki/Special:XowaDiag?type=fs.check&wiki=de.wikipedia.org

You can compare against my sample below.

Thanks.

---

```
scanning: C:\xowa\wiki\www.wikidata.org\
fil|www.wikidata.org-core.wbase.xowa|6241837056|20190113 170042.640
fil|www.wikidata.org-core.xowa|4815400960|20190113 171146.696
fil|www.wikidata.org-file-core.xowa|57344|20190113 170200.665
fil|www.wikidata.org-file-user.xowa|57344|20190113 170200.669
fil|www.wikidata.org-text-ns.000-db.002.xowa|1967067136|20190113 170239.706
fil|www.wikidata.org-text-ns.000-db.003.xowa|2048626688|20190113 170244.762
fil|www.wikidata.org-text-ns.000-db.004.xowa|2127896576|20190113 170249.786
fil|www.wikidata.org-text-ns.000-db.005.xowa|2112032768|20190113 170254.950
fil|www.wikidata.org-text-ns.000-db.006.xowa|2124963840|20190113 170300.174
fil|www.wikidata.org-text-ns.000-db.007.xowa|2112184320|20190113 170309.558
fil|www.wikidata.org-text-ns.000-db.008.xowa|2125627392|20190113 170314.767
fil|www.wikidata.org-text-ns.000-db.009.xowa|2076205056|20190113 170319.823
fil|www.wikidata.org-text-ns.000-db.010.xowa|2280185856|20190113 170324.871
fil|www.wikidata.org-text-ns.000-db.011.xowa|2312888320|20190113 170329.927
fil|www.wikidata.org-text-ns.000-db.012.xowa|2041102336|20190113 170335.231
fil|www.wikidata.org-text-ns.000-db.013.xowa|2082865152|20190113 170345.063
fil|www.wikidata.org-text-ns.000-db.014.xowa|2117017600|20190113 170350.731
fil|www.wikidata.org-text-ns.000-db.015.xowa|2101448704|20190113 170355.947
fil|www.wikidata.org-text-ns.000-db.016.xowa|2361319424|20190113 170401.131
fil|www.wikidata.org-text-ns.000-db.017.xowa|2082508800|20190113 170406.620
fil|www.wikidata.org-text-ns.000-db.018.xowa|2066173952|20190113 170412.128
fil|www.wikidata.org-text-ns.000-db.019.xowa|2058776576|20190113 170418.068
fil|www.wikidata.org-text-ns.000-db.020.xowa|2158624768|20190113 170423.832
fil|www.wikidata.org-text-ns.000-db.021.xowa|2034368512|20190113 170433.476
fil|www.wikidata.org-text-ns.000-db.022.xowa|2188390400|20190113 170438.780
fil|www.wikidata.org-text-ns.000-db.023.xowa|2091167744|20190113 170443.992
fil|www.wikidata.org-text-ns.000-db.024.xowa|1967276032|20190113 170449.008
fil|www.wikidata.org-text-ns.000-db.025.xowa|2422337536|20190113 170454.496
fil|www.wikidata.org-text-ns.000-db.026.xowa|1935097856|20190113 170459.737
fil|www.wikidata.org-text-ns.000-db.027.xowa|2000330752|20190113 170504.757
fil|www.wikidata.org-text-ns.000-db.028.xowa|1943924736|20190113 170509.657
fil|www.wikidata.org-text-ns.000-db.029.xowa|2084155392|20190113 170515.025
fil|www.wikidata.org-text-ns.000-db.030.xowa|2004606976|20190113 170520.149
fil|www.wikidata.org-text-ns.000-db.031.xowa|1999441920|20190113 170525.057
fil|www.wikidata.org-text-ns.000-db.032.xowa|1982038016|20190113 170530.489
fil|www.wikidata.org-text-ns.000-db.033.xowa|1960345600|20190113 170535.837
fil|www.wikidata.org-text-ns.000-db.034.xowa|1948049408|20190113 170540.593
fil|www.wikidata.org-text-ns.000-db.035.xowa|1873264640|20190113 170545.257
fil|www.wikidata.org-text-ns.000-db.036.xowa|1910407168|20190113 170549.945
fil|www.wikidata.org-text-ns.000-db.037.xowa|1907236864|20190113 170554.714
fil|www.wikidata.org-text-ns.000-db.038.xowa|1877409792|20190113 170559.462
fil|www.wikidata.org-text-ns.000-db.039.xowa|1880576000|20190113 170604.190
fil|www.wikidata.org-text-ns.000-db.040.xowa|1881886720|20190113 170608.838
fil|www.wikidata.org-text-ns.000-db.041.xowa|1902395392|20190113 170613.510
fil|www.wikidata.org-text-ns.000-db.042.xowa|1881759744|20190113 170618.162
fil|www.wikidata.org-text-ns.000-db.043.xowa|1835323392|20190113 170622.846
fil|www.wikidata.org-text-ns.000-db.044.xowa|1832439808|20190113 170627.506
fil|www.wikidata.org-text-ns.000-db.045.xowa|2008412160|20190113 170632.394
fil|www.wikidata.org-text-ns.000-db.046.xowa|1996050432|20190113 170637.138
fil|www.wikidata.org-text-ns.000-db.047.xowa|1919889408|20190113 170641.878
fil|www.wikidata.org-text-ns.000-db.048.xowa|2007924736|20190113 170646.679
fil|www.wikidata.org-text-ns.000-db.049.xowa|2037465088|20190113 170651.543
fil|www.wikidata.org-text-ns.000-db.050.xowa|2004434944|20190113 170656.279
fil|www.wikidata.org-text-ns.000-db.051.xowa|2049900544|20190113 170701.103
fil|www.wikidata.org-text-ns.000-db.052.xowa|2025721856|20190113 170705.935
fil|www.wikidata.org-text-ns.000-db.053.xowa|1955479552|20190113 170710.643
fil|www.wikidata.org-text-ns.000-db.054.xowa|1985421312|20190113 170715.463
fil|www.wikidata.org-text-ns.000-db.055.xowa|2022199296|20190113 170720.267
fil|www.wikidata.org-text-ns.000-db.056.xowa|2097086464|20190113 170725.227
fil|www.wikidata.org-text-ns.000-db.057.xowa|2100703232|20190113 170730.051
fil|www.wikidata.org-text-ns.000-db.058.xowa|2094596096|20190113 170734.967
fil|www.wikidata.org-text-ns.000-db.059.xowa|2041888768|20190113 170740.060
fil|www.wikidata.org-text-ns.000-db.060.xowa|2043031552|20190113 170744.988
fil|www.wikidata.org-text-ns.000-db.061.xowa|1996349440|20190113 170749.808
fil|www.wikidata.org-text-ns.000-db.062.xowa|1965932544|20190113 170754.632
fil|www.wikidata.org-text-ns.000-db.063.xowa|2003156992|20190113 170759.452
fil|www.wikidata.org-text-ns.000-db.064.xowa|2010431488|20190113 170804.412
fil|www.wikidata.org-text-ns.000-db.065.xowa|2067337216|20190113 170809.396
fil|www.wikidata.org-text-ns.000-db.066.xowa|2011815936|20190113 170814.680
fil|www.wikidata.org-text-ns.000-db.067.xowa|2036854784|20190113 170819.620
fil|www.wikidata.org-text-ns.000-db.068.xowa|2065903616|20190113 170824.432
fil|www.wikidata.org-text-ns.000-db.069.xowa|2056220672|20190113 170829.313
fil|www.wikidata.org-text-ns.000-db.070.xowa|2141679616|20190113 170834.197
fil|www.wikidata.org-text-ns.000-db.071.xowa|2102427648|20190113 170839.053
fil|www.wikidata.org-text-ns.000-db.072.xowa|2039107584|20190113 170844.145
fil|www.wikidata.org-text-ns.000-db.073.xowa|2031058944|20190113 170853.661
fil|www.wikidata.org-text-ns.000-db.074.xowa|1986818048|20190113 170859.129
fil|www.wikidata.org-text-ns.000-db.075.xowa|1917296640|20190113 170904.201
fil|www.wikidata.org-text-ns.000-db.076.xowa|2012266496|20190113 170909.361
fil|www.wikidata.org-text-ns.000-db.077.xowa|1987469312|20190113 170914.609
fil|www.wikidata.org-text-ns.000-db.078.xowa|1774043136|20190113 170920.001
fil|www.wikidata.org-text-ns.000.xowa|1864364032|20190113 170217.650
fil|www.wikidata.org-text-ns.004.xowa|182743040|20190113 170208.717
fil|www.wikidata.org-text-ns.008.xowa|1028096|20190113 170213.049
fil|www.wikidata.org-text-ns.010.xowa|4059136|20190113 170226.186
fil|www.wikidata.org-text-ns.012.xowa|6500352|20190113 170221.986
fil|www.wikidata.org-text-ns.014.xowa|823296|20190113 170230.474
fil|www.wikidata.org-text-ns.1198.xowa|32874496|20190113 170234.994
fil|www.wikidata.org-text-ns.120.xowa|22941696|20190113 170304.482
fil|www.wikidata.org-text-ns.146.xowa|19709952|20190113 170848.613
fil|www.wikidata.org-text-ns.2600.xowa|1368064|20190113 170428.216
fil|www.wikidata.org-text-ns.828.xowa|1482752|20190113 170339.551
fil|www.wikidata.org-xtn.category.core.xowa|81920|20190113 171014.358
fil|www.wikidata.org-xtn.category.link-db.001.xowa|19914752|20190113 171010.758
```

```
scanning: C:\xowa\wiki\de.wikipedia.org\
fil|de.wikipedia.org-core.xowa|473968640|20190112 104255.513
fil|de.wikipedia.org-file-core.xowa|57344|20190112 104704.484
fil|de.wikipedia.org-file-user.xowa|229376|20190119 113011.876
fil|de.wikipedia.org-text-ns.000-db.002.xowa|2023882752|20190112 104537.705
fil|de.wikipedia.org-text-ns.000-db.003.xowa|2032525312|20190112 104537.782
fil|de.wikipedia.org-text-ns.000-db.004.xowa|1102012416|20190112 104537.845
fil|de.wikipedia.org-text-ns.000.xowa|1875804160|20190112 104537.496
fil|de.wikipedia.org-text-ns.004.xowa|1012215808|20190112 104537.516
fil|de.wikipedia.org-text-ns.006.xowa|51818496|20190112 104537.566
fil|de.wikipedia.org-text-ns.008.xowa|806912|20190112 104537.601
fil|de.wikipedia.org-text-ns.010.xowa|66285568|20190112 104537.585
fil|de.wikipedia.org-text-ns.012.xowa|1740800|20190112 104537.545
fil|de.wikipedia.org-text-ns.014.xowa|78082048|20190112 104537.635
fil|de.wikipedia.org-text-ns.100.xowa|48726016|20190112 104537.531
fil|de.wikipedia.org-text-ns.828.xowa|1392640|20190112 104537.797
fil|de.wikipedia.org-xtn.category.core.xowa|5484544|20190112 104704.484
fil|de.wikipedia.org-xtn.category.link-db.001.xowa|1260769280|20190112 104704.484
fil|de.wikipedia.org-xtn.search.core.xowa|181776384|20190112 104526.961
fil|de.wikipedia.org-xtn.search.link-title-ns.000-db.001.xowa|326590464|20190112 104350.879
fil|de.wikipedia.org-xtn.search.link-title-ns.999-db.001.xowa|75325440|20190112 104505.910
```

**Comment by desb42** [comment] 2019-01-23 07:57
I can see the confusion.
I use a bigger filesize threshold than you; specifically

    scanning: G:\xowa_dev\wiki\www.wikidata.org\
    fil|www.wikidata.org-core.wbase.xowa|6241882112|20190109 162411.704
    fil|www.wikidata.org-core.xowa|4809084928|20190109 163128.767
    fil|www.wikidata.org-file-core.xowa|57344|20190109 163118.163
    fil|www.wikidata.org-file-user.xowa|122880|20190116 082728.338
    fil|www.wikidata.org-text-ns.000-db.002.xowa|4176502784|20190109 164225.081
    fil|www.wikidata.org-text-ns.000-db.003.xowa|4236955648|20190109 164238.197
    fil|www.wikidata.org-text-ns.000-db.004.xowa|4237774848|20190109 164259.196
    fil|www.wikidata.org-text-ns.000-db.005.xowa|4356366336|20190109 164311.911
    fil|www.wikidata.org-text-ns.000-db.006.xowa|4353953792|20190109 164326.084
    fil|www.wikidata.org-text-ns.000-db.007.xowa|4199845888|20190109 164349.093
    fil|www.wikidata.org-text-ns.000-db.008.xowa|4462739456|20190109 164401.650
    fil|www.wikidata.org-text-ns.000-db.009.xowa|4148629504|20190109 164415.147
    fil|www.wikidata.org-text-ns.000-db.010.xowa|4217356288|20190109 164430.257
    fil|www.wikidata.org-text-ns.000-db.011.xowa|4222705664|20190109 164452.503
    fil|www.wikidata.org-text-ns.000-db.012.xowa|4058402816|20190109 164504.877
    fil|www.wikidata.org-text-ns.000-db.013.xowa|4357410816|20190109 164517.786
    fil|www.wikidata.org-text-ns.000-db.014.xowa|3944222720|20190109 164529.300
    fil|www.wikidata.org-text-ns.000-db.015.xowa|4088733696|20190109 164540.874
    fil|www.wikidata.org-text-ns.000-db.016.xowa|3981443072|20190109 164553.186
    fil|www.wikidata.org-text-ns.000-db.017.xowa|3908349952|20190109 164605.431
    fil|www.wikidata.org-text-ns.000-db.018.xowa|3783643136|20190109 164615.792
    fil|www.wikidata.org-text-ns.000-db.019.xowa|3784609792|20190109 164625.968
    fil|www.wikidata.org-text-ns.000-db.020.xowa|3762429952|20190109 164635.761
    fil|www.wikidata.org-text-ns.000-db.021.xowa|3784122368|20190109 164646.325
    fil|www.wikidata.org-text-ns.000-db.022.xowa|3667738624|20190109 164656.921
    fil|www.wikidata.org-text-ns.000-db.023.xowa|4004425728|20190109 164709.054
    fil|www.wikidata.org-text-ns.000-db.024.xowa|3927781376|20190109 164720.671
    fil|www.wikidata.org-text-ns.000-db.025.xowa|4041846784|20190109 164733.653
    fil|www.wikidata.org-text-ns.000-db.026.xowa|4075601920|20190109 164745.223
    fil|www.wikidata.org-text-ns.000-db.027.xowa|3940876288|20190109 164756.117
    fil|www.wikidata.org-text-ns.000-db.028.xowa|4119248896|20190109 164807.598
    fil|www.wikidata.org-text-ns.000-db.029.xowa|4195262464|20190109 164821.437
    fil|www.wikidata.org-text-ns.000-db.030.xowa|4084887552|20190109 164834.515
    fil|www.wikidata.org-text-ns.000-db.031.xowa|3962265600|20190109 164845.603
    fil|www.wikidata.org-text-ns.000-db.032.xowa|4013555712|20190109 164855.841
    fil|www.wikidata.org-text-ns.000-db.033.xowa|4079128576|20190109 164909.758
    fil|www.wikidata.org-text-ns.000-db.034.xowa|4102705152|20190109 164919.301
    fil|www.wikidata.org-text-ns.000-db.035.xowa|4197883904|20190109 164933.145
    fil|www.wikidata.org-text-ns.000-db.036.xowa|4141494272|20190109 164944.880
    fil|www.wikidata.org-text-ns.000-db.037.xowa|4017836032|20190109 165006.400
    fil|www.wikidata.org-text-ns.000-db.038.xowa|3929546752|20190109 165017.702
    fil|www.wikidata.org-text-ns.000-db.039.xowa|3761389568|20190109 165033.191
    fil|www.wikidata.org-text-ns.000.xowa|3831390208|20190109 164140.949
    fil|www.wikidata.org-text-ns.004.xowa|182743040|20190109 164122.740
    fil|www.wikidata.org-text-ns.008.xowa|1028096|20190109 164130.952
    fil|www.wikidata.org-text-ns.010.xowa|4059136|20190109 164157.030
    fil|www.wikidata.org-text-ns.012.xowa|6500352|20190109 164148.617
    fil|www.wikidata.org-text-ns.014.xowa|823296|20190109 164204.831
    fil|www.wikidata.org-text-ns.1198.xowa|32874496|20190109 164214.086
    fil|www.wikidata.org-text-ns.120.xowa|22941696|20190109 164247.170
    fil|www.wikidata.org-text-ns.146.xowa|19709952|20190109 164953.903
    fil|www.wikidata.org-text-ns.2600.xowa|1368064|20190109 164440.733
    fil|www.wikidata.org-text-ns.828.xowa|1482752|20190109 164334.951
and

    scanning: G:\xowa_dev\wiki\de.wikipedia.org\
    fil|de.wikipedia.org-core.xowa|476315648|20190110 185746.776
    fil|de.wikipedia.org-file-core.xowa|776335360|20180812 230616.000
    fil|de.wikipedia.org-file-ns.000-db.001.xowa|1640964096|20180812 230648.000
    fil|de.wikipedia.org-file-ns.000-db.002.xowa|1640771584|20180812 230744.000
    fil|de.wikipedia.org-file-ns.000-db.003.xowa|1645969408|20180812 230840.000
    fil|de.wikipedia.org-file-ns.000-db.004.xowa|1646596096|20180812 230936.000
    fil|de.wikipedia.org-file-ns.000-db.005.xowa|1641201664|20180812 231032.000
    fil|de.wikipedia.org-file-ns.000-db.006.xowa|1641762816|20180812 231126.000
    fil|de.wikipedia.org-file-ns.000-db.007.xowa|1643061248|20180812 231222.000
    fil|de.wikipedia.org-file-ns.000-db.008.xowa|1643126784|20180812 231318.000
    fil|de.wikipedia.org-file-ns.000-db.009.xowa|1645060096|20180812 231414.000
    fil|de.wikipedia.org-file-ns.000-db.010.xowa|1646702592|20180812 231508.000
    fil|de.wikipedia.org-file-ns.000-db.011.xowa|1646743552|20180812 231604.000
    fil|de.wikipedia.org-file-ns.000-db.012.xowa|1649766400|20180812 231700.000
    fil|de.wikipedia.org-file-ns.000-db.013.xowa|1645740032|20180812 231756.000
    fil|de.wikipedia.org-file-ns.000-db.014.xowa|1649451008|20180812 231852.000
    fil|de.wikipedia.org-file-ns.000-db.015.xowa|1646096384|20180812 231948.000
    fil|de.wikipedia.org-file-ns.000-db.016.xowa|1649065984|20180812 232044.000
    fil|de.wikipedia.org-file-ns.000-db.017.xowa|1653538816|20180812 232140.000
    fil|de.wikipedia.org-file-ns.000-db.018.xowa|1654943744|20180812 232236.000
    fil|de.wikipedia.org-file-ns.000-db.019.xowa|1663946752|20180812 232332.000
    fil|de.wikipedia.org-file-ns.000-db.020.xowa|1654857728|20180812 232428.000
    fil|de.wikipedia.org-file-ns.000-db.021.xowa|1676013568|20180812 232522.000
    fil|de.wikipedia.org-file-ns.000-db.022.xowa|1677000704|20180812 232616.000
    fil|de.wikipedia.org-file-ns.000-db.023.xowa|1678102528|20180812 232712.000
    fil|de.wikipedia.org-file-ns.000-db.024.xowa|1661128704|20180812 232806.000
    fil|de.wikipedia.org-file-ns.000-db.025.xowa|1666592768|20180812 232900.000
    fil|de.wikipedia.org-file-ns.000-db.026.xowa|1658515456|20180812 232956.000
    fil|de.wikipedia.org-file-ns.000-db.027.xowa|1654767616|20180812 233050.000
    fil|de.wikipedia.org-file-ns.000-db.028.xowa|1653239808|20180812 233146.000
    fil|de.wikipedia.org-file-ns.000-db.029.xowa|1659412480|20180812 233240.000
    fil|de.wikipedia.org-file-ns.000-db.030.xowa|1650778112|20180812 233336.000
    fil|de.wikipedia.org-file-ns.000-db.031.xowa|91893760|20180812 233426.000
    fil|de.wikipedia.org-file-ns.004-db.001.xowa|1663148032|20180812 233434.000
    fil|de.wikipedia.org-file-ns.004-db.002.xowa|1051365376|20180812 233526.000
    fil|de.wikipedia.org-file-ns.014-db.001.xowa|5906432|20180812 233558.000
    fil|de.wikipedia.org-file-ns.100-db.001.xowa|281354240|20180812 233558.000
    fil|de.wikipedia.org-file-user.xowa|1339392|20190113 133319.742
    fil|de.wikipedia.org-text-ns.000-db.002.xowa|3177316352|20190110 163749.094
    fil|de.wikipedia.org-text-ns.000.xowa|3898056704|20190110 163734.900
    fil|de.wikipedia.org-text-ns.004.xowa|1014104064|20190110 163736.567
    fil|de.wikipedia.org-text-ns.006.xowa|51798016|20190110 163740.159
    fil|de.wikipedia.org-text-ns.008.xowa|811008|20190110 163742.675
    fil|de.wikipedia.org-text-ns.010.xowa|66539520|20190110 163741.567
    fil|de.wikipedia.org-text-ns.012.xowa|1740800|20190110 163738.773
    fil|de.wikipedia.org-text-ns.014.xowa|78880768|20190110 163744.407
    fil|de.wikipedia.org-text-ns.100.xowa|48934912|20190110 163737.700
    fil|de.wikipedia.org-text-ns.828.xowa|1421312|20190110 163750.895
    fil|de.wikipedia.org-xtn.category.core.xowa|5533696|20190110 163644.234
    fil|de.wikipedia.org-xtn.category.link-db.001.xowa|1271332864|20190110 163634.435
    fil|de.wikipedia.org-xtn.search.core.xowa|182439936|20190110 191532.085
    fil|de.wikipedia.org-xtn.search.link-title-ns.000-db.001.xowa|327933952|20190110 190045.365
    fil|de.wikipedia.org-xtn.search.link-title-ns.999-db.001.xowa|75796480|20190110 190510.240

I have added up the 000 filesizes of wikidata for your version and mine the respective values are (in bytes)

    158,162,485,248
    158,161,063,936
          1,421,312 difference (just over 1MB)

I have also noticed that I have not created the categories table for wikidata (I hope this is not introducing false issues) 
I'm off to build the categories now

**Comment by gnosygnu** [comment] 2019-02-10 13:39
Sorry for the late reply. Regarding your last comment, yes that's fine. I should have remembered that you were changing file sizes.

As noted in #351, I was able to reproduce this error during my dewiki build. I checked in a fix above, and also refactored a lot of the code to make the main Xoa_lang_mgr (XOWA language manager) more uniform in usage. As I'm building dewiki this week, I'll close this issue out after a successful run.

**Comment by gnosygnu** [comment] 2019-02-18 01:15
Unfortunately, this was still an issue after the build. I was able to fix it in the commits above. Snippet below as simple reproduction

Also, regarding the circular reference between pt and pt-br. This is defined by MediaWiki
* [pt has fallback of pt-br](https://github.com/wikimedia/mediawiki/blob/master/languages/messages/MessagesPt.php)
* [pt-br has fallback of pt](https://github.com/wikimedia/mediawiki/blob/master/languages/messages/MessagesPt_br.php#L80)

XOWA handles circular references, thought it was inadvertently loading dupes b/c of some logic with "en" being the default fallback for every lang

```
function p.test21(frame)
   local var = mw.language.new('gl'):isRTL();
   dbg(var);
end
```

**Closed** 2019-02-24 21:22 UTC
Labels: [impact 2 - many classes], [priority 3 - moderate], [resolved - commit], [schedule 1 - within days], [type - bug], core - language, core - make wiki
