### ISSUE TITLE
Read-only remote wiki database

### ISSUE THREAD

**Issue by ZebraFromPluto** [gnosygnu/xowa#509] opened 2019-07-03 20:25 UTC
First, hi gnosygnu and many thanks for the wonderful program! I recently decided I wanted some offline wiki databases and this appears to be the best program for it.

I found a comment by you elsewhere explaining how to use a remote database and made a simple batch file like this that I put in the program folder:
java -jar xowa_windows_64.jar --wiki_dir \\\\SERVER\\Wiki\\

A problem however is when using wikis in a remote network location that has read-only permissions. The program wants to create a custom wiki-file-user.xowa file ("wiki" being the name of the wiki in use) in the wiki folder, and this is an obvious problem when said folder is read-only.

The program will still work without write permission, but there will about a minute long pause the first time it tries to access a new wiki for each new session. And if you left tabs open to several different wikis when you quit the program, then the pause the next time you launch the program will be compounded for each wiki in use.

Even if I keep a wiki-file-user.xowa file in the remote folder the pauses will still happen. (What's in this file anyway considering the program will still function without it?)

Can the wiki-file-user.xowa file be stored in the program's "user" folder instead?

Also, it would be nice if the ability to specify the wiki_dir could be done from the program's Options window. Using the batch file leaves a cmd window open (even if you prefix the java command with "start") and also displays some errors about a SplashScreen.

**Comment by gnosygnu** [comment] 2019-07-05 04:24
Hi, thanks for the kind words about XOWA! I'm glad you find it useful, and hope that it continues to work well for you.

First, with regards to the "wiki-file-user.xowa file issue. This file is used to store images downloaded from the web.

When you view a page in XOWA, XOWA will try to pull the images from 1 of 2 places
* From the file*.xowa databases
* From the Wikimedia web sites
  * Note that files downloaded from Wikimedia are saved in adhoc file-user.xowa databases (so the same file won't get pulled down again and again)

You can disable all write-activity to "wiki-file-user.xowa" by disabling all network connectivity for XOWA. (Unchecking "Web access enabled" at home/wiki/Special:XowaCfg?grp=xowa.app.security)

If this doesn't work for you, then this will need a new option for not using "wiki-file-user.xowa" or storing it in the "user" folder. Unfortunately, neither change is really easy.

Second, regarding a wiki_dir, it sounds like you're on a Windows box. If so, you can create a shortcut to xowa_64.exe with a target like the following: "C:\xowa\xowa_64.exe --wiki_dir D:\xowa\wiki"

Hope this helps. Thanks!

**Comment by ZebraFromPluto** [comment] 2019-07-05 13:11
Thanks for the reply.  I realized after I made my post that I forget to mention the platform I was on. Sorry about that. I was going to edit my post but then realized my mention of using xowa_windows_64.jar indicated it anyway. I can dual boot in Windows 7 and Windows 10, but prefer Windows 7 so I have been testing the software there.

I already had "Web access enabled" turned off but unfortunately this doesn't help. It appears the program still tries to access this file with write permission, and whether it's that or some other side effect there is a roughly one minute pause the first time any given wiki is accessed for every session,

I feel I should stress that this is a very important feature. The idea of giving many users the ability to connect to a central wiki server is far too useful a feature to ignore. And the remote server simply cannot enable write access as this would allow either intentional or unintentional damage to the database.

I appreciate that this may not be an easy change to make, but it is a vital change to make. It's easy to imagine situations such as education centers in third world countries without regular internet access providing a wiki database to use. It would be impractical to install the entire wiki database on every machine, not to mention a maintenance nightmare. And if everybody could connect to a central server then a single administrator could easily make updates etc to the database that affect all users at once, and without the worry of tampering of the database.

Also, even if write permissions were turned on, what's going to happen when multiple terminals try to modify wiki-file-user.xowa at the same time? In another situation, it may be that an organization would rather distribute the wiki databases on a DVD or some other read-only material. It's simply not viable to be creating or modifying files in the main wiki databases themselves.

In regards to creating a shortcut to xowa_64.exe with a target specifying wiki_dir, I should have realized that myself. DOH! Thanks, that works much better! It would still be nice to be able to specify it from within the program options, but not vital.

**Comment by gnosygnu** [comment] 2019-07-06 01:14
Thanks for the detailed explanation. 

In short, I looked at it a little today, but don't know why there is a 1-minute delay. 

A few questions / requests:
* What is the Operating System for "\\SERVER\Wiki\"? Another Windows box? Linux? OS X? etc?
* What is the file system for "\\SERVER\Wiki\"? NTFS? ext4? OS X?
* Are there any special permissions on it besides read-only?

Can you try the following on your Windows 7 box?
* Download Simple Wikipedia (There's a link on the main page and it should take about 3 to 5 minutes)
* Go to Properties for C:\xowa\wiki\simple.wikipedia.org\simple.wikipedia.org-file-user.xowa
* Go to the Security tab, and remove all permissions from all users except for "Read" and "Read and Execute". Also make another user the owner
* Open XOWA and go to Simple Wikipedia -> Does it take a minute? (mine is just as fast)

---

Regarding your edit:

> Isn't it redundant to be storing them twice? It seems the cache will recycle drive space with the ability to specify a max size, but will wiki-file-user.xowa just continue to grow forever as new images get downloaded? Perhaps I'm not understanding things correctly, but if I do then I'd think just using the cache would be ideal, and don't see the need for wiki-file-user.xowa at all.

Yup, this is correct. The main purpose of wiki-file-user.xowa is to be as offline as possible. The  general usage pattern was to be something like this
* User connects to internet
* User opens up Page_1 in enwiki
* XOWA downloads images from en.wikipedia.org and saves them in wiki-file-user.xowa
* XOWA saves the same images to /xowa/file because the HTML references file locations (&lt;img src='file:///xowa/file/....'>)
* User repeats process with other pages: Page_2 -> Page_100
* At a certain point, user saves over 100 MB of images in /xowa/file
  * Cache maintenance process kicks in to limit size to 100 MB for /xowa/file
  * This means that images from Page_1 are deleted from /xowa/file
* User disconnects from internet
* User visits Page_1 again

Without wiki-file-user.xowa, the user would have to:
* re-connect to the internet to view the images (user may not have online capabilities)
* re-download the images again (user may not want to incur additional bandwidth usage)

So, there is redundancy, but I think it comes at a useful purpose.

That said, I could add an option for this, but I'm not sure if that will solve the delay issue above.

**Comment by ZebraFromPluto** [comment] 2019-07-06 02:54
- What is the Operating System for "\SERVER\Wiki"? Another Windows box? Linux? OS X? etc?

I'm running everything from the same computer for now while I'm testing. I have the wikis residing on a local USB drive and simply shared the "wiki" folder using built-in Windows functionality:
First ensure you have "file and printer sharing" turned on in the "Advanced sharing settings" in the "Network and Sharing Center" Control Panel.
Get Properties for the "wiki" folder, click the "Sharing" tab, click "Advanced Sharing...", turn on "Share this folder", then click "OK".
It should default with just "Read" permissions.

I can now connect to it as a server, with read-only permissions the same as a remote user using a shortcut with this target:
C:\XOWA\xowa_64.exe --wiki_dir \\\\SERVER\Wiki\

And I can also connect to it as local drive WITH write permissions by launching a different shortcut using this target:
C:\XOWA\xowa_64.exe --wiki_dir E:\Wiki\

SERVER would be the name of your computer. (Which is not my actual computer name.) I've simplified the paths from what my actual setup uses to better illustrate how it works.

- What is the file system for "\SERVER\Wiki"? NTFS? ext4? OS X?

Everything is NTSF.

- Are there any special permissions on it besides read-only?

Nope. Just what I've described above.

<hr>

I can't really do your test with the Simple Wikipedia as I don't have any other users on my computer, and would rather not create a new user just for a quick test unless the need becomes great. I did however test opening the Simple Wikipedia as a read-only remote server and the pause for it was only about 20 seconds instead of a minute. My guess would be that there's some core or system level functionality that doesn't fail right away when it can't get write permission and instead waits for a timeout. I think the only real fix is to simply not try to access any files in the "wiki" folder using write permission.

If you can share your own "wiki" folder the way I did above perhaps you can test it on your end and see what I'm talking about.

Storing wiki-file-user.xowa in the program's "user" folder would certainly be the ideal solution. But considering there was no wiki-file-user.xowa until v2.5.4.1 perhaps you could have an option to revert to however it worked before v2.5.4.1.

Your explanation to my edit makes sense and now I understand it. Thanks. I could also see some people preferring JUST the temp cache though, without permanently storing the images in wiki-file-user.xowa. You'd only have recent images in the cache, and they'd have to reload from the internet if they get purged. I really don't like kludges or half-solutions though. Storing it in the program's "user" folder really would be best. But of course that's easy for me to say when I'm not the one who has to code it.

**Comment by ZebraFromPluto** [comment] 2019-07-06 13:28
I wanted to go into a bit more detail about sharing for people who want to try it.

First, when sharing your "wiki" folder as describe above, and you want know what the network path to it is, simply look at the "Sharing" tab in the Properties for the folder and it will be displayed under "Network Path:".

Next, the shared "wiki" folder doesn't need to reside on a separate drive. In fact, you should be able to leave it in the XOWA folder, and then you can still run xowa_64.exe like normal without a shortcut, and with normal file privileges. Share the "wiki" folder and create a network shortcut to the program to launch it as shown above and you can also treat it as a read-only remote network location. Just don't put the shared folder anywhere inside "Program Files" or your user folder, which includes your Documents, Pictures, Music folders etc. They have their own way of dealing with permissions and sharing. So if you put XOWA inside your "Program Files" then you should put the "wiki" folder somewhere else if you want to share it.

If you try to rename or move a shared folder, Windows will warn you that the folder will no longer be shared if you do so. You need to go back into "Advanced Sharing" for the folder and turn off "Share this folder" first. After renaming or moving the folder turn it back on again. You should also notice that although the shared name defaults to the folder name when you turn on "Share this folder", you can change it to anything you like. You could name the "wiki" folder as "foo", share it as "bar", then create a shortcut to the program such as: C:\XOWA\xowa_64.exe --wiki_dir \\\\SERVER\bar\

Don't forget that these instructions pertain to Windows 7. Windows 10 should work in a similar manner, but I'm not going to boot into Windows 10 to check the exact mechanics there unless I need to.

<hr>

gnosygnu, a couple things I'd like to direct at you:

Keep in mind that I'm only assuming the pause is being caused by the program wanting write permissions to wiki-file-user.xowa, or the folder in general. It's entirely possible there's an issue just simply using a network path. If you can create your test setup as I've shown then perhaps you can narrow it down for sure.

Also, I noticed something else while launching the program locally WITH write permissions. Move all the files inside "simple.wikipedia.org" with "-file-" in the name somewhere else so that you don't have any images downloaded (beyond what might be in the cache). Launch the program normally with write permissions, and not only does it create simple.wikipedia.org-file-user.xowa, but it will also create simple.wikipedia.org-file-core.xowa. This is also going to be an issue when working with read-only wikis, as nothing in the folder can be created or modified at all.

**Comment by gnosygnu** [comment] 2019-07-06 16:10
Thanks for the precise instructions. Given that I wasn't able to reproduce your issue, the instructions really help in reproducing it.

The short answer is that this is a bug with XOWA's read-only detection code. You can work around it by explicitly marking all the .xowa files read-only. 

Specifically, do the following:
* Open Windows Explorer
* Go to your external folder. For example: ```\\YOUR_SERVER_NAME\wiki\en.wikipedia.org```
* Select all the files in the folder (Ctrl+A)
* Go to the Properties Tab
* Check the Read-only mark

Let me know if the work-around fixes the issue. If it does, then I'll do a real fix inside XOWA and try to release something next week.

A little more detail on the bug below. I'll respond to your other comments later.

Thanks.

---

* The problem is that SQLite needs to be explicitly told when it's a read-only connection.
* XOWA has code to handle this situation: https://github.com/gnosygnu/xowa/blob/341d2e13a43bb91e40b0c0204a750a5f56780a26/140_dbs/src/gplx/dbs/engines/sqlite/Sqlite_engine.java#L71
* Unfortunately, XOWA's code is only checking at the file-level. In your case, read-only is enforced a parent folder level (a few levels up)
* So even though ```\\YOUR_SERVER_NAME\wiki``` was a read-only folder, the actual files (```simple.wikipedia.org-core.xowa```) were still marked as read-write
* Windows (and other OSs) are smart enough to enforce the read-only permission on the file; XOWA wasn't
* However, once you toggle the read-only check-box for all the ```.xowa``` files, then XOWA will detect them as read-only

**Comment by ZebraFromPluto** [comment] 2019-07-06 16:47
Awesome find! I tested a couple of wikis and that seems to remove the pauses. Thanks! I look forward to a proper solution whereas I don't need to set the files themselves to read-only.

I'm still not keen on the idea of modifying that folder at all, even when write permissions are available, simply because problems will arise if multiple users connect to it at once. But a setup with multiple users should have read-only permissions anyway. Perhaps this will be the best solution for everything you want the program to do. It's your program, and I trust any solution you come up with will be satisfactory. Thanks!

**Comment by gnosygnu** [comment] 2019-07-09 03:26
Sorry, a little late in replying to your comments. Let me know if I missed anything.

Thanks

---

>> What is the Operating System for "\SERVER\Wiki"? Another Windows box? Linux? OS X? etc?

> I'm running everything from the same computer for now while I'm testing. I have the wikis residing on a local USB drive and simply shared the "wiki" folder using built-in Windows functionality
> ...
> ...

Said above, but worth saying again. Thanks again for the exhaustive detail.

> Your explanation to my edit makes sense and now I understand it. Thanks. I could also see some people preferring JUST the temp cache though, without permanently storing the images in wiki-file-user.xowa. You'd only have recent images in the cache, and they'd have to reload from the internet if they get purged. I really don't like kludges or half-solutions though.

In general, I try to treat online connectivity as a limited resource. As such, I really didn't like the idea of downloading images, showing them the user, and then discarding them. At that point, they will have to download them again (more bandwidth usage) or do without them (no connectivity).

I feel that the ```file-user.xowa``` was a pretty good way of accomplishing this, with only a cost of disk space. In today's age of TB hard-drives (or GB flash-drives), I really feel that a file-user.xowa db measured in MB is fractional. There's also the undocumented feature that ```file-user.xowa``` can be deleted to reclaim disk space if necessary.

> Storing it in the program's "user" folder really would be best. But of course that's easy for me to say when I'm not the one who has to code it.

I thought about this, and I decided early on to keep "wiki" data in the wiki folder. The problem with the "user" folder is that it blurs the boundaries between different dated wikis (i.e.: is the image for the 2019-05 or 2018-07?). Granted, in a multi-user environment, the "user" folder is a more natural fix, but XOWA currently only supports one user: anonymous.

That said, I could add an option for this, but there is a permutational complexity to supporting more and more options. XOWA already has a lot of options, and this is one that seemed like low usage.

Finally, keep in mind that the ```file-user.xowa``` is not critical. If, for some reason, an image doesn't save there (because multiple users are trying to save a file), it just fails and XOWA continues.

> gnosygnu, a couple things I'd like to direct at you:

> Keep in mind that I'm only assuming the pause is being caused by the program wanting write permissions to wiki-file-user.xowa, or the folder in general. It's entirely possible there's an issue just simply using a network path. If you can create your test setup as I've shown then perhaps you can narrow it down for sure.

Yup, responded to above. Thanks again.

> Also, I noticed something else while launching the program locally WITH write permissions. Move all the files inside "simple.wikipedia.org" with "-file-" in the name somewhere else so that you don't have any images downloaded (beyond what might be in the cache). Launch the program normally with write permissions, and not only does it create simple.wikipedia.org-file-user.xowa, but it will also create simple.wikipedia.org-file-core.xowa. This is also going to be an issue when working with read-only wikis, as nothing in the folder can be created or modified at all.

Yes, this is an intentional design decision. XOWA will always try to create a ```file-core.xowa```. For read-only environments, I'd recommend that the wiki be opened once in read-write mode to create it. If it's not there, the file will fail to create, but I don't think that will have any noticeable impact (no delay)

> Upon doing some thinking, I realize the problem is a bit more involved than simply moving wiki-file-user.xowa to the program's "user" folder, assuming you can do that. It would defeat the purpose of having a limited local cache size (which I'm assuming is an issue on mobile devices) if wiki-file-user.xowa is there as well, which can grow in size forever. In my mind, the concept of retaining retrieved images forever is the real problem. Things would be a lot simpler if retrieved images were only stored in the cache, and if they get purged due to the max size being exceeded, then they'd need to be retrieved from the internet again if needed. If a user wants to be able to keep a lot of retrieved images around, then they just need to set a large max cache size.

Replied to in my comment above. Again, I opted to treat online connectivity as a scarce resource.

Also, keep in mind the user can download the full set of images for a wiki from archive.org. For example, for en.wikipedia.org, there's about 150 GB of files at https://archive.org/download/Xowa_enwiki_latest. If they have all the file_ns...xowa databases then there will be very little that will go into file-user.xowa

> Awesome find! I tested a couple of wikis and that seems to remove the pauses. Thanks! 

Cool. Thanks for the confirm.

> I look forward to a proper solution whereas I don't need to set the files themselves to read-only.

Yeah, that will be part of the next release. ETA of this week-ish.

> I'm still not keen on the idea of modifying that folder at all, even when write permissions are available, simply because problems will arise if multiple users connect to it at once. 

For a multi-user environment, I'm relying on SQLite to handle the multiple requests. XOWA doesn't do any additional logic. Maybe it should, but that requires a lot more coding than I have time for.

> But a setup with multiple users should have read-only permissions anyway. Perhaps this will be the best solution for everything you want the program to do. It's your program, and I trust any solution you come up with will be satisfactory. Thanks!

Yeah, to repeat, I'll fix the start pause b/c of read-only permissions on a higher-level parent folder. I'm not planning to add any additional options for disabling / limiting the size of file-user.xowa or moving it to the /user/ folder. Thanks.

**Comment by ZebraFromPluto** [comment] 2019-07-09 13:17
Thanks so much for everything! I realize now that I put too much importance on the need for writable files to reside elsewhere, without understanding that the program will gracefully handle everything just fine when situated with read-only permissions. I was also thinking later yet that SQLite likely handles various things as well, as it should, just as you've suggested in your reply.

I must say, this is a very fine program, and I have been delighted to find myself browsing wiki pages for hours at a time, much the way many people get stuck endlessly clicking YouTube links. It's one of those programs that's "just done right!" I am simply amazed at the details and little nuances XOWA handles so well. I can't thank you enough for this program, and I can't possibly recommend it enough to anybody else who's looking for an offline wiki reader.

**Comment by gnosygnu** [comment] 2019-07-20 13:37
This took longer than I expected. The main issue is that I wanted to handle NTFS permissions as well, which turns out to be complicated. I also wanted to make this an option

I made the commit above and will build sometime Sunday or Monday. I want to tackle the other issue as well.

Short instructions below

---

* Go to home/wiki/Special:XowaCfg?grp=xowa.app.dbs (this will be in the new release)
* The options are the following:
  * Basic - file only : Default option. The current behavior
  * Basic - file and parent dirs: Check read-only for every folder until root. Should handle File Sharing permissions as described above
  * Permissions - file: Check ACL (NTFS) / POSIX permissions. May not work in some cases because Java NIO looks pretty rough (I think I need to do JNI to get the actual info)

**Comment by ZebraFromPluto** [comment] 2019-07-20 13:53
That should work fine. Thanks. I'll check it after you make the new release.

**Comment by ZebraFromPluto** [comment] 2019-07-25 15:36
I've done some quick testing with the new v4.6.2.1907 release and everything works great! You have a minor issue in the form of a typo in the new"App - Databases" options  I figured I should point out though:

"Read-only dection" should be "Read-only detection"

Many thanks for this fix, and the other fixes as well!

**Comment by gnosygnu** [comment] 2019-07-26 01:52
> I've done some quick testing with the new v4.6.2.1907 release and everything works great! 

Cool. Thanks for the confirm!

> "Read-only dection" should be "Read-only detection"

Oops. Missed that. Will be part of  next release Thanks for correcting!

> Many thanks for this fix, and the other fixes as well!

No problem. Thanks for reporting them to begin with!

**Closed by gnosygnu** 2019-07-26 01:52 UTC
Labels: [effort 4 - less than a day], [priority 4 - minor], [resolved - commit], [risk 3 - moderate], [schedule 1 - within days], [type - bug], core - database
