### ISSUE TITLE
Switching tab positions of two different wiki projects causes both to have all links broken

### ISSUE THREAD

**Issue by NijazM** [gnosygnu/xowa#761] opened 2020-07-13 21:19 UTC
I noticed that if I open some wikipedia page in first tab in xowa, and open help pages of xowa in 2nd tab, and swap positions of tabs by drag and drop, then all links of wikipedia page that lose it's host at the start of url, while those from xowa help pages get host of wikipedia at start of url.

For example if first tab is `en.wikipedia.org/wiki/Category:Free_wiki_software` and 2nd tab is `home/wiki/Help/Contents` and I swap their positions. Then link to Overview in xowa help is like: `en.wikipedia.org/wiki/Help/Overview` which does not exist. And link to open source software in wikipedia page is `home/wiki/Open-source_software` which does not exist of course.

Please fix this.

**Comment by gnosygnu** [comment] 2020-07-15 12:53
Thanks for the detailed comment! I was able to reproduce this on my side.

Let me make a fix for it in the next few days. Will report back here when done

**Comment by gnosygnu** [comment] 2020-07-17 13:28
Pushed a fix for the above and created a new unofficial release: https://github.com/gnosygnu/xowa/releases/tag/v4.6.9.2007

@AntiMortal: I like to give credit in the XOWA change logs to users who discover bugs. The next release will have a line like `Gui: Fix page loading in wrong wiki after switching tab positions. {detected by anonymous}` Let me know if you'd like to be cited as AntiMortal or would rather remain anonymous.

Otherwise, thanks!

**Comment by AntiMortal** [comment] 2020-07-17 13:56
Souds cool, but I would be liked to be cited as Nijaz M, as that is my real name. AntiMortal is just random username I thought because did not have better idea, and trust me had better usernames before. Thanks for fixing.

**Comment by gnosygnu** [comment] 2020-07-20 03:42
Cool. `NijazM` it is. Thanks!

**Closed** 2020-07-20 12:31 UTC
Labels: [effort 4 - less than a day], [priority 2 - major], [resolved - commit], [risk 4 - minor], [schedule 1 - within days], [type - bug], core - gui
