### ISSUE TITLE
Search Criteria Issue

### ISSUE THREAD

**Issue by XowaWilliam** [gnosygnu/xowa#64] opened 2016-07-02 11:16 UTC
Just discovered a small glitch in the search criteria when searching for date numbers mixed with text.

I wanted to look up **July 15**, and after typing in **July**, many results with **July** appeared in the drop box. 
When I added a **space** the drop box closed up. 
When I included the number **15**, the drop box remained closed.

This occurred despite there being a valid page named **July 15**.

This was not a serious issue, as when just **July** is typed, **15** is amongst the options available.

However my concern is this may become a problem in yet unseen circumstances.

**Comment by gnosygnu** [comment] 2016-07-02 18:34
Hi! I tried now, but wasn't able to reproduce. See my screenshot .
![july_15](https://cloud.githubusercontent.com/assets/4994104/16541934/e0186342-4061-11e6-82ae-37c6ca0c075b.png)

I've seen this happen randomly when the app is opened for a few hours. The underlying cause seems to the GUI library (SWT), and I can't track down why.

In short, can you try restarting XOWA and seeing if it still occurs? If it does, then I'll ask you to check the log or try some other debugging.

Thanks!

**Comment by XowaWilliam** [comment] 2016-07-02 23:58
Thanks for screen shot.

I tested my Simple Wiki, and it worked perfectly.

So I assume an error crept in while building the search menu through the Import Offline feature, so the fault is on my side.

I will do a rebuild with latest June English Wikipedia data.

You can close #64

**Comment by gnosygnu** [comment] 2016-07-03 00:03
Cool. It might be that the English Wiki failed to build.

You can also download the files from here:

http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_core.zip
http://archive.org/download/Xowa_enwiki_latest/Xowa_enwiki_2016-06_xtn.search.core.zip

Let me know if there's anything else. Thanks for the follow-up!

**Comment by XowaWilliam** [comment] 2016-07-04 02:54
Hi Mr Gnosygnu.

After trying many things, I could not correct the Search Criteria issue unless I reverted to older Xowa version **3.5.1.1** , only then does the search criteria work as it should.

I noticed that user **Ope30** in #65 is having the very same issue.

I managed to get a screen shot where it describes an error at the bottom of the page. Upon typing the word **July**, after pressing the **space bar**, the error appears at the bottom of the screen.

Hope this is helpful.

![xowa-search-g-drive-](https://cloud.githubusercontent.com/assets/12995082/16549745/b6298db2-41a2-11e6-9c50-260bcb178aad.gif)

**Comment by gnosygnu** [comment] 2016-07-04 04:05
Thanks for the screenshot! As said elsewhere, the error message was extremely helpful.

Basically, I broke multiple word search in v3.6.3+ because of some tweaks to the Search algorithm. I never noticed on my machine because it only affected old wikis (2016-05 and earlier). All the wikis on my machines were new ones (2016-06 and up)

I release v3.7.1.2 tonight to handle the issue: https://github.com/gnosygnu/xowa/releases/tag/v3.7.1.2 . Please give it a try; it should resolve the issue.

Thanks!

**Comment by XowaWilliam** [comment] 2016-07-04 06:31
Thank you Mr Gnosygnu.

Installing the very latest upload Xowa ver v3.7.1.2 solved this the search results problem.

That patch came fast :)

**Comment by gnosygnu** [comment] 2016-07-04 17:28
> Installing the very latest upload Xowa ver v3.7.1.2 solved the search results problem.

Great! Thanks for the follow-up!

> That patch came fast :)

Yup, error messages help a lot!

**Comment by gnosygnu** [comment] 2016-07-11 04:24
This was fixed last week in v3.7.1.2. I'm going to close the issue now. Let me know if there's anything else, and I'll reopen. Thanks.

**Closed by gnosygnu** 2016-07-11 04:24 UTC
Labels: resolved, search
