### ISSUE TITLE
frwiki =Module:Bases:148 attempt to call nil

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#531] opened 2019-08-03 14:03 UTC
I have just tried to rebuild frwiki (2019-06-01) and am get many of the above error
As an example fr.wikipedia.org/wiki/Yannick_Favennec_Becot

The wikitext triggering this is

    {{bases vie publique}}
I have tracked this down to one line in Module:Bases

    table.foreach(valsNonFr, function(k,v) table.insert(vals, v) return nil end)
approximately line 143

This seems to be causing the table `vals` to be reset to `nil`

As it happens `valsNonFr` is an empty table `{}`

**Comment by gnosygnu** [comment] 2019-08-05 03:45
Hi! Thanks for the report as well as the specific link to fr.wikipedia.org/wiki/Yannick_Favennec_Becot

I was pretty busy with v4.6.3.1908 release tonight, so wasn't able to really look at this.

I'm bringing down 2019-06 frwiki now, but probably won't get more info till later this week. Will triage this next.

Thanks!

**Comment by gnosygnu** [comment] 2019-08-11 03:43
Took a quick look at this. The problem is that Luaj 3.0+ does not support foreach

```
dbg(table.foreach);
```

Lua 5.1 does support it: https://www.lua.org/source/5.1/ltablib.c.html

I see that Luaj 2.0.3 has support for it. Let me try to add it tomorrow

**Comment by gnosygnu** [comment] 2019-08-11 15:54
Not as bad as I feared. Resolved with the commit above and verified with fr.wikipedia.org/wiki/Yannick_Favennec_Becot

**Closed** 2019-08-13 02:49 UTC
Labels: [effort 4 - less than a day], [priority 2 - major], [resolved - commit], [risk 4 - minor], [schedule 1 - within days], [type - bug], core - parser, xtn - lua
