### ISSUE TITLE
Progress Messages Cut Off by Bottom of Window

### ISSUE THREAD

**Issue by MasterEric** [gnosygnu/xowa#24] opened 2015-09-21 02:05 UTC
![screenshot 10](https://cloud.githubusercontent.com/assets/4635334/9984272/79413618-5fe2-11e5-91f4-fdc5ea4836fa.png)

Look at the bottom of this image (click to zoom and see more clearly); the text displaying the progress of the current import is obscured partially. Changing the size of the window does not fix the issue.

Right clicking and selecting the "Show Progress Messages" option allows me to see the list, but it does not update, meaning every time I want to check on the progress, I have to go in and click to see the progress.

At first, I almost thought there were no progress messages in the program at all, until I later saw the text change at the bottom.

**Comment by gnosygnu** [comment] 2015-09-21 04:20
Hi! Thanks for the report as well as the screenshot!

I've only seen this issue on machines with large fonts enabled. However, your screenshot looks like normal fonts. Out of curiosity, is this Windows 8 / 10? And is it normal fonts (default mode)? Depending on your answer, I'll try to reproduce this on my side.

In the meantime, there is a manual workaround for this issue. Please try the following:

* Go to home/wiki/Help:Options/Window
* Change "Adjustment type" to "relative"
* Change "Adjustment rect" to "0,0,0,-20". Note that "-20" means make the HTML box 20 pixels shorter, which will bring the progress window into view. Experiment with the "-20" number until it suits your preference.
* Click the Save button -- the floppy disk icon along the middle-right margin of the screen.

Let me know if there's anything else. Thanks!

**Comment by MasterEric** [comment] 2015-09-22 15:59
Thanks for the workaround!

And yes, this is Windows 8.1 with default font size.

**Comment by gnosygnu** [comment] 2015-09-23 04:09
Cool. Thanks for the confirm! I don't have a Windows 8.1 box handy, but I'll try to set one up this week. I'll post again when I have more info.

**Comment by gnosygnu** [comment] 2015-10-12 05:35
I wasn't able to reproduce this on a loaner Windows 8.1 laptop. I should have another Windows 8.1 laptop to try in the next few days. If I still can't reproduce it, I'll look at changing the UI so it is "smarter" in sizing the various widgest.

**Comment by gnosygnu** [comment] 2016-03-28 05:39
Just an overdue follow-up. I've tried this on a few loaner 8.1 laptops, and can't reproduce the progress messages being cut off. It does happen in Large Fonts mode though. I'm still aiming to rewrite the UI layout logic, but for now, the only workaround is the manual step above. I'll keep this ticket open until I reach a better resolution. Thanks.

**Comment by gnosygnu** [comment] 2017-02-15 21:48
Another overdue follow-up. This issue will be resolved in the next release, which is tentatively scheduled for this weekend.

For those interested, XOWA will no longer use a manual layout manager, but will instead use the SWT GridLayout. It turns out that manual layout calculations are complicated for the following reasons:
* **Operating System differences** For example, the thickness of the application window border or the height of the application window title. For the record, XOWA did try to handle these.
* **DPI variances**: Systems can also change the DPI, such as Large Fonts mode for laptops, or High DPI settings. XOWA didn't handle this, which caused the issues above. This may be trivial to handle, but after discovering that Eclipse Mars and earlier failed on high DPI machines, I decided to punt the whole thing to SWT.

If anyone wants a preview build, let me know which platform, and I'll generate one for you. Otherwise, I'm going to close this out in a few days. Should the problem recur, feel free to reopen, or create a new issue.

Thanks

**Comment by gnosygnu** [comment] 2017-02-22 02:52
This was resolved in tonight's 4.3 release. I tested on two separate laptops. If it's still occurring, let me know and I'll investigate. Thanks.

**Closed by gnosygnu** 2017-02-22 02:52 UTC
Labels: gui, resolved
