### ISSUE TITLE
Luaj: Return NIL not NONE for table.remove and empty table (when is nil not nil)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#604] opened 2019-10-22 06:13 UTC
The page `commons.wikimedia.org/wiki/United_Kingdom`
give a big red error

    Script error: =Module:Fallback/sandbox:108 bad argument: string expected, got nil

On looking at Module:Fallback/sandbox, the lines where the error occurs are

    local function getFallbacksFor(lang)
      -- 1. First expand the list with Commons-local fallbacks from _fblist[lang].
      local languages, result, hasEnglish = {lang}, {}, false
      while true do
        -- Extract a language from the array to process from the start.
        local lang = table.remove(languages, 1)
        if lang == nil then
          break
        end
        -- Normalize the given language code to lower case, with dashes separators only, and all spaces trimmed
        lang = string.gsub(string.gsub(string.lower(lang), '_', '-'), ' ','')

The last line shown is where the error occurs
If I place a few `dbg` statements like

    local function getFallbacksFor(lang)
      -- 1. First expand the list with Commons-local fallbacks from _fblist[lang].
      local languages, result, hasEnglish = {lang}, {}, false
    dbg('a', mw.dump_table(languages))
      while true do
        -- Extract a language from the array to process from the start.
        local lang = table.remove(languages, 1)
    dbg('b', lang, c')
        if lang == nil then
          break
        end
        -- Normalize the given language code to lower case, with dashes separators only, and all spaces trimmed
    dbg('d', lang, lang == nil, lang == 'nil')
        lang = string.gsub(string.gsub(string.lower(lang), '_', '-'), ' ','')
Then I get some unexpected results

    a { [1] = en,}  
    b en c 
    d en false false 
    b nil c 
    d nil false false 
Second time round the loop is supposedly a nil value but something is not right

**Comment by gnosygnu** [comment] 2019-10-30 13:43
Thanks for the detailed breakdown. I believe the issue was with Luaj and some incorrect code to handle invalid table.remove. More details below.

Otherwise, fixed in the commit above. Thanks!

---

The problem is that Luaj returns ```NONE``` instead of ```NIL``` for invalid ```table.remove``` calls.

From what I can tell, NONE is an internal constant only: https://stackoverflow.com/questions/38562720/is-none-one-of-basic-types-in-lua

Moreover, Lua source code for table.tremove returns 0 which maps to TNIL, not TNONE (which is -1)
* LUA_TNONE is -1: https://www.lua.org/source/5.1/lua.h.html
* table.tremove returns 0: https://www.lua.org/source/5.1/ltablib.c.html

```
static int tremove (lua_State *L) {
  int e = aux_getn(L, 1);
  int pos = luaL_optint(L, 2, e);
  if (!(1 <= pos && pos <= e))  /* position is outside bounds? */
   return 0;  /* nothing to remove */
```

**Comment by desb42** [comment] 2019-11-03 07:58
Great work (as always) 
As a matter of protocol, should I close the issues that I raise, once they seem to be fixed, or let you close them?

**Comment by gnosygnu** [comment] 2019-11-03 20:21
> Great work (as always)

Haha! Thanks!

> As a matter of protocol, should I close the issues that I raise, once they seem to be fixed, or let you close them?

Up to you. Feel free to close any issue you raised. I usually leave them open -- just in case anything happens -- but end up closing them out within several days or so.

**Closed by gnosygnu** 2019-11-03 20:21 UTC
Labels: [effort 4 - less than a day], [priority 2 - major], [resolved - commit], [risk 3 - moderate], [schedule 2 - within weeks], [type - bug], core - parser, xtn - lua

**Comment by gnosygnu** [comment] 2019-11-03 20:25
Also, just noticed that I left several issues open. Mass closed them now. Thanks for reminder by inferral!
