### ISSUE TITLE
Fix failed jawiki import due to foreign-language names  [#594] (mid failed: bgn=19 end=13)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#594] opened 2019-10-08 16:29 UTC
just started to try to build jawiki and got the above

in researching this it seems to come down to the routine Ttl_()
in 400_xowa\src\gplx\xowa\wikis\data\tbls\Xowd_page_itm.java

the line

    ttl_page_db = Bry_.Mid(v, ns.Name_ui_w_colon().length, v.length);
`v` contains `Template:Stub` (13 byte long)
`ns.Name_ui_w_colon().length` is 19
This 19 comes from `テンプレート` the japanese for 'Template' (sort of)

This Japanese in turn comes from the file bin\any\xowa\cfg\wiki\core\ja.wikipedia.org.gfs
which is redefining namespace 10 (aka Template)

I suspect that the code just above

    Object o = ns_mgr.Names_get_w_colon(v, 0, v.length);
`Template:` is being matched to a namespace object; however the name stored for it has been overwritten by ja.wikipedia.org.gfs 

hopefully that makes sense

**Comment by desb42** [comment] 2019-10-08 17:01
my current 'fix' is to change (Line 112)

    ttl_page_db = Bry_.Mid(v, ns.Name_ui_w_colon().length, v.length);
to

    int colon_pos = Bry_find_.Find_fwd(v, Byte_ascii.Colon, 0, v.length);
    ttl_page_db = Bry_.Mid(v, colon_pos+1, v.length);

**Comment by gnosygnu** [comment] 2019-10-13 15:33
Oops. I'm a bit surprised how this is broken, as it should have failed during every jawiki build, and I've built in the past.

At any rate, fixed with a variant of the approach above. Thanks for isolating the cause, as well as the excellent write-up!

**Closed** 2019-11-03 20:22 UTC
Labels: [effort 5 - less than an hour], [priority 3 - moderate], [resolved - commit], [risk 3 - moderate], [schedule 1 - within days], [type - bug], core - parser
