### ISSUE TITLE
v2.7.2.1: Handle broken downloads at http://dumps.wikimedia.org/ does not work for de.wikipedia.org; de.wikisource.org

### ISSUE THREAD

**Issue by AnselmD** [gnosygnu/xowa#7] opened 2015-07-17 20:30 UTC
v2.7.2.1: Handle broken downloads at http://dumps.wikimedia.org/ 

I am using 2.7.2.1, but the import of de.wikipedia.org fails:
"download failed. Please select 'read from file' ...

**Comment by gnosygnu** [comment] 2015-07-17 22:57
Hey, thanks for the report.

I tried to reproduce it now, but wasn't able to. I'm using Help:Import/List. See the screenshot and the status text at the bottom.

Are you sure you don't have "Web access enabled" set to false at Help:Options/Security ?

![dewiki](https://cloud.githubusercontent.com/assets/4994104/8758732/a0233dea-2cb5-11e5-9e0c-921a3bc20d1e.png)

**Comment by AnselmD** [comment] 2015-07-18 07:27
"Web access enabled" is checked

xowa zip file was unpacked in a new drectory

session.log

```
Special:XowaSystemData
From XOWA: a free, open-source, offline wiki application

Path: C:\Users\ad\Downloads\xowa_app_windows_64_v2.7.2.1\user\anonymous\app\tmp\log\current\session.txt

20150717_224056.671 term:log_wtr
20150717_224056.671 term:log_mgr
20150717_224056.671 term:wiki_mgr
20150717_224056.687 swt.kit.term:bgn
20150717_224056.687 swt.kit.term:cursor
20150718_070436.905 env.init: version=2.7.2.1
20150718_070436.921 env.init: jar_url=xowa_windows_64.jar; build_date=2015-07-13 01:17
20150718_070436.921 env.init: op_sys=windows64
20150718_070436.937 
arguments:
  **** NONE ****
  use --help to show help

20150718_070437.108 app.init
20150718_070437.124 db.schema.load.bgn: conn=data source=C:\Users\ad\Downloads\xowa_app_windows_64_v2.7.2.1\user\xowa.user.anonymous.sqlite3;version=3;
20150718_070437.249 db.schema.load.end
20150718_070437.389 gfs.done: C:\Users\ad\Downloads\xowa_app_windows_64_v2.7.2.1\bin\windows_64\xowa\cfg\xowa_cfg_os.gfs
20150718_070437.405 gfs.done: C:\Users\ad\Downloads\xowa_app_windows_64_v2.7.2.1\user\anonymous\app\data\cfg\xowa_user_cfg.gfs
20150718_070437.405 gfs.done: C:\Users\ad\Downloads\xowa_app_windows_64_v2.7.2.1\user\anonymous\app\data\cfg\user_custom_cfg.gfs
20150718_070437.405 gfs.done: C:\Users\ad\Downloads\xowa_app_windows_64_v2.7.2.1\xowa.gfs
20150718_070437.405 app.upgrade.done
20150718_070437.405 wiki.init.bgn: home
20150718_070437.483 wiki.init.end
20150718_070437.545 swt.kit.init.done
20150718_070438.732 page.load: url=home/wiki/Help:Import/List
20150718_070438.153 app.gui.kit_init.done
20150718_070438.216 app.gui.win_load.done
20150718_070438.216 app.launch.page.bgn
20150718_070438.732 app.launch.page.end
20150718_070439.231 jtidy.init; elapsed=31
20150718_070439.605 page.async: url=home/wiki/Help:Import/List
20150718_070517.654 page.load: url=home/wiki/Help:Options
20150718_070517.935 page.async: url=home/wiki/Help:Options
20150718_070619.648 page.load: url=home/wiki/Help:Options/Security
20150718_070619.695 page.async: url=home/wiki/Help:Options/Security
20150718_070653.781 page.load: url=home/wiki/Help:Import/List
20150718_070653.968 page.async: url=home/wiki/Help:Import/List
20150718_070704.264 url: https://dumps.wikimedia.org/dewiki/latest/dewiki-latest-pages-articles.xml.bz2
20150718_070704.607 download fail: src='https://dumps.wikimedia.org/dewiki/latest/dewiki-latest-pages-articles.xml.bz2' trg='C:\Users\ad\Downloads\xowa_app_windows_64_v2.7.2.1\wiki\de.wikipedia.org\dewiki-latest-pages-articles.xml.bz2' error='https://dumps.wikimedia.org/dewiki/latest/dewiki-latest-pages-articles.xml.bz2'
20150718_070716.330 page.load: url=home/wiki/Help:Change_log
20150718_070716.377 page.async: url=home/wiki/Help:Change_log



This page was last modified on 2015-07-18, at 09:07.

    Version
    Build-Zeitpunkt
    2.7.2.1
    2015-07-13 01:17
```

So i do not have an idea...

For myself i will download it manually including the the discussions (pages-meta-current.xml.bz2).

**Comment by gnosygnu** [comment] 2015-07-19 01:51
Ok. Thanks for the log

That's weird. I tried again and it still works. See my log excerpt below.

```
20150719_014801.984 page.async: url=home/wiki/Help:Import/List
20150719_014815.828 url: https://dumps.wikimedia.org/dewiki/20150602/dewiki-20150602-pages-articles.xml.bz2
20150719_014917.671 page.load: url=home/wiki/Special:XowaDefaultTab
```

I'll add some more logging to v2.7.3 to track it. If you get a chance, bring it down and try again.

**Comment by AnselmD** [comment] 2015-07-20 13:01
Are there enough information which helps you?

```
Special:XowaSystemData
From XOWA: a free, open-source, offline wiki application

Path: C:\Users\ad\Downloads\xowa_app_windows_64_v2.7.3.1\user\anonymous\app\tmp\log\current\session.txt

20150720_125232.191 env.init: version=2.7.3.1
20150720_125232.221 env.init: jar_url=xowa_windows_64.jar; build_date=2015-07-20 02:40
20150720_125232.221 env.init: op_sys=windows64
20150720_125232.221 
arguments:
  **** NONE ****
  use --help to show help

20150720_125232.401 app.init
20150720_125232.401 creating user_system_cfg.gfs: C:\Users\ad\Downloads\xowa_app_windows_64_v2.7.3.1\user\anonymous\app\data\cfg\user_system_cfg.gfs
20150720_125232.531 db.schema.load.bgn: conn=data source=C:\Users\ad\Downloads\xowa_app_windows_64_v2.7.3.1\user\xowa.user.anonymous.sqlite3;version=3;
20150720_125232.541 db.schema.load.end
20150720_125232.721 creating bookmarks page
20150720_125232.761 wiki.init: circular call canceled: home
20150720_125232.761 wiki.init: circular call canceled: home
20150720_125232.761 wiki.init: circular call canceled: home
20150720_125232.761 wiki.init: circular call canceled: home
20150720_125232.761 wiki.init: circular call canceled: home
20150720_125232.761 wiki.init: circular call canceled: home
20150720_125232.721 wiki.init.bgn: home
20150720_125232.771 wiki.init.end
20150720_125232.791 moving history files
20150720_125232.791 moved history files: 0
20150720_125232.801 xowa_cfg_os generated; url=C:\Users\ad\Downloads\xowa_app_windows_64_v2.7.3.1\bin\windows_64\xowa\cfg\xowa_cfg_os.gfs
20150720_125232.801 gfs.done: C:\Users\ad\Downloads\xowa_app_windows_64_v2.7.3.1\bin\windows_64\xowa\cfg\xowa_cfg_os.gfs
20150720_125232.811 gfs.done: C:\Users\ad\Downloads\xowa_app_windows_64_v2.7.3.1\user\anonymous\app\data\cfg\xowa_user_cfg.gfs
20150720_125232.821 gfs.done: C:\Users\ad\Downloads\xowa_app_windows_64_v2.7.3.1\user\anonymous\app\data\cfg\user_custom_cfg.gfs
20150720_125232.821 gfs.done: C:\Users\ad\Downloads\xowa_app_windows_64_v2.7.3.1\xowa.gfs
20150720_125232.821 setup:checking if dir exists: version_prv= version_del=1.8.2.1 dir=C:\Users\ad\Downloads\xowa_app_windows_64_v2.7.3.1\user\anonymous\lang\
20150720_125232.821 setup:checking if dir exists: version_prv= version_del=1.8.2.1 dir=C:\Users\ad\Downloads\xowa_app_windows_64_v2.7.3.1\user\anonymous\wiki\#cfg\
20150720_125232.821 setup:checking if dir exists: version_prv= version_del=1.10.2.1 dir=C:\Users\ad\Downloads\xowa_app_windows_64_v2.7.3.1\bin\any\javascript\
20150720_125232.821 setup:checking if dir exists: version_prv= version_del=1.10.2.1 dir=C:\Users\ad\Downloads\xowa_app_windows_64_v2.7.3.1\bin\any\xowa\html\modules\
20150720_125232.821 converted options to v2
20150720_125232.821 app.upgrade.done
20150720_125232.831 wiki.init.bgn: home
20150720_125232.851 wiki.init.end
20150720_125232.911 swt.kit.init.done
20150720_125235.692 page.load: url=home/wiki/Main_Page
20150720_125233.361 app.gui.kit_init.done
20150720_125233.401 app.gui.win_load.done
20150720_125233.411 app.launch.page.bgn
20150720_125235.692 app.launch.page.end
20150720_125236.092 jtidy.init; elapsed=10
20150720_125236.142 page.async: url=home/wiki/Main_Page
20150720_125244.722 page.load: url=home/wiki/Help:Import/List
20150720_125245.062 page.async: url=home/wiki/Help:Import/List
20150720_125252.412 url: https://dumps.wikimedia.org/dewiki/latest/dewiki-latest-pages-articles.xml.bz2
20150720_125252.762 download fail: src='https://dumps.wikimedia.org/dewiki/latest/dewiki-latest-pages-articles.xml.bz2' trg='C:\Users\ad\Downloads\xowa_app_windows_64_v2.7.3.1\wiki\de.wikipedia.org\dewiki-latest-pages-articles.xml.bz2' error='https://dumps.wikimedia.org/dewiki/latest/dewiki-latest-pages-articles.xml.bz2'



This page was last modified on 2015-07-20, at 14:53.

    Version
    Build-Zeitpunkt
    2.7.3.1
    2015-07-20 02:40
```
![2015-07-20 14_57_43-](https://cloud.githubusercontent.com/assets/6770907/8776243/edc84ba8-2eef-11e5-9ebe-257e86de836e.png)

**Comment by AnselmD** [comment] 2015-07-20 13:07
Windows XP & Java 7

```
Special:XowaSystemData
From XOWA: a free, open-source, offline wiki application

Path: C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\Downloads\xowa_app_windows_v2.7.3.1\user\anonymous\app\tmp\log\current\session.txt

20150720_130303.000 env.init: version=2.7.3.1
20150720_130303.812 env.init: jar_url=xowa_windows.jar; build_date=2015-07-20 02:40
20150720_130303.812 env.init: op_sys=windows32
20150720_130303.812 
arguments:
  **** NONE ****
  use --help to show help

20150720_130304.703 app.init
20150720_130304.703 creating user_system_cfg.gfs: C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\Downloads\xowa_app_windows_v2.7.3.1\user\anonymous\app\data\cfg\user_system_cfg.gfs
20150720_130307.453 db.schema.load.bgn: conn=data source=C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\Downloads\xowa_app_windows_v2.7.3.1\user\xowa.user.anonymous.sqlite3;version=3;
20150720_130307.515 db.schema.load.end
20150720_130308.843 creating bookmarks page
20150720_130308.984 wiki.init: circular call canceled: home
20150720_130308.984 wiki.init: circular call canceled: home
20150720_130308.984 wiki.init: circular call canceled: home
20150720_130308.984 wiki.init: circular call canceled: home
20150720_130308.984 wiki.init: circular call canceled: home
20150720_130308.984 wiki.init: circular call canceled: home
20150720_130308.859 wiki.init.bgn: home
20150720_130309.015 wiki.init.end
20150720_130309.109 moving history files
20150720_130309.109 moved history files: 0
20150720_130309.187 xowa_cfg_os generated; url=C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\Downloads\xowa_app_windows_v2.7.3.1\bin\windows\xowa\cfg\xowa_cfg_os.gfs
20150720_130309.203 gfs.done: C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\Downloads\xowa_app_windows_v2.7.3.1\bin\windows\xowa\cfg\xowa_cfg_os.gfs
20150720_130309.265 gfs.done: C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\Downloads\xowa_app_windows_v2.7.3.1\user\anonymous\app\data\cfg\xowa_user_cfg.gfs
20150720_130309.281 gfs.done: C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\Downloads\xowa_app_windows_v2.7.3.1\user\anonymous\app\data\cfg\user_custom_cfg.gfs
20150720_130309.281 gfs.done: C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\Downloads\xowa_app_windows_v2.7.3.1\xowa.gfs
20150720_130309.281 setup:checking if dir exists: version_prv= version_del=1.8.2.1 dir=C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\Downloads\xowa_app_windows_v2.7.3.1\user\anonymous\lang\
20150720_130309.281 setup:checking if dir exists: version_prv= version_del=1.8.2.1 dir=C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\Downloads\xowa_app_windows_v2.7.3.1\user\anonymous\wiki\#cfg\
20150720_130309.281 setup:checking if dir exists: version_prv= version_del=1.10.2.1 dir=C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\Downloads\xowa_app_windows_v2.7.3.1\bin\any\javascript\
20150720_130309.281 setup:checking if dir exists: version_prv= version_del=1.10.2.1 dir=C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\Downloads\xowa_app_windows_v2.7.3.1\bin\any\xowa\html\modules\
20150720_130309.296 converted options to v2
20150720_130309.296 app.upgrade.done
20150720_130309.296 wiki.init.bgn: home
20150720_130309.390 wiki.init.end
20150720_130309.953 swt.kit.init.done
20150720_130314.921 page.load: url=home/wiki/Main_Page
20150720_130311.859 app.gui.kit_init.done
20150720_130312.140 app.gui.win_load.done
20150720_130312.140 app.launch.page.bgn
20150720_130314.921 app.launch.page.end
20150720_130315.781 jtidy.init; elapsed=125
20150720_130315.984 page.async: url=home/wiki/Main_Page
20150720_130327.703 page.load: url=home/wiki/Help:Import/List
20150720_130328.843 page.async: url=home/wiki/Help:Import/List
20150720_130341.375 url: https://dumps.wikimedia.org/dewiki/latest/dewiki-latest-pages-articles.xml.bz2
20150720_130341.734 download fail: src='https://dumps.wikimedia.org/dewiki/latest/dewiki-latest-pages-articles.xml.bz2' trg='C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\Downloads\xowa_app_windows_v2.7.3.1\wiki\de.wikipedia.org\dewiki-latest-pages-articles.xml.bz2' error='https://dumps.wikimedia.org/dewiki/latest/dewiki-latest-pages-articles.xml.bz2'



This page was last modified on 2015-07-20, at 15:04.

    Version
    Build-Zeitpunkt
    2.7.3.1
    2015-07-20 02:40
```
![xp](https://cloud.githubusercontent.com/assets/6770907/8776397/10d9d890-2ef1-11e5-828c-30d5575b0e4c.png)

**Comment by AnselmD** [comment] 2015-07-20 13:24
Ubuntu & Java 8


```
Special:XowaSystemData
From XOWA: a free, open-source, offline wiki application

Path: /home/da/Downloads/xowa_app_linux_64_v2.7.3.1/user/anonymous/app/tmp/log/current/session.txt

20150720_131645.441 env.init: version=2.7.3.1
20150720_131645.496 env.init: jar_url=xowa_linux_64.jar; build_date=2015-07-20 02:40
20150720_131645.497 env.init: op_sys=linux64
20150720_131645.502 
arguments:
  **** NONE ****
  use --help to show help

20150720_131646.170 app.init
20150720_131646.171 creating user_system_cfg.gfs: /home/da/Downloads/xowa_app_linux_64_v2.7.3.1/user/anonymous/app/data/cfg/user_system_cfg.gfs
20150720_131646.388 db.schema.load.bgn: conn=data source=/home/da/Downloads/xowa_app_linux_64_v2.7.3.1/user/xowa.user.anonymous.sqlite3;version=3;
20150720_131646.396 db.schema.load.end
20150720_131646.963 creating bookmarks page
20150720_131646.976 wiki.init: circular call canceled: home
20150720_131646.977 wiki.init: circular call canceled: home
20150720_131646.978 wiki.init: circular call canceled: home
20150720_131646.981 wiki.init: circular call canceled: home
20150720_131646.981 wiki.init: circular call canceled: home
20150720_131646.982 wiki.init: circular call canceled: home
20150720_131646.964 wiki.init.bgn: home
20150720_131646.991 wiki.init.end
20150720_131647.042 moving history files
20150720_131647.043 moved history files: 0
20150720_131647.091 xowa_cfg_os generated; url=/home/da/Downloads/xowa_app_linux_64_v2.7.3.1/bin/linux_64/xowa/cfg/xowa_cfg_os.gfs
20150720_131647.103 gfs.done: /home/da/Downloads/xowa_app_linux_64_v2.7.3.1/bin/linux_64/xowa/cfg/xowa_cfg_os.gfs
20150720_131647.123 gfs.done: /home/da/Downloads/xowa_app_linux_64_v2.7.3.1/user/anonymous/app/data/cfg/xowa_user_cfg.gfs
20150720_131647.124 gfs.done: /home/da/Downloads/xowa_app_linux_64_v2.7.3.1/user/anonymous/app/data/cfg/user_custom_cfg.gfs
20150720_131647.124 gfs.done: /home/da/Downloads/xowa_app_linux_64_v2.7.3.1/xowa.gfs
20150720_131647.126 setup:checking if dir exists: version_prv= version_del=1.8.2.1 dir=/home/da/Downloads/xowa_app_linux_64_v2.7.3.1/user/anonymous/lang/
20150720_131647.126 setup:checking if dir exists: version_prv= version_del=1.8.2.1 dir=/home/da/Downloads/xowa_app_linux_64_v2.7.3.1/user/anonymous/wiki/#cfg/
20150720_131647.127 setup:checking if dir exists: version_prv= version_del=1.10.2.1 dir=/home/da/Downloads/xowa_app_linux_64_v2.7.3.1/bin/any/javascript/
20150720_131647.127 setup:checking if dir exists: version_prv= version_del=1.10.2.1 dir=/home/da/Downloads/xowa_app_linux_64_v2.7.3.1/bin/any/xowa/html/modules/
20150720_131647.140 shutting down app; saving cfg: len=75
20150720_131647.142 app.upgrade.done
20150720_131647.143 wiki.init.bgn: home
20150720_131647.246 wiki.init.end
20150720_131647.415 swt.kit.init.done
20150720_131648.443 page.load: url=home/wiki/Main_Page
20150720_131648.028 app.gui.kit_init.done
20150720_131648.122 app.gui.win_load.done
20150720_131648.124 app.launch.page.bgn
20150720_131648.444 app.launch.page.end
20150720_131648.875 jtidy.init; elapsed=37
20150720_131649.068 page.async: url=home/wiki/Main_Page
20150720_131653.566 page.load: url=home/wiki/Help:Import/List
20150720_131654.773 page.async: url=home/wiki/Help:Import/List
20150720_131702.761 url: https://dumps.wikimeda.org/dewiki/latest/dewiki-latest-pages-articles.xml.bz2
20150720_131703.149 download fail: src='https://dumps.wikimeda.org/dewiki/latest/dewiki-latest-pages-articles.xml.bz2' trg='/home/da/Downloads/xowa_app_linux_64_v2.7.3.1/wiki/de.wikipeda.org/dewiki-latest-pages-articles.xml.bz2' error='https://dumps.wikimeda.org/dewiki/latest/dewiki-latest-pages-articles.xml.bz2'



This page was last modified on 2015-07-20, at 15:17.

    version
    build time
    2.7.3.1
    2015-07-20 02:40
```

![screenshot from 2015-07-20 15 17 33](https://cloud.githubusercontent.com/assets/6770907/8776591/a09be8a0-2ef2-11e5-98af-a7471c84ed8a.png)

**Comment by gnosygnu** [comment] 2015-07-21 04:23
Thanks for the multiple logs. Really, I would have believed you after the first. :)

I still don't know what the issue is. I tried on 4 machines [1], and I don't get the error. My best guess is that it is regional (Germany versus USA). That's a far stretch though, but I'm out of ideas.

Unfortunately, while researching this issue, I discovered that there was a different bug in yesterday's release. It causes downloads to occur at your.org for partial dumps (like de.wikipedia.org).

I released v2.7.3.2 now. I don't think it will solve this issue, but please try it on one of your machines. Also, I added some logging that might help in debugging. It looks something like this: 

```
wmf.dump:connect rslts; url=https://dumps.wikimedia.org/dewiki/latest/dewiki-latest-pages-articles.xml.bz2 result=y fil_len=169 file_modified=1969-12-31 19:00:00 server_url=https://dumps.wikimedia.org/ dump_date=latest
```

Thanks again for all your help.

[1] Windows XP, Windows 7 64-bit, openSUSE 64-bit, Mac OS X 64-bit

**Comment by AnselmD** [comment] 2015-07-21 10:49
> Thanks for the multiple logs. Really, I would have believed you after the first. :)

Yes you, but not me :-)

BTW: How can i quote here?

Before I send you the new log, here an error message, when is starts xowa with:

java  -jar xowa_windows.jar

```
XOWA: the XOWA Offline Wiki Application
Copyright (c) 2012 gnosygnu@gmail.com

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

--------------------------------------------------------------------------------


version: 2.7.3.2; build date: 2015-07-21 03:47

arguments:
  **** NONE ****
  use --help to show help

1437475271064   addons.manager  ERROR   startup failed: [Exception... "Component
 returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIPrefBranch.setCh
arPref]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :
: resource://gre/modules/AddonManager.jsm :: AMI_startup :: line 645"  data: no]
 Stack trace: AMI_startup()@resource://gre/modules/AddonManager.jsm:645 < AMP_st
artup()@resource://gre/modules/AddonManager.jsm:2318 < AMC_observe()@resource://
```

**Comment by AnselmD** [comment] 2015-07-21 10:53
session.log
```
Special:XowaSystemData
From XOWA: a free, open-source, offline wiki application

Path: C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\Downloads\xowa_app_windows_v2.7.3.2\user\anonymous\app\tmp\log\current\session.txt

20150721_105219.890 env.init: version=2.7.3.2
20150721_105219.968 env.init: jar_url=xowa_windows.jar; build_date=2015-07-21 03:47
20150721_105219.968 env.init: op_sys=windows32
20150721_105220.031 
arguments:
  **** NONE ****
  use --help to show help

20150721_105220.781 app.init
20150721_105220.812 db.schema.load.bgn: conn=data source=C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\Downloads\xowa_app_windows_v2.7.3.2\user\xowa.user.anonymous.sqlite3;version=3;
20150721_105221.281 db.schema.load.end
20150721_105221.875 gfs.done: C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\Downloads\xowa_app_windows_v2.7.3.2\bin\windows\xowa\cfg\xowa_cfg_os.gfs
20150721_105221.921 gfs.done: C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\Downloads\xowa_app_windows_v2.7.3.2\user\anonymous\app\data\cfg\xowa_user_cfg.gfs
20150721_105221.921 gfs.done: C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\Downloads\xowa_app_windows_v2.7.3.2\user\anonymous\app\data\cfg\user_custom_cfg.gfs
20150721_105221.921 gfs.done: C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\Downloads\xowa_app_windows_v2.7.3.2\xowa.gfs
20150721_105221.937 app.upgrade.done
20150721_105221.937 wiki.init.bgn: home
20150721_105222.281 wiki.init.end
20150721_105222.468 swt.kit.init.done
20150721_105225.984 page.load: url=home/wiki/Special:XowaSystemData
20150721_105223.640 app.gui.kit_init.done
20150721_105223.796 app.gui.win_load.done
20150721_105223.796 app.launch.page.bgn
20150721_105225.984 app.launch.page.end
20150721_105226.343 page.async: url=home/wiki/Special:XowaSystemData
20150721_105229.906 page.load: url=home/wiki/Help:Import/List
20150721_105230.609 jtidy.init; elapsed=94
20150721_105231.656 page.async: url=home/wiki/Help:Import/List
20150721_105242.109 wmf.dump:connect log; url=https://dumps.wikimedia.org/dewiki/latest/dewiki-latest-pages-articles.xml.bz2 result=y fil_len=169 file_modified=1970-01-01 01:00:00 server_url=https://dumps.wikimedia.org/ dump_date=latest
20150721_105242.109 url: https://dumps.wikimedia.org/dewiki/latest/dewiki-latest-pages-articles.xml.bz2
20150721_105244.484 download fail: src='https://dumps.wikimedia.org/dewiki/latest/dewiki-latest-pages-articles.xml.bz2' trg='C:\Dokumente und Einstellungen\Administrator\Eigene Dateien\Downloads\xowa_app_windows_v2.7.3.2\wiki\de.wikipedia.org\dewiki-latest-pages-articles.xml.bz2' error='https://dumps.wikimedia.org/dewiki/latest/dewiki-latest-pages-articles.xml.bz2'
```

**Comment by gnosygnu** [comment] 2015-07-21 12:16
> Yes you, but not me :-) 

Ah, your record is pretty good. I think you should believe yourself. ;)

> I have diffenent firwall software running at different systems.

Good idea, but actually something else. See below.

> BTW: How can i quote here?

I just copy and paste the comment and use ">" at the beginning of the line. Like this:

```
> (copy and paste comment)
```
> Before I send you the new log, here an error message, when is starts xowa with:

Yeah, this is an SWT / XULRunner issue. It doesn't actually do anything. There's a bug on it: https://bugs.eclipse.org/bugs/show_bug.cgi?id=466391 . I made a note of it in the help file as well: home/wiki/Help:HTML Browser

> wmf.dump:connect log; url=https://dumps.wikimedia.org/dewiki/latest/dewiki-latest-pages-articles.xml.bz2 result=y fil_len=169 file_modified=1970-01-01 01:00:00 server_url=https://dumps.wikimedia.org/ dump_date=latest

Ok. I see what the problem is. I'm using a crappy way of determining whether or not the file doesn't exist by checking the file time. Right now it's UnixTime < 0. For me, it works because I'm in EDT and I have a file_modified time of 1969-12-31 19:00:00. Your German time zone doesn't work for my check. You can verify by setting your time zone to EDT before you click download.

Let me know if this works. If so, I may fix this in another release tonight.

Thanks!

**Comment by AnselmD** [comment] 2015-07-21 13:50
>Ok. I see what the problem is. I'm using a crappy way of determining whether or not the file doesn't exist by checking the file time. Right now it's UnixTime < 0. For me, it works because I'm in EDT and I have a file_modified time of 1969-12-31 19:00:00. Your German time zone doesn't work for my check. You can verify by setting your time zone to EDT before you click download.

Ok, I do not change the change my timezone at my os, but as commandline parameter:
```
java -DTZ=EDT -jar xowa_windows.jar
```

This works! :-)

**Comment by gnosygnu** [comment] 2015-07-22 00:16
Cool. Thanks for the confirmation!

I uploaded v2.7.3.3 just now. I tested by switching my time zone to Fiji. Works

Let me know if there's anything else. Otherwise, I'll close this ticket out in a few days.

Thanks again!

**Closed** 2015-07-28 02:32 UTC
Labels: import
