### ISSUE TITLE
Page "Search feature" does not work properly with numbers.

### ISSUE THREAD

**Issue by XowaWilliam** [gnosygnu/xowa#119] opened 2016-12-29 00:39 UTC
The page Search feature does not work properly with numbers.

For example, if you open **en.wikipedia** to the home page the number **2016** should appear highlighted 5 times, however, when you type in **2016**, nothing is highlight.

The current work around... Type in **2016** with a **space** following, then click **backspace**, and only then are all the **2016** numbers are highlighted.

Tests were done on current Xowa 3.12.1.1  and older Xowa 2.6.5.1 and the results were the same.

**Comment by gnosygnu** [comment] 2016-12-29 01:46
Hi! Thanks for the detailed steps.

Unfortunately, I tried it now, and couldn't reproduce it. I attach a gif below. Note the following:
* I only have 3 instances of <code>2016</code>
* After I type in 2016, the first instance is highlighted in blue at the top right of the page
* I then scroll down to the bottom of the page and there are two other instances highlighted in yellow (hard to see, as the quality is not good in the gif)

Let me know if I'm doing anything differently. Thanks!

![search](https://cloud.githubusercontent.com/assets/4994104/21535117/a52729fc-cd3e-11e6-9d15-27cd85f859ca.gif)

**Comment by XowaWilliam** [comment] 2016-12-29 05:22
I never went to the page you suggested, because I discovered the problem just before going there. 

Upon receiving your reply I thought _"This is impossible! Am I going nuts!?"_

So after pondering the situation for a while, I thought of using the line of number keys above the qwerty part of the keyboard and it worked perfectly.

Went back to the keypad numbers right of qwerty keyboard, and these failed not work in the same manner.

This is kind of weird, in that they only work after you use the **Backspace** key.

Maybe you can explain why this is, and why the two number systems appear to act independently from each other.

**Comment by gnosygnu** [comment] 2016-12-30 04:10
> Went back to the keypad numbers right of qwerty keyboard, and these failed to work in the same manner.

Ah! Nice thinking on your part! Yes, I am using the number keys in the top row -- not the number keys in the keypad on the right.

The right keypad keys use different keycodes which XOWA has never recognized. In fact, for due disclosure, I don't even have a right keypad on my keyboard. :)

This should be fixed for the upcoming release this Sunday (or possibly Monday). I'll comment again in this thread when it's finally released.

Thanks!

**Comment by gnosygnu** [comment] 2017-01-04 02:52
This issue was resolved in tonight's release: https://github.com/gnosygnu/xowa/releases

I'm going to go ahead and close this issue. Let me know if there's anything else. Thanks!

**Comment by XowaWilliam** [comment] 2017-01-07 06:30
Hi Mr Gnosygnu .

I just got round to testing this recent NUMPAD KEYS problem in recent 
update  v4.0.0.1701 and the problem has not been fully resolved.
It sort of works, but not in the same way as the upper number keys work.

For example, when you press the "1" key ( upper row keys ) , all the 
numbers on the page with "1" are highlighted.
If you press the "1" key ( NUMPAD ) , no numbers on the page with "1" 
are highlighted.

Hope this helps. :)

William

**Comment by gnosygnu** [comment] 2017-01-08 02:48
Hi! I tried it again just now and it does work on my side. I'm using a pretty generic keyboard (Dell Keyboard KB212-B).

When you get a chance, can you try the following?:
* Go to home/wiki/Special:XowaCfg?grp=xowa.gui.shortcuts
* Click the "Wrench" icon next to any of the shortcuts (App - Exit, Back, Forward, etc.)
* A window should pop up and automatically set the cursor to in the Binding box
* Press the 1 key on your number pad. I get a keycode of <code>49</code>
* Press the 1 key in the top row. I get a keycode of <code>49</code> as well

If you're getting different numbers, then that would explain something. Otherwise, if you're getting the same number <code>49</code>, then I don't know why the numpad key wouldn't work the same as the top row key.

Let me know if you need other info. Thanks!

**Comment by XowaWilliam** [comment] 2017-01-08 03:11
I need help here.
Using the link you gave leads to a blank page, and trying to find it manually was also unfruitful.
This is the link I used.
**home/wiki/Special:XowaCfg?grp=xowa.gui.shortcuts**

**Comment by gnosygnu** [comment] 2017-01-08 03:14
Hmm..... That should work. I tried it again on my side just now.

You can also try home/wiki/Options/Shortcuts.

If you want to chat, I just jumped on IRC at http://webchat.freenode.net/?channels=#xowa

**Comment by XowaWilliam** [comment] 2017-01-08 03:42
OK this is what I found...
I clicked "show key binding" and a little menu popped up.
I typed in 1 upper number keys and got 49
I typed in 1 in NUMPAD keys and got 16777265

![keybinding](https://cloud.githubusercontent.com/assets/12995082/21747116/3a797de2-d565-11e6-99e8-d0f814c916e9.jpg)

**Comment by gnosygnu** [comment] 2017-01-08 03:47
Cool. Thanks for the screenshot.

I think you're still on an old version. The new version would change the 16777265 to a 49. In addition, it has a "Clear" button next to "Ok" and "Cancel". See my screenshot below. I imagine yours doesn't look like mine at all.

You can also go to <code>home/wiki/Help/About</code> to double-check the version. It reads the version info directly from the jar.

![xowa_shortcuts](https://cloud.githubusercontent.com/assets/4994104/21747126/fa7eb6ba-d52a-11e6-9caa-41cbaa375809.png)

**Comment by XowaWilliam** [comment] 2017-01-08 03:55
Sorry... This is all my fault.
I accidently rebuilt latest January en.wiki with previous version instead of latest version of Xowa I downloaded this week. Don't know how that happened.
Will rebuild and confirm later.

**Comment by gnosygnu** [comment] 2017-01-08 03:59
No worries. Let me know what you turn up. I'll keep the ticket open for a week or so.

Thanks!

**Comment by XowaWilliam** [comment] 2017-01-08 04:14
OK without rebuilding, I just overwrote the previous version with current v4.0.0.1701 of Xowa.
Surprise surprise... Whole new menu :+1: 
No wonder I could not follow your instructions :)
Once again I am sorry for wasting your time on my account.

I can confirm that the NUMPAD keys works perfectly. :100:

**Comment by gnosygnu** [comment] 2017-01-08 04:19
Cool. Good to hear!

Just so you know, you can always overwrite a previous version with a later version. I always test by making sure that this approach works.

I'm going to go ahead and close the ticket. Let me know if there's anything else.

Thanks!

**Closed by gnosygnu** 2017-01-08 04:19 UTC
Labels: gui, resolved
