### ISSUE TITLE
Wikibase: Parse e as exponent in wikidata json (precision in globecoordinate not handling engineering format)

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#565] opened 2019-09-05 08:35 UTC
Looking at en.wikipedia.org/wiki/San_Andres,_Romblon
xowa gives
![coords1](https://user-images.githubusercontent.com/861631/64325243-b1311d80-cfbf-11e9-8c9c-fb31c1aeb8ad.jpg)
and mediawiki
![coords2](https://user-images.githubusercontent.com/861631/64325261-b8582b80-cfbf-11e9-9b9e-c5f744f8f489.jpg)
The coordinate info comes from wikidata
specifically (from Q174667)

    , "P625":
      [ 
        { "mainsnak":
          { "snaktype":"value"
          , "property":"P625"
          , "hash":"8951ea0a096e1c828f786a437f1859c0fbb8c1fc"
          , "datavalue":
            { "value":
              { "latitude":12.533333
              , "longitude":122.025
              , "altitude":null
              , "precision":1.0e-5
              , "globe":"http:\/\/www.wikidata.org\/entity\/Q2"
              }
            , "type":"globecoordinate"
            }
          }
 Note that `precision` is 1.0e-5

It seems that xowa does not understand this notation
However changing this to 1.0E-5 (that is, capitalising 'e') makes it work

I have added the line

    raw = raw.replace('e', 'E');
to the routine 'parse'
in 100_core\src\gplx\Decimal_adp_.java
This seems to make it work

**Comment by gnosygnu** [comment] 2020-03-25 10:10
Nice breakdown, and sorry for the late reply on my side.

Fixed with the commit above. Thanks!

**Comment by gnosygnu** [comment] 2020-08-27 10:15
While looking at #792, I noticed that this bug was still surfacing. The problem is this line https://github.com/gnosygnu/xowa/blob/7b6b3ed09a00cca0efef71434e1baad5823f0ead/400_xowa/src/gplx/xowa/xtns/wbases/Wdata_prop_val_visitor.java#L190 which parses a json byte array directly (rather than call the json decimal method)

So, made the fix as desb42@ originally recommended. This is what I get for not listening to you. :)

**Closed** 2020-09-07 12:35 UTC
Labels: [effort 5 - less than an hour], [priority 3 - moderate], [resolved - commit], [risk 4 - minor], [schedule 3 - within months], [type - bug], core - parser, misc - commit submitted, xtn - wikibase
