### ISSUE TITLE
Scribunto: Do not return early in Gsub if source is String.empty (Module:ar-nominals:1668 Dual stem should end in -ān(i))

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#731] opened 2020-05-25 08:06 UTC
Have just built enwiktionary (2020-05-01) and have 4 of the above errors in the log

The code immediately above line 1668 is:

    if rfind(stem, ALIF .. NI .. "?$") then
        stem = rsub(stem, AOPTA .. NI .. "?$", "")
    elseif rfind(stem, AMAD .. NI .. "?$") then
        stem = rsub(stem, AMAD .. NI .. "?$", HAMZA_PH)
    else
        error("Dual stem should end in -an(i): '" .. stem .. "'")

I suspect a regex issue

**Comment by desb42** [comment] 2020-05-25 08:08
an example page is `en.wiktionary.org/wiki/%D8%BA%D9%8A%D8%B1_%D8%B7%D8%A8%D9%8A%D8%B9%D9%8A`
aka 'غير_طبيعي'

**Comment by desb42** [comment] 2020-07-18 08:06
Looking into this further I think I have identified the area of issue, it is not related to the sample code above

As part of generating the declension table quite a lot of initiation occurs.
Part of that is to work out some stems to work on
This is done in the function `stem_and_type`
Inside this function is a local function `local function sub`
This is where the 'magic' happens
The first two lines of this function are

    if rfind(sgar, arfrom) then
        local arret = rsub(sgar, arfrom, arto)
my reading of those two lines means that if the `rfind` succeeds then the `rsub` should produce something
As an example if `sgar` is '', `arfrom` is '$' and `arto` is 'a' then `arret` should end up as 'a'

Cutting this down to a simpler test
xowa lua

    function export.test3()
        local sgar = ''
        local arfrom = '$'
        local arto = 'aaa'
    dbg('t', rfind(sgar, arfrom))
    dbg('u', rsub(sgar, arfrom, arto))
    end
gives

    t 1 0 
    u  
mw lua

    function export.test3()
        local sgar = ''
        local arfrom = '$'
        local arto = 'aaa'
    mw.log('t', rfind(sgar, arfrom))
    mw.log('u', rsub(sgar, arfrom, arto))
    end
gives

    t	1	0
    u	aaa

**Comment by gnosygnu** [comment] 2020-07-20 04:38
Wow! Nice breakdown!

It looks like the problem is with these lines: https://github.com/gnosygnu/xowa/blob/398a1c854ae5df2511d11260df58e07473657e54/400_xowa/src/gplx/xowa/xtns/scribunto/libs/patterns/Scrib_pattern_matcher__xowa.java#L55-L57

The problem is that I was not considering regex flag characters like `$`. So, although it's impossible to match any letter (for example `a`) against a zero-length string, it IS possible to match a `$` (start of pattern) against a zero length string.

I'll fix that by removing the lines and adding the test (hopefully tomorrow morning)

Thanks!

**Comment by gnosygnu** [comment] 2020-07-20 12:29
Fixed with the commit above! Again, thanks a lot for all the details as well as the full triage (down to the lua snippets). Invaluable!

**Closed** 2020-07-23 12:25 UTC
Labels: [effort 3 - less than a week], [priority 2 - major], [resolved - commit], [risk 2 - major], [schedule 1 - within days], [type - bug], core - parser, misc - commit submitted, xtn - lua
