### ISSUE TITLE
Special:Search results display is blank for enwikt

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#606] opened 2019-10-22 07:47 UTC
One of the external links to `en.wikiquote.org/wiki/United_Kingdom` goes to enwiktionary with the link `en.wiktionary.org/wiki/Special:Search/united_kingdom`
Producing in xowa-gui

![blank_results](https://user-images.githubusercontent.com/861631/67265511-cd244c00-f4a5-11e9-9d26-6d2fbf82e475.jpg)
There are no Page titles being displayed

I also noticed that if I change the link to `en.wiktionary.org/wiki/Special:Search/United_Kingdom` (capital U and capital K), then the page `en.wiktionary.org/wiki/United_Kingdom` is displayed directly (I assume this is the intended behaviour)

**Comment by desb42** [comment] 2019-10-22 08:17
On further investigation I have found that the \<a> anchor is being generated but with no visible text

The issue seems related to line 37 in `400_xowa\src\gplx\xowa\addons\wikis\searchs\specials\htmls\Srch_html_row_bldr.java`
which reads

    lnki_bldr.Caption_direct_(row.Page_ttl_display(Bool_.Y));
if I change this to

    lnki_bldr.Caption_direct_(row.Page_ttl_display(Bool_.N));
The text appears (not really sure what the Bool_.Y is intending to do

**Comment by desb42** [comment] 2019-10-22 08:23
And another small thing
Given that there are (in this example) only four results, why is a `Next` button displayed?

**Comment by gnosygnu** [comment] 2019-11-12 04:29
I'm having problems reproducing it, primarily because I don't have the fullTextSearch for enwikt and my openSuse box crashes with a heap dump after 5 or so hours. I may have to reinstall the OS, which could be painful...

**Comment by desb42** [comment] 2019-11-12 11:56
I think that fullTextSearch refers to the lucene data generated by adding `indexer_enabled = 'y'` to the `mass_parse` step
If so, I have not created this data for my version of enwikt

This index used is being generated from the 'standard' step

    search.page__page_score
    search.link__link_score
    search.word__link_count

**Comment by gnosygnu** [comment] 2019-11-17 04:54
Yeah, sorry. ```fullTextSearch``` does refer to the ```indexer_enabled``` switch

I tried reproducing it on a regular build first, but didn't get any results. I did some more debugging today, and think I have a fix for this. I also fixed the blank empty rows (Regular search was basically broken)

I'll have a fix sometime tomorrow. Thanks

**Comment by gnosygnu** [comment] 2019-11-17 21:09
Pushed commits above. Summary below.

Sorry again for delay, but things have been busy recently on personal level. Let me know if anything else. Thanks!

---

* Regular search was showing empty results because it was always showing the highlighted title (highlighted title is specific to search suggest). 
  * I fixed it by adding more specific logic as to which title to use
  * I also added some tests to try to guard against future breakage
* Regular search (and probably full-text) would sometimes show empty results in xowa-gui (SWT) because the AJAX calls would return back faster than the GUI was ready (SWT was still loading the tab)
  * I fixed this by adding a simple flag to note when the GUI was done

**Closed** 2019-11-20 13:30 UTC
Labels: [effort 3 - less than a week], [priority 3 - moderate], [resolved - commit], [risk 3 - moderate], [schedule 2 - within weeks], [type - bug], xtn - search
