### ISSUE TITLE
font style for Headings

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#724] opened 2020-05-13 14:55 UTC
I was looking at `he.wikipedia.org/wiki/חוק_הזהב` in xowa-http
Viewing this page in Chrome
![font1](https://user-images.githubusercontent.com/861631/81813900-f0851600-951f-11ea-89b7-33bcb4ebb4c3.jpg)
The red ellipse shows the Page name

Most of the common CSS for wikimedia has the following in ithem

    .mw-body h1:lang(ja),
    .mw-body-content h1:lang(ja),
    .mw-body-content h2:lang(ja),
    .mw-body h1:lang(he),
    .mw-body-content h1:lang(he),
    .mw-body-content h2:lang(he),
    .mw-body h1:lang(ko),
    .mw-body-content h1:lang(ko),
    .mw-body-content h2:lang(ko) {
            font-family: sans-serif;
        }

That is, some specific languages play with the font for \<h1> and \<h2>

Looking at the wikimedia html for this page (specifically the Page name) shows:

    <h1 id="firstHeading" class="firstHeading" lang="he">חוק הזהב</h1>
whereas xowa shows:

    <h1 id="firstHeading" class="firstHeading">חוק הזהב</h1>
Once coded to add the language, it is now
![font2](https://user-images.githubusercontent.com/861631/81828123-59c15500-9531-11ea-98aa-aebe3608af9a.jpg)

I achieved this by adding an extra parameter to the Init routine of `400_xowa\src\gplx\xowa\wikis\pages\Xopg_page_heading.java` to capture the language code

please see
[font.zip](https://github.com/gnosygnu/xowa/files/4622731/font.zip)

**Comment by gnosygnu** [comment] 2020-05-14 13:52
Thanks for the detail! (and the commit!)

Will add in the next day or so. Some minor scribblings below for my reference.


```
	private byte[] lang_code;
```
---

```
		, pagename_for_tab
		, page.Html_data().Page_heading().Init(wiki, html_gen_tid == Xopg_view_mode_.Tid__read, page.Html_data(), page.Ttl().Full_db(), pagename_for_h1, page.Lang().Key_bry())
```

**Comment by gnosygnu** [comment] 2020-05-15 13:36
Resolved with the commit above.

FWIW, I downloaded hewiki today and couldn't reproduce the bug (mine looked like your 2nd image). That said, confirmed that the `lang` attribute is in the Wikimeda version, so change makes sense to me.

Also, as always, pretty impressive that you noticed the difference. I had to stare at your screenshots for 10 or 15 seconds to see the difference!

Thanks!

**Comment by desb42** [comment] 2020-05-16 06:05
This is very subtle, and I think browser dependent

There was no noticeable difference using xowa-gui; however using xowa-http and Chrome showed the issue

**Comment by gnosygnu** [comment] 2020-05-17 15:35
> There was no noticeable difference using xowa-gui; however using xowa-http and Chrome showed the issue

Yeah, FWIW, I tried with xowa-http and Chrome, but the title looked identical. My best guess is that it might be related to the files in `C:\xowa\user\anonymous\wiki\he.wikipedia.org` (I pulled down a new batch)

That said, the change above makes sense, and have no concerns from my side!

**Closed** 2020-05-27 12:26 UTC
Labels: [effort 4 - less than a day], [priority 2 - major], [resolved - commit], [risk 4 - minor], [schedule 1 - within days], [type - bug], core - parser, misc - commit submitted, xtn - i18n
