### ISSUE TITLE
frwiki image download stalled

### ISSUE THREAD

**Issue by desb42** [gnosygnu/xowa#414] opened 2019-03-31 08:58 UTC
I broke the frwiki dump into phases
1) build wikitext dbs
2) build html text dbs
3) download images

On the third phase after roughly four days of downloading, the process seems to be hung - nothing is happening, no cpu usage, network or disk activity
The console looks like
![console](https://user-images.githubusercontent.com/861631/55286846-1ccfe880-5399-11e9-820c-a9102f2d7cbb.jpg)

and the last four lines of the session.txt files are

    20190331_055913.081 failed: ttl=[[File:Diplomacia_con_nombre_de_mujer_(04)_(cropped).jpg|220px]]
    20190331_060948.799 download fail: src='https://upload.wikimedia.org/wikipedia/commons/6/61/Don_cusmano.jpg' trg='g:\xowa\file\commons.wikimedia.org\orig\6\1\4\6\Don_cusmano.jpg' error='https://upload.wikimedia.org/wikipedia/commons/6/61/Don_cusmano.jpg'
    20190331_060948.816 bin_mgr:thumb not found; wkr=xowa.http.wmf ttl=Don_cusmano.jpg w=150
    20190331_060948.817 failed: ttl=[[File:Don_cusmano.jpg|150px]]

It is now 20190331_0940...

I have just terminated the process
I am now left with a corrupt fr.wikipedia.org-file-core.xowa and a corrupt fr.wikipedia.org-file-ns.000-db.014.xowa
(I am using a 3GB threshold on filesize)

Is there any process to rebuild file-core or do I need to write one?
I do not want to spend another four days downloading if I can help it

**Comment by gnosygnu** [comment] 2019-03-31 14:51
> I am now left with a corrupt fr.wikipedia.org-file-core.xowa and a corrupt fr.wikipedia.org-file-ns.000-db.014.xowa
> (I am using a 3GB threshold on filesize)

That stinks. I'm surprised it's corrupt. I do TRANSACTIONs at checkpoints and have stopped the process in the past. But stranger things have happened.

Are you able to open it in sqlite console? If so, you can try to do things like ```PRAGMA integrity_check;``` and ```VACUUM``` which may help clean up the temp data.

If you can't open it, can you post it here (as a zip file)? I'd like to take a look at it.

> Is there any process to rebuild file-core or do I need to write one?

If the core db is truly corrupt, then unfortunately there's not much to do. It has a lot of metadata which is not in any of the bin databases. The bin databases will have the raw data, but there's no way to retrieve them (no name, no id) without the core db.

**Comment by desb42** [comment] 2019-04-02 14:49
(un)Fortunately the tool I was using gave the wrong impression about  fr.wikipedia.org-file-core.xowa and fr.wikipedia.org-file-ns.000-db.014.xowa
I have been able to access both of them with sqlited.exe
Thankfully 40Gb of download is not lost

I  am going to try to finish the image download now

**Comment by gnosygnu** [comment] 2019-04-04 04:10
> I have been able to access both of them with sqlited.exe

Cool. Good to hear. I usually just use the default sqlite3.exe (I bundle it with XOWA)

Let me know if anything else. Thanks

**Comment by gnosygnu** [comment] 2019-05-19 15:14
Marking this as unreproducible since the issue was with sqlite and corrupted databases. Let me know if anything else. Thanks.

**Closed by gnosygnu** 2019-05-19 15:14 UTC
Labels: [effort 5 - hour], [priority 2 - major], [resolved - unreproducible], [risk 2 - major], [schedule 1 - within days], [type - bug], core - make wiki, xtn - sqlite
